### ISSUE TITLE
Scheduler Hangs with 100% CPU usage (possible DST Issue?)

### ISSUE THREAD

**Issue by iammer** [node-schedule/node-schedule#11]
I have a scheduled job that runs everyday at 9:45pm.  Everything was working fine until today, when the node process hung with 100% CPU usage.  The next time this is scheduled to run is after a daylight savings time change, and I speculate that is causing the issue.  See code below to reproduce.  I see "Scheduling job.", then my CPU goes to 100% and I never see "Scheduling done."

I was previously using version 0.1.5 and I after I noticed the issue I switched to 0.1.7, but that did not resolve it.

Note: This may only fail the day before a daylight saving time change.

``` js
var schedule=require('node-schedule');

console.log('Scheduling job.');

schedule.scheduleJob({hour: 21, minute: 45},function() {
    console.log('Job ran');
});

console.log('Scheduling done.');
```

**Comment by valayDave** [comment]
This is happening to me right now 

`
var Jobs = appRequire('jobs');

var Scheduler = require('node-schedule');

var hourlyRule = new Scheduler.RecurrenceRule();
hourlyRule.minute = 60

Scheduler.scheduleJob(hourlyRule, function () {
    var inputObject = {startDate : new Date().setHours(0,0,0,0),endDate : new Date().setHours(23,59,59,999)}// specify time period here.
    Jobs.dailyCron(inputObject, function (err) {
        console.log(err);
    });
});
`

I have such a rule but once the process starts the CPU spikes to a 100% and all other processes on that machine Die. 

I am using Version 1.1.1

What should I Do?
