### ISSUE TITLE
How to manage jobs

### ISSUE THREAD

**Issue by DaAwesomeP** [node-schedule/node-schedule#110]
I'm building an application that will schedule and manage lots of scheduled tasks. However, I will not preserve the job's object. For instance, when the app starts, it will get a list from the database and schedule jobs with `each`. How can I manage jobs that have already been created? Are they assigned an id or name? I need to ability to cancel/modify them.

**Comment by tejasmanohar** [comment]
https://github.com/node-schedule/node-schedule/issues/54#issue-39080155

@ricardofbarros was working on a PR for the ID's

Till that's out in a major release, as far as I know, the answer is no. cc @santigimeno

**Comment by DaAwesomeP** [comment]
Hmm. I really don't want to be stuck with cron. It's not cross-platofrm (*cough*Windows*cough*).

I really like the ID idea though. A lot of the alternatives to this library use strings and not IDs. It's impossible to manage automatically.

I'll close this since it's really a duplicate.
