### ISSUE TITLE
About Date Scheduling 

### ISSUE THREAD

**Issue by k0ms** [node-schedule/node-schedule#111]
[Documentation] I think the parameter in the callback function should be "x".

From your sample code
var schedule = require('node-schedule');
var date = new Date(2012, 12, 21, 5, 30, 0);
var x = 'Tada!';
var j = schedule.scheduleJob(date, function(y){
    console.log(y);
}.bind(null,x));
x = 'Changing Data

**Comment by jonhester** [comment]
It's correct as is. Bind just passes the current value of `x` into the callback function as an argument so `y` could be anything as long as it matches what is in the `console.log` statement. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind for more info.
