### ISSUE TITLE
Thoughts on integrating Code Coverage reporting

### ISSUE THREAD

**Issue by jonhester** [node-schedule/node-schedule#113]
How would everyone feel about integrating code coverage reporting with something like https://codecov.io? I think there are some glaring holes in the current testing that would be wise to cover before any major rewriting. I did some work on simlify some of the recurrence rule code and all the tests were passing, but it wasn't actually working. I'd be happy to submit a pull request to have travis generate and submit code coverage.

**Comment by santigimeno** [comment]
I am not familiar with any code coverage tool at all, but anything that improves the quality of this project gets a :+1: from me. Thanks a lot!

**Comment by jonhester** [comment]
@santigimeno Cool, I should be able to do it tonight. I'll tie it into my fork so you can see what it looks like before merging/setting it up on your end.

**Comment by tejasmanohar** [comment]
:+1: sounds good to me, too. Also, want collaborator access? You've been helping a whole lot lately.

**Comment by jonhester** [comment]
@tejasmanohar Thanks, that'd be awesome.

**Comment by tejasmanohar** [comment]
No problem. It'll help when adding simple things to the README or rare, tiny fixes that don't need consensus from community. We'll discuss, and I'll push out formal releases to NPM.

**Comment by jonhester** [comment]
Sounds good.

**Comment by jonhester** [comment]
Codecov can't tell the difference between the actual master branch and a pull request, so I'm looking into coveralls now.

**Comment by jonhester** [comment]
Take a look at the pull request to see how this works. On Coveralls you can see the detailed info of each build and what lines are covered - https://coveralls.io/builds/2127456.

@tejasmanohar @santigimeno We also have two thresholds that we can set failure. A minimum coverage percentage and/or a maximum decrease in coverage percentage. Thoughts?

**Comment by tejasmanohar** [comment]
@jonhester Hmm, what are the defaults on those values?

**Comment by jonhester** [comment]
@tejasmanohar nothing, so it currently should never fail on coverage. Also, if the comments are annoying I can turn those off too. It still shows the percent coverage in the status.

![screen shot 2015-03-16 at 7 54 55 pm](https://cloud.githubusercontent.com/assets/3527123/6678986/7345cf8e-cc18-11e4-90ee-9fe96c43b333.png)

**Comment by jonhester** [comment]
@tejasmanohar @santigimeno Eeek. Guess it does fail by default if coverage decreases. I'm going ahead and setting it to only fail if coverage drops to by 10% or overall coverage is 80% so everything doesn't fail. I also disabled the comments since it's a bit noisy. Let me know what you think.

![screen shot 2015-03-16 at 9 39 34 pm](https://cloud.githubusercontent.com/assets/3527123/6679867/03893138-cc25-11e4-901c-0bcfd3f047c1.png)

**Comment by jonhester** [comment]
Ok, everything seems to be working now.

**Comment by tejasmanohar** [comment]
@jonhester Nice work! I guess we just test it and see :+1: if we have problems, re-open.

**Comment by jonhester** [comment]
@tejasmanohar yeah, there was definitely some wonkiness getting things started, but it should be good now. Next up is increasing the test coverage.
