### ISSUE TITLE
Travis CI Build Fail

### ISSUE THREAD

**Issue by tejasmanohar** [node-schedule/node-schedule#114]
My past release altering versions on `package.json` of some modules to make sure we're all on the same plate, including `nodeunit`, failed in Travis CI on only some Node versions.

https://travis-ci.org/node-schedule/node-schedule/jobs/54628773

Anyone know the root of this cause? What version should we resolve this to? What is the *best practice* when dealing w/ versions of dependencies (^ symbol, I assume)?

@jonhester you may know more about this than me?

**Comment by jonhester** [comment]
A quick search yields this: https://github.com/caolan/nodeunit/issues/291

**Comment by tejasmanohar** [comment]
Eek, but we're on "~0.8.1" @jonhester, not 0.7.x.

**Comment by jonhester** [comment]
I'm guessing there is a but in the latest version of Node 0.8.x.

**Comment by tejasmanohar** [comment]
@jonhester UPDATE: Delete `node_modules` folder and `npm test` and tests pass.

**Comment by tejasmanohar** [comment]
@jonhester So it's all about what version is being cached or being downloaded first w/ Travis now...

https://travis-ci.org/node-schedule/node-schedule/builds/54628772

**Comment by tejasmanohar** [comment]
@jonhester or potentially a compatibility issue in latest version of Node + nodeunit 0.8.x, yeah.

**Comment by jonhester** [comment]
@tejasmanohar The last one. yeah. Looks like the current version of Nodeunit is newer. I'd say we want to use 0.9.1 anyway which ~0.8.1 won't resolve to. That may fix it.

**Comment by tejasmanohar** [comment]
**UPDATE:** Version ranges in my latest commit saved the day.

https://travis-ci.org/node-schedule/node-schedule

I still don't quite understand how this happens when I specify directly 0.8.1 rather than ~0.8.1 since the issue was removed after nodeunit 0.8.1.

**Comment by tejasmanohar** [comment]
@jonhester Good point, that's the next test :)

**Comment by jonhester** [comment]
@tejasmanohar Since 0.8.1 obviously worked, it was just adding the tilde that broke it. So I'm guessing that there is a bug in the latest version of 0.8.x. Since the tilde will use the latest compatible version

**Comment by tejasmanohar** [comment]
@jonhester Yup, exactly. Upgraded nodeunit successfully :+1: 

Bad on my part for not wiping `node_modules` and testing, just running `npm install` since we satisfied the condition in `package.json` before and after the change. Problem resolved.

**Comment by jonhester** [comment]
@tejasmanohar Nice
