### ISSUE TITLE
Several scheduled jobs: only two will start, freezes the whole node server(2015)

### ISSUE THREAD

**Issue by dmoerman** [node-schedule/node-schedule#121]
Hi,

I'm using the "Object Literal Syntax" to schedule 3 jobs. But the jobs dont start.

schedule.scheduleJob({hour: 22, minute: 0},function() {   doJob1(); });
schedule.scheduleJob({hour: 23, minute: 0}, function() { doJob2(); });
schedule.scheduleJob({hour: 24, minute: 0}, function() { doJob3(); });

When i change it to 2 jobs, then it all works again.
I saw the closed issue, that was really similar. But it's already a while ago.
And the code changed over the years soo...

if there is a better way to this let me know 

thx

**Comment by jonhester** [comment]
I'll try to duplicate tonight. Do you mind giving me the node version and OS you are using?

**Comment by santigimeno** [comment]
@dmoerman I've been able to reproduce it. The problem is with the `hour : 24`. Change it to something in the range: `0 - 23` and should work just fine.

**Comment by santigimeno** [comment]
Probably we should throw or something if input parameters are invalid

**Comment by jonhester** [comment]
@santigimeno Good catch. On my phone and didn't even notice that. Guess that is what https://github.com/node-schedule/node-schedule/issues/108 is for.

**Comment by dmoerman** [comment]
@santigimeno  thx. It didn't cross my mind that it was with the range:``` 0-23 ```. Used 24 without thinking

**Comment by ForsakenHarmony** [comment]
Please fix this, don't blame the user for a freeze

**Comment by santigimeno** [comment]
@ForsakenHarmony the project is open source. Feel free to send a PR if you think there's something to be fixed here. I'll gladly review it.
