### ISSUE TITLE
Add Appveyor build/badge to show Windows support

### ISSUE THREAD

**Issue by MoOx** [node-schedule/node-schedule#127]
I saw in your wiki that this module works on Windows, it can be nice to automate test on this plateform too.
[Appveyor](http://appveyor.com/) is a travis like for windows. Here is an example of a config https://github.com/cssnext/cssnext/blob/master/appveyor.yml
Feel free to close if no effort has been made to ensure windows compatibility :)

**Comment by jonhester** [comment]
node-schedule doesn't depend on the file system at all which is where you can sometimes run into issues  into differences is OSs. As long as you use a supported version of node, this package will work on any OS.

**Comment by tejasmanohar** [comment]
Package should work on Windows.

@MoOx - what potential issues are you spotting w/ Windows? I'm not **against** setting up a CI for Windows testing but not sure what the benefits would be here.

**Comment by jonhester** [comment]
@tejasmanohar If we do this, we should figure out a way to cover Mac OS as well. I'm not sure it's worth it. If however, we were working with the file system, I would probably feel differently about it.

**Comment by MoOx** [comment]
Nevermind it was just an idea. I were just wondering if there is potential risk for windows (fs access or similar)
Note: OS X (Mac OS name is deprecated) is a unix OS so it should work if it works on Travis.

**Comment by jonhester** [comment]
@MoOx Correct, but travis tests on Linux. Which is not the same as, but is also based on Unix. An example of one of the differences between Linux and OS X would be case sensitivity of file names. Linux is case sensitive, while OS X is not.

**Comment by tejasmanohar** [comment]
Ah ok. I don't think there's a reason to pursue this at the time given the dependencies of node-schedule and its procedures.
