### ISSUE TITLE
git flow

### ISSUE THREAD

**Issue by tejasmanohar** [node-schedule/node-schedule#129]
https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow
https://www.atlassian.com/git/tutorials/comparing-workflows/forking-workflow/

Add references to documentation referring to git workflows we use for contributing. Use `develop` base branch and setup the es6 and validation off of these.

**Comment by jonhester** [comment]
@tejasmanohar Branched from master. I'll update develop to es6 style once we've merged @ricardofbarros getJob code in. I'll need to cover the ES6 in the docs as well before this ES6 goes in. Don't want to make it hard to contribute. Lastly, validate functionality is going to require the jobs to be refactored before it will be ready to be merged in. But I already have some ideas on that.

I'll work on the contributing docs some tonight. I'll also reference semantic versioning.

**Comment by tejasmanohar** [comment]
Got it. Merged @ricardofbarros' work into develop.

**Comment by jonhester** [comment]
@tejasmanohar How's [this](https://github.com/node-schedule/node-schedule/wiki/Contributing) look? Tried to break it down so no one will need to read the gitflow info. Also, removed information that is specific to collaborators since anybody given commit access should know the process, and it may confuse others if left in.

**Comment by jonhester** [comment]
In addition, I think it may be better for mine, yours, and @santigimeno  continued work to be in forks so we only have master, develop, and potentially a release branch in the node-schedule. Otherwise we could end up with a lot of branches in the main repo.

**Comment by jonhester** [comment]
@tejasmanohar I'm going to close this. Feel free to reopen if you have any issues with it.

**Comment by tejasmanohar** [comment]
LGTM
