### ISSUE TITLE
Recurring job only executes once

### ISSUE THREAD

**Issue by rbhalla** [node-schedule/node-schedule#138]
This seems like a trivial issue but I'm out of troubleshooting steps. My code is simple:

```
var job = schedule.scheduleJob({minute: 1}, function() {
  console.log('Testing');
});
```

I think my issue is that I am running this script when launching my express app (just using a require statement). Although the express app is clearly still up, afterwards, the job only seems to run once.

Can anyone spot anything glaringly obvious with what I've done?

**Comment by santigimeno** [comment]
@rbhalla Do you have a reduced test that reproduces the issue? I can't seem to reproduce it. This simple test passes for me:

```
var schedule = require('schedule');
var sinon = require('sinon');
var assert = require('assert');

var clock = sinon.useFakeTimers();

var i = 0;

var job = schedule.scheduleJob({minute: 1}, function() {
   process.nextTick(function() {
       clock.tick(3600 * 1000);
       ++ i;
   }); 
});

clock.tick(3600 * 1000);

setTimeout(function() {
   assert.equal(i, 3); 
   job.cancel();
}, (3 * 3600 * 1000) + 1000);
```

**Comment by rbhalla** [comment]
Hi @santigimeno 

You are right, that does seem to work. Actually even running the simple less elegant:

```
var schedule = require('node-schedule');

var job = schedule.scheduleJob({second: 1}, function() {
   process.nextTick(function() {
       console.log('minute');
   });
});
```

seems to work when using the node cli directly. My problem seems to be when trying to use a process manager like pm2. When I run `pm2 start test.js` with pm2, the script doesn't log anything.

I could potentially just go back to cron, but it would be nice to know why this particular use case doesn't work.

**Comment by santigimeno** [comment]
@rbhalla Tested your example with `pm2` and seems to work for me. Just had to look the log file associated with the process. You can check the file by executing `pm2 show job_id` and look for `out log path`

**Comment by rbhalla** [comment]
That's interesting. So you used `pm2 start <script name>` and saw statements in your pm2 log? Because I did exactly that and saw no log statements appearing.

Did you manually tail the log file or did you use `pm2 logs`?

**Comment by santigimeno** [comment]
Yes, that's correct. I used tail on the log file

**Comment by tejasmanohar** [comment]
Due to inactivity on this issue, I'm going to close it. I, as well, cannot replicate this, and I tailed the log file.
