### ISSUE TITLE
Regression caused by CancelJob refactoring

### ISSUE THREAD

**Issue by santigimeno** [node-schedule/node-schedule#139]
Before commit https://github.com/node-schedule/node-schedule/commit/a12fdfa5ceb276159676162f1317f44ff7d39f1a you could run through the scheduled jobs using `Object.keys`:
```
Object.keys(schedule.scheduledJobs).forEach(function(job_name) {
    console.log(job_name); // Only scheduled jobs are printed
});
```
After the commit the sample code will print all jobs (scheduled or canceled)

I would argue that this change shouldn't have gone into a patch version but into a major version.

/cc @rodrigoalviani @tejasmanohar @jonhester

**Comment by tejasmanohar** [comment]
Yeah, my bad for merging that into a patch. It does indeed change usage and is a breaking change... should've been in a major release.

Not sure what's the best way to go back on that now- probably none. Instead, let's call for a major release soon/now? I was planning to wait on #125 for 1.0, but we can probably call for a 0.3 now- thoughts?

**Comment by jonhester** [comment]
Going to put some work into #125 tonight.

**Comment by tejasmanohar** [comment]
This has been resolved- we're not changing it in this release cycle, we'll just note of it in version history of 1.0
