### ISSUE TITLE
Scheduling a job in the past returns a job and triggers the job execution in the nextTick

### ISSUE THREAD

**Issue by santigimeno** [node-schedule/node-schedule#141]
Sample code:
```
var schedule = require('schedule');

var date = new Date(Date.now() - 3600000);
console.log(date);
var job = schedule.scheduleJob('My Job', date, function() {
    console.log('myjob!!');
});

console.log(job);
```
I don't know the best strategy here:
- Just return null (It won't be a breaking change)
- Return null and emit an specific event: we could add a new `error` event with the description of the error. Of course this would be a breaking changes.

Thoughts? @tejasmanohar @jonhester

**Comment by tejasmanohar** [comment]
Thanks for looking into some of the off-cases. This one is rather small... I'd suggest a custom Error in the next major release and just merge `return null` (or nothing) now.

**Comment by santigimeno** [comment]
https://github.com/node-schedule/node-schedule/pull/142 should do it for master
