### ISSUE TITLE
The date-based scheduling is not working

### ISSUE THREAD

**Issue by young-py** [node-schedule/node-schedule#144]
```javascript
var cron = require('node-schedule');
var date = new Date(2015, 05, 15, 16, 45, 30);
cron.scheduleJob(date, function(){
    console.log(new Date(), "The world is going to end today.");    
});
```

**Comment by santigimeno** [comment]
@young-py I think nothing is wrong with that code. Probably the issue is that you're expecting that the 2nd argument in the Date constructor refers to the month of May, but it really corresponds to June as the month counting starts in 0.

**Comment by young-py** [comment]
I got it, thank you!
By the way, the callback function cannot take parameters, I had a simple change the code!
