### ISSUE TITLE
Can you tell me how to get all the jobs in the schedule?

### ISSUE THREAD

**Issue by Messilimeng** [node-schedule/node-schedule#148]

**Comment by santigimeno** [comment]
```
var schedule = require('schedule');
var all_jobs = schedule.scheduledJobs;
```

**Comment by tejasmanohar** [comment]
@santigimeno there :+1:. she is creating jobs from a loop, and thus 

`first.cancel();` method wouldn't work, and she'd have to go based on the Schedule object as I mentioned :+1:
