### ISSUE TITLE
Can I write rule like this

### ISSUE THREAD

**Issue by Messilimeng** [node-schedule/node-schedule#150]
rule.month = [5,6]; 
               rule.date = [2,3,4];
		rule.hour = 5;
		rule.minute = 4;
		rule.second = 6;

**Comment by Messilimeng** [comment]
can you tell me  if i can write the rule like that ?

**Comment by tejasmanohar** [comment]
No, but you can use schedule it using JavaScript `Date` objects which achieve the same thing.

https://github.com/node-schedule/node-schedule/wiki/Date-based-Scheduling

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date
```
new Date(year, month[, day[, hour[, minutes[, seconds[, milliseconds]]]]]);
```

**Comment by tejasmanohar** [comment]
Please check the issue before commenting next time :smile:

**Comment by tejasmanohar** [comment]
we also have a chat for help now https://gitter.im/tejasmanohar/node-schedule
