### ISSUE TITLE
change that does not allow scheduling jobs in the past

### ISSUE THREAD

**Issue by davisford** [node-schedule/node-schedule#151]
Hi, [this commit](https://github.com/node-schedule/node-schedule/commit/c2afc663b1b75a32a62b4d61c45990ffa335ed68) broke some tests for me when upgrading `0.2.6` to `0.2.7`.

Specifically, in certain tests, I was setting the schedule spec to a date in the past to force the code that uses schedule to run immediately.  The net result of this change is that `require('node-schedule').scheduleJob(dateInPast, function () {})` returns `null`, which is kind of a bummer.

The only alternative I see now is to try to make the spec some number of millis in the future, to force it to run, but this would be somewhat brittle.

Is there another way to schedule a job immediately with a `Date` object?

**Comment by santigimeno** [comment]
@davisford I understand your point. This change could have gone to a major version but I thought it was a bug.
One question (maybe silly): why would you need using `node-schedule` to execute a job immediately?

**Comment by santigimeno** [comment]
@davisford Anyway, we have broken the API. Sorry about that.

I think this change should be reverted and a new version should be published. @tejasmanohar @jonhester?

**Comment by davisford** [comment]
thanks @santigimeno for the reply -- to answer your question, i use it in production to schedule it for the future, but i also have a whole suite of unit tests also.  scheduling unit tests to run in the future isn't the best way to go, which is why it was nice to be able to schedule it for yesterday and have the code run immediately in the test case.  of course, i could mock out `node-schedule`, but if i did that, i never would have discovered this problem until after i deployed the change.

**Comment by tejasmanohar** [comment]
Looks like an issue, but frankly I don't have much time to look into it or test for the next 1.5 weeks due to some hectic-ness preparing for launch v1 (sorry). I've given you access to NPM @santigimeno @jonhester :smile:

**Comment by jonhester** [comment]
Not at my computer now, but I'll take a look tonight.

**Comment by tejasmanohar** [comment]
np, so you can `npm publish` now if you're logged in with the account "jonhester"

**Comment by jonhester** [comment]
@davisford We just published a new version that reverts the offending commit. Can you confirm for us that this fixes your issue?

**Comment by santigimeno** [comment]
@davisford Thanks for the reply. Just a couple more things, as I'm trying to understand the whole issue and see if this functionality can be removed in a future major version.

- FWIU in your tests, you're taking advantage of the fact that scheduling an issue in the past triggers the job execution immediately. Is this correct? If so, and taking into account your application only schedule jobs in the future, I don't see the use of it as the code path of the tests and the production code would be different. Maybe I'm missing something  though.
- If somebody is using this functionality to execute a job immediately, I think not using `node-schedule` and just executing the job would do it.
- Do you foresee any major breakage in your code (apart from the tests) in case this functionality would be removed?

Thanks for your time

**Comment by davisford** [comment]
Thanks @jonhester will check soon

**Comment by davisford** [comment]
@santigimeno it would be helpful to add something in the api that tells node-schedule to trigger a job immediately...this would solve my problem.

I am indeed taking advantage of the fact that jobs scheduled in the past execute immediately so that I don't have to try to schedule small millisecond job start times in a test to get tests to run efficiently...that would be brittle.

However, I really don't need support for job times in the past, I just need a way to trigger a job immediately.

I mock this function (this is my own function exported by one of my own modules) in my tests, to return a time in the past:

```javascript
/**
 * Given a subscription, resolve what the next scheduled date/time should be to
 * deliver the report based on daylight savings, fiscal start of day, and
 * location timezone offset.
 *
 * @param  {Object} sub subscription object
 * @return {Date}       represents when to deliver the next report
 */
function getJobSchedule(sub) {
  var now = new Date();
  var tokens = sub.location.fiscal_hour_of_day.split(':'),
    hour = parseInt(tokens[0], 10),
    min  = parseInt(tokens[1], 10),
    sec  = parseInt(tokens[2], 10),
    offset = (now.dst() ? sub.location.tz_utc_dst_offset : sub.location.tz_utc_offset);

  // example 2014-12-01T10:34:00-05:00
  // create an iso8601 string with tz offset and parse it;         js month is zero based
  var iso = now.getFullYear() + '-' + prefix(Number(now.getMonth() + 1)) + '-' + prefix(now.getDate())
    + 'T' + prefix(hour) + ':' + prefix(min) + ':' + prefix(sec) + (offset < 0 ? '-' : '+') + prefix(Math.abs(offset)) + ':00';

  log('next job scheduled for ISO 8601 string: %s', iso);
  var date = new Date(Date.parse(iso));

  // if it has already passed...
  if (date.getTime() <= now.getTime()) {
    // schedule it to run tomorrow
    date.setDate(date.getDate() + 1);
  }

  return date;
}
```

It is used like this:

```javascript
var next = getJobSchedule(sub),
  job = schedule.scheduleJob('Subscription ' + sub._id, next, function ( ) {
    /* etc */
  });
```

What was happening after the PR merge here is job ended up being null when the time was in the past cause null reference errors later in the code.

Example test:

```javascript
var yesterday = (function () {this.setDate(this.getDate()-1); return this;}).call(new Date());

it('should schedule jobs immediately if the schedule is in the past, and when they run it should trigger deliver:subscription pdf request', function (done) {
      // have getJobSchedule return a date in the past so the jobs run immediately
      sinon.stub(scheduler, 'getJobSchedule').returns(yesterday);

      var callbacks = 0;
      function jobCallback(id) {
        expect(id).to.exist;
        callbacks++;
        if (callbacks === 2) {
          expect(createStub.calledTwice).to.be.true;
          expect(Object.keys(queue).length).to.equal(0);
          done();
        }
      }

      scheduler.scheduleJobs(function (err, q) {
        queue = q;
        expect(err).to.not.exist;
        expect(queue).to.exist;
        expect(Object.keys(queue).length).to.equal(2);
      }, jobCallback);
    });
```

I have a quite a few tests here centered around corner cases, esp. with DST.  My favorite trio of DST + JavaScript + UTC/LocalTime is always a pleasure to deal with, so having the capability to manipulate this for testing these corner cases is highly useful.

Granted I'm sure I could rewrite these tests and mock at a different level or workaround this in another way, but this minor semver update caught me by surprise.  If you feel the need to strip out this capability, that would be fine, I'll just have to spend the time to re-work this -- such is life.

My $.02, tho..I don't think it hurts anything immediately scheduling jobs whose timestamp is in the past.  I think that would be preferable than returning a null job object.

Hope that helps, and thanks for maintaining this!

**Comment by davisford** [comment]
@jonhester we're good -- thanks so much for all the assistance.  i'll close this one out.

**Comment by santigimeno** [comment]
@davisford Thanks for the thorough explanation.
I think I understand your points but still not fully convinced :(. I think that if `node-schedule` is used only to execute jobs in the future, the tests should test that behavior. I understand that for testing, we want the job to be executed immediately, but that can be accomplished for example by *mocking* the `Date` using `sinon` `fakeTimers` functionality as we do in our tests. Does make sense to you?
Anyway, I'm opening an issue to discuss whether to maintain or drop this feature in the next major release

**Comment by davisford** [comment]
@santigimeno sinon `fakeTimers` is a valid solution.  i've used it before.  like i said, i can work around it, it's just legacy code now that has to be dealt with when there aren't minutes in the day :)  sinon.fakeTimers would be helpful to rewind the clock to have more time to fix things.
