### ISSUE TITLE
Switch from node-time to timezone module for Windows support

### ISSUE THREAD

**Issue by tejasmanohar** [node-schedule/node-schedule#155]
Thoughts, @santigimeno @jonhester ?

https://github.com/bigeasy/timezone offers a pure JavaScript version while timezone relies on `time.h`.

**Comment by santigimeno** [comment]
I've been looking into this a little bit. I think it's feasible but I don't know when I'll have time to implement it.
For the moment I propose we should revert the node-time implementation as I think, not supporting Windows is a no-go

**Comment by tejasmanohar** [comment]
Fair enough. For something that can be done in pure JS, it's probably best to support all OS's. @santigimeno if you send in a PR reverting the node-time integration, I'll merge it and make a release.

**Comment by santigimeno** [comment]
@tejasmanohar Will do that tomorrow.

**Comment by santigimeno** [comment]
@tejasmanohar  https://github.com/tejasmanohar/node-schedule/pull/159

**Comment by tejasmanohar** [comment]
#217
