### ISSUE TITLE
Scheduling jobs in the past

### ISSUE THREAD

**Issue by santigimeno** [node-schedule/node-schedule#157]
Before releasing `1.0.0` I would like to discuss if we should change the behavior when scheduling jobs in the past. The current behavior is that the job gets executed immediately.

My position is that we should not allow scheduling a job in the past, and that if somebody wants to execute something immediately, should just *execute* the task right away, without using `node-schedule`.

@davisford raised some valid points for keeping the functionality as it is. See: https://github.com/tejasmanohar/node-schedule/issues/151 for the discussion

cc/ @tejasmanohar @jonhester

**Comment by tejasmanohar** [comment]
Yeah, that could be stopped in the schedule validation that's a `// TODO` right now.

**Comment by tejasmanohar** [comment]
Hm, I'm thinking of adding this back and releasing a major version change (semver). Thoughts, @santigimeno? I don't see a valid reason for node-schedule to run something immediately, even for tests.

**Comment by santigimeno** [comment]
@tejasmanohar I tend to agree with you. I just hope it doesn't break many applications, but probably the only way to know is having a new release out and wait for bug reports.

BTW what are your plans for this major release. I think you should open an issue to discuss what should be in form the dev branch.

**Comment by santigimeno** [comment]
Version 1.0.0 disallows for scheduling jobs in the past
