### ISSUE TITLE
Async?

### ISSUE THREAD

**Issue by achurak** [node-schedule/node-schedule#164]
Hello,

I'm trying to schedule a job from a web application, but it looks like this module doesn't release the process (works synchronously), so whenever I'm trying to schedule something I'm not getting a reply from the server, the process stuck on the scheduling function. Isn't it supposed to be async? Am I doing something wrong? Here's the code:
```javascript
var rule = new schedule.RecurrenceRule();
if (params.schedule.recurrence === 'weekly') rule.dayOfWeek = params.schedule.dow;
rule.hour = params.schedule.hour;
rule.minute = params.schedule.minute;
var j = schedule.scheduleJob(rule, function(name) {
    SomeClass.runSomeFunction(name);
}.bind(null, name));
```

**Comment by tejasmanohar** [comment]
> the process stuck on the scheduling function

By this, do you mean that you're never able to run the next function.... never getting the callback / response that the job is scheduled. If that's the case, the answer is no, node-schedule's jobs do not occupy a whole thread; you're scheduling something for later- you don't have to keep that as the only process running in the app.

**Comment by achurak** [comment]
@tejasmanohar Yes, correct. So is there something wrong with my code? Why is is happening?

**Comment by aktary** [comment]
@achurack: I ran in to the same problem and resolved it by putting my require statements (including require('async')) in the function declaration of the job being scheduled.  

@tejasmanohar , you may want to update the examples to indicate this for any async functions... or really, any jobs that require use of outside modules.

**Comment by ekrtf** [comment]
@achurak can you detail a little more? Thanks for the help!

**Comment by tejasmanohar** [comment]
@aktary Example? PR?

> I ran in to the same problem and resolved it by putting my require statements (including require('async')) in the function declaration of the job being scheduled.
Can you show me a runnable example so I can replicate this locally? Plus, I don't think @achurak mentions anything about the async module- don't mix up "asynchronous" and caolon's async.

**Comment by nmaggioni** [comment]
Same issue here. Just a logging statement in the callback, but the process just hangs and does neither call the callback nor continue execution.

**Comment by santigimeno** [comment]
@nmaggioni sample code?

**Comment by nmaggioni** [comment]
@santigimeno here it is: http://git.io/vBWF0

**Comment by santigimeno** [comment]
Can you reduce it to something simpler I can run myself?

**Comment by nmaggioni** [comment]
Nevermind, my bad: the date passed to the scheduler was not a proper Date, but a Moment.js object. Sorry for the nuisance :sweat_smile:

**Comment by santigimeno** [comment]
np :)
