### ISSUE TITLE
readme points to wiki, and wiki points to readme

### ISSUE THREAD

**Issue by gka** [node-schedule/node-schedule#175]
readme says

    Check out our wonderful wiki for usage instructions.

and wonderful wiki says

    ...we recommend starting with our README.
    
No simple usage information in either of them.

**Comment by santigimeno** [comment]
You're right. PR's to improve the documentation are always welcome :)

**Comment by tejasmanohar** [comment]
I'm going to move the information over to the README, I think the wiki just creates confusion... we do need more examples though, I agree. If you've used node-schedule in your project, sample projects are also welcomed.

I'm going to leave this open until it's fixed and assign this to me. But yes, as @santigimeno mentioned, we would really appreciate any documentation PRs :smile:

**Comment by tejasmanohar** [comment]
everything's in the readme now
