### ISSUE TITLE
Create a job that starts at a particular date and then recurs?

### ISSUE THREAD

**Issue by blah238** [node-schedule/node-schedule#176]
This wasn't clear from the wiki, but how would I go about creating a job that starts on a particular date, say Sep. 1 at 5AM, and then recurs every weekday at the same time?

**Comment by santigimeno** [comment]
@blah238 I'm not sure it can be done with a single job. You could always schedule one job to be triggered on the start date, and then schedule the recursive job.
Anyway, I think having the possibility to pass a start_date when scheduling a job would be a nice addition.
Thanks

**Comment by blah238** [comment]
@santigimeno Thanks for the reply. Do you mean that the recurring job should be created in the callback of the first job?

And yes I think having both support for a start date and end date would be ideal.

So you could for example schedule a job to run at Sep. 1 at 5AM, recurs every weekday at the same time, and then never runs again after say, Nov. 15 at 12AM (or whatever).

I suppose this could be done now by checking in the callback of the recurring job whether the end date is less than the current date, and if so, cancel the recurring job.

Does that make sense?

**Comment by santigimeno** [comment]
@blah238 Yes something like that. You could create a 3rd job for the end date, and then cancel the recurring job

**Comment by blah238** [comment]
@santigimeno I came across a couple of interesting libraries that are designed to handle this use case:

  - https://github.com/jkbrzt/rrule: "JavaScript library for working with recurrence rules for calendar dates."
  - https://github.com/coolaj86/node-reschedule: "A job / event scheduler for both one-time and recurring (RRULE-based) events"

May be useful to use `rrule.js` in future versions to simplify schedule parsing, as it is based on the [RFC 5545](https://tools.ietf.org/html/rfc5545) (iCalendar) standard and looks to be well tested.

node-reschedule does not appear to be well tested or actively maintained, but nonetheless makes for an interesting case study, particularly [this fork](https://github.com/L8D/node-reschedule).

**Comment by tejasmanohar** [comment]
#227
