### ISSUE TITLE
What's this `execute` method?

### ISSUE THREAD

**Issue by santigimeno** [node-schedule/node-schedule#183]
See: https://github.com/tejasmanohar/node-schedule/blob/master/lib/schedule.js#L131
Maybe it's obvious but, does anyone know where this came from
@tejasmanohar

**Comment by tejasmanohar** [comment]
I actually have no clue.

**Comment by tejasmanohar** [comment]
It looks like code from @mattpat's original implementation.... like mocking a function that never came to existence. And, also not sure what the true intent here was.

**Comment by hdpinto** [comment]
If it helps, that threw an error when I passed the scheduleJob method it a function that didn't exist today.

**Comment by tejasmanohar** [comment]
Yes, `execute()` is very much undefined.

**Comment by jonhester** [comment]
It was added in this commit: https://github.com/tejasmanohar/node-schedule/commit/e7c475f0f1cf00753420a17b61aa1046acb4473b,

**Comment by jonhester** [comment]
@tejasmanohar, @santigimeno So the way I see it is if `this.job` is a function then call it. Otherwise, assume that it is an object with an execute property that is a function.

**Comment by santigimeno** [comment]
@jonhester Yeah, that's what I thought too. What bothers me is: no documentation (not now, not ever), no tests, is it really useful?
I think it complicates the API and doesn't provide anything you can't do by using simply a `function`. Definitely I would remove it in the next major version. What do you think?

**Comment by jonhester** [comment]
@santigimeno Agreed, it could be being used by someone so we definitely will have to wait to the next major version to follow semver.
