### ISSUE TITLE
Doesnt work for windows (in some cases)

### ISSUE THREAD

**Issue by pursual** [node-schedule/node-schedule#189]
Under Azure (windows), cron style jobs using "hour" do not fire. Using minute and second seem fine.

**Comment by tejasmanohar** [comment]
@pursual unfortunately, i don't yet have a windows system to test this out, but i'll try to get it sometime. can you provide a runnable/testable example and describe more details surrounding your error? you can try to use sinon's fake timers to test if this is really the case or something else is interfering like @santigimeno does here- https://github.com/tejasmanohar/node-schedule/issues/191#issuecomment-150348284

**Comment by chentsulin** [comment]
Maybe worth to try http://www.appveyor.com/. I haven't use it before. but it seems free for OSS projects.

**Comment by tejasmanohar** [comment]
i agree, i'll take a peek at that. this issue has been untouched so i'm going to close it. we really need an example or test case that we can run & replicate. it works on my windows machine. you can use sinon fake timers to test this.
