### ISSUE TITLE
run recurrent job all the year with given dayofweek

### ISSUE THREAD

**Issue by venu-koluguri** [node-schedule/node-schedule#191]
why the recurrence job stopping after a week
if i print the rule it shows like
{ hour: 16,
minute: 54,
dayOfWeek: { start: 2, end: 6, step: 1 } }
am i missing anything
i want to run this job all the year with given dayofweek

**Comment by santigimeno** [comment]
@venu-koluguri This code is working for me (ignore `sinon` use as it's only for testing):
```
var schedule = require('./');
var sinon = require('sinon');
var clock = sinon.useFakeTimers();

schedule.scheduleJob({
    hour: 16,
    minute: 54,
    dayOfWeek: new schedule.Range(2, 6, 1)
}, function() {
    console.log(new Date());
});

clock.tick(100000000000000);
```

**Comment by santigimeno** [comment]
Closing this. @venu-koluguri feel free to re-open if it's still an issue for you
