### ISSUE TITLE
Switch out NodeUnit for Mocha

### ISSUE THREAD

**Issue by tejasmanohar** [node-schedule/node-schedule#195]

**Comment by santigimeno** [comment]
Why? I personally use `mocha` for most of my projects, so it would be no problem, but want to understand the reason for such change

**Comment by tejasmanohar** [comment]
when we use es6, mocha has a --compilers option as well as -r for babel polyfill, but i think we can use es6 in our tests and transpile and run or use babel-node in dev so this shouldn't be a problem even with nodeunit. will look more
