### ISSUE TITLE
Weird functionality when reusing RecurrenceRule object

### ISSUE THREAD

**Issue by mrmayfield** [node-schedule/node-schedule#216]
If I write some code such as:
```

var rule = new schedule.RecurrenceRule();
rule.minute = 10;

var j = schedule.scheduleJob(rule, function(){
    console.log('The answer to life, the universe, and everything 10!');
});

rule.minute = 11;

var k = schedule.scheduleJob(rule, function(){
    console.log('The answer to life, the universe, and everything 11!');
});
```

On the 10th minute, as expected
 `The answer to life, the universe, and everything 10` 

is outputted to the console, however on the 11th minute, this is outputted:

however on the 11th minute, this is outputted:
 ```
The answer to life, the universe, and everything 10
The answer to life, the universe, and everything 11
``` 

Definitely caught me off guard and after speaking with Tejas is sounds like this is definitely a bug.

**Comment by aradnom** [comment]
This might be another flavor of https://github.com/node-schedule/node-schedule/issues/208 and https://github.com/node-schedule/node-schedule/issues/214, which I'm also seeing.

**Comment by tejasmanohar** [comment]
It is odd functionality, but it covers an abnormal use case (mutating a rule) which I see no application for. I'm +-0 (will merge if acceptable and well-tested but don't think it's worth anything myself) for any PRs where someone finds an effective way to resolve this.

Somewhat related- https://github.com/node-schedule/node-schedule/pull/215. @ytkang has a _sorta_ valid concern of system time changing.

**Comment by tejasmanohar** [comment]
I don't think this is a valid concern since it narrows down to how setTimeout works and what you're mutating. Still.. if you do think of a solution, down for PRs. System time changing on the other hand is definitely.
