### ISSUE TITLE
job schedule in seconds

### ISSUE THREAD

**Issue by neocite** [node-schedule/node-schedule#22]
Hi!
What is configuration for schedule jobs run at 20 seconds? My schedule config is...
var rule_quotations = new schedule.RecurrenceRule();
rule_quotations.second = 20;
var j = schedule.scheduleJob(rule_quotations, function(){
   console.log('ok');
});
but my jobs it's executend ever 40 seconds. can i help me?

**Comment by mbukosky** [comment]
+1
