### ISSUE TITLE
Run the schedule too many times!

### ISSUE THREAD

**Issue by Manjiz** [node-schedule/node-schedule#221]
Code like `* */24 * * *`.  I run the script `node server` and then let the computer sleep. After many hours(less than 24), I power up the computer and found the schedule had run several times.

**Comment by tejasmanohar** [comment]
> and then let the computer sleep
^ That's the problem. There are many cases to consider like what happens if a job was missed because computer had suspended at the time. See #96. Post suggestions there. Closing as duplicate.
