### ISSUE TITLE
Is it possible to log the scheduled time in human string format?

### ISSUE THREAD

**Issue by diegoaguilar** [node-schedule/node-schedule#224]
Is there any way to log the job's schedule time in a format such as:

* _Every 5 minutes_
* _Every monday at 10 AM_
* _Everyday at 10:30 PM_

**Comment by albertdatui** [comment]
Hi,

I don't think the library support such format. However, you can use [Object Literal Syntax] (https://github.com/node-schedule/node-schedule#object-literal-syntax), it is the closest format that I could find.

Cheers

**Comment by tejasmanohar** [comment]
not atm, and I don't think that belongs in this module. You could use [this module](https://github.com/matthewmueller/date) to generate `Date` objects from a human-readable string. As per recurrence rules, not that I know of, but that sounds like a great separate module imo.

**Comment by tejasmanohar** [comment]
Thoughts, @santigimeno? ^
