### ISSUE TITLE
Cancelled Job still  triggers

### ISSUE THREAD

**Issue by andela-omesanni** [node-schedule/node-schedule#226]
I am working on an app that uses twilio to connect calls between two people. I use node-schedule to schedule these calls. When the time for the call has reached, node-schedule, triggers the twilio call to both parties.

Now, if one party reschedules a call, I cancel the previous job and then schedule a new one but everytime i do this, the former job still triggers the function that initiates the twilio call. After cancelling a job, i log the current scheduled jobs and i  see something like 'jobname': null, but for some reason I the twilio call still triggers. When i pick up the twilio call i do get an application error but i just don't know why the twilio call still triggers. I am starting to think the timer for the cancelled job is still active even after i have cancelled the job hence making the twilio call still trigger. 

Please I need major help.

**Comment by albertdatui** [comment]
Do you mind to show us the related snippet code?
It will help us to find the error.

**Comment by andela-omesanni** [comment]
```
function scheduleCallsCallback(scheduledCall) {
  var callDetails = scheduledCall.val();

  rootRef.child('users').child(callDetails.expertId).once('value', function(snap) {
    var user = snap.val(); 
    var date = new Date(callDetails.callDate);

    rootRef.child('scheduling_mode').once('value', function(snap) { 
      schedule.scheduleJob(callDetails.callRequestId, date, function() {
        requester.startCallProcess({
          callRequestId: callDetails.callRequestId,
          requesterPhoneNumber: callDetails.requesterPhoneNumber,
          expertPhoneNumber: callDetails.expertPhoneNumber
        });
      });
    });
  });
}
```
so from above in schedule.scheduleJob function, inside the callback function, I have another function that starts the twilio call process. Now even after, I have cancelled a job, the requester.startCallProcess function still gets called.

I looked at your code and I noticed when you initializae a job, the runOnDate function has this process.nextTick(job). I am thinking this might be causing the problem because even if you have clear the timer and cancelled the job, u cannot actually cancel process.nextTick() and so the callback function inside the job still triggers.

**Comment by albertdatui** [comment]
for the function in runOnDate, the process.nextTick() will be executed if you schedule the job in the past and it will return null. otherwise, it is going to return a timer. (CMIWW)

#192 might be a good issue to look at. Reschedule function will be implemented in the next release.

**Comment by andela-omesanni** [comment]
so for now there's no solution to this? The job actually cancels because anytime I check pendingInvocations, i can see the job is no longer there but for some unknown reason the twilio call still happens

**Comment by andela-omesanni** [comment]
are you available on screenhero so we could pair?

**Comment by santigimeno** [comment]
@andela-omesanni,  can you post a simple test that reproduces the issue without using any external modules / functions so I can try to figure out what's going on?

**Comment by andela-omesanni** [comment]
I wrote a test and the test passed so I had to take a look at my code again to see what i am doing wrong. I have fixed my code now and everything seems to be working right now.

Thanks for your replies.

**Comment by santigimeno** [comment]
Glad you could find the problem. Closing for the moment

**Comment by benishak** [comment]
I still have this issue

```
    var job = schedule.scheduledJobs[push.id];
    var data = {};
    data.data = {};
    data.data.alert = push.get("message");
    data.data.type = push.get("type");
    
    if(job){
        console.log("JOB !!!" + JSON.stringify(job));
        job.cancel();
        console.info(schedule.scheduledJobs[push.id]);
    }

    schedule.scheduleJob(push.id, push.get("date"), function(){
           // do something
    });
    
```
