### ISSUE TITLE
Persistance if server reboots?

### ISSUE THREAD

**Issue by etiennea** [node-schedule/node-schedule#228]
Just wondering if this works if the process restarts, I need this feature.

**Comment by tejasmanohar** [comment]
From my understanding, what you're saying is an application concern.

https://github.com/node-schedule/node-schedule#overview
>If you need to schedule jobs that will persist even when your script isn't running, consider using actual cron.

Jobs on the schedule will be executed at the specified time if the process is running at the specified time. Node Schedule is lean and comes with no built-in persistence method (however, this doesn't mean that you can't implement one yourself around it). Schedule your jobs at your script start time. If the process restarts and the job was supposed to be schedule during sometime when the process was done, the job won't run automatically by Node Schedule (and shouldn't). Your process will have to handle that.
