### ISSUE TITLE
The schedule job doesn't execute In a leap year February 

### ISSUE THREAD

**Issue by ZhaoZhijie** [node-schedule/node-schedule#229]
the schedule seems won't execute if you set the date of your system to leap year February likes 2016/2/1 18:31
Here is my code:
var schedule = require('node-schedule');
var j = schedule.scheduleJob('32 * * * *', function(){
  console.log('The answer to life, the universe, and everything!');
});
the program exit  immediately after it starts.

**Comment by lucianlush** [comment]
I have some error. but If you code like this, It's working.
   var rule = new schedule.RecurrenceRule();
    var times = [];
    for(var i=1; i<60; i++){
        times.push(i);
    }
    rule.minute = times;
    var j = schedule.scheduleJob(rule, function(){
console.log('The answer to life, the universe, and everything!');
});

**Comment by tejasmanohar** [comment]
dupe #225
