### ISSUE TITLE
Just a quick question....

### ISSUE THREAD

**Issue by Yelnik** [node-schedule/node-schedule#232]
Sorry to create an issue for this but I just wanted to clarify something on the main github page.

In the examples, there is a job that runs Thursday through Sunday, so 4 days, but the syntax is:

rule.dayOfWeek = [0, new schedule.Range(4, 6)];

I'm just a bit confused on 4 through 6 ends up covering 4 days instead of 3.

Does the 0 also end up including Sunday in the job as well?

**Comment by albertdatui** [comment]
Hi Yelnik,

Yes, basically the rule.dayOfWeek = [0, 4, 5, 6] which result in sunday, thurs, fri and sat.
thanks
