### ISSUE TITLE
RecurrenceRule hour firing a lot.

### ISSUE THREAD

**Issue by J4ck4l0pe** [node-schedule/node-schedule#234]
when I use this: 
`var rule = new schedule.RecurrenceRule();`
`rule.hour = 1;`
`var j = schedule.scheduleJob(rule, function () {`
`//Do something`
`}`

the scheduleJob fired 125 times, while i just wanted it to fire once. adding a `rule.minute = 0` seems to have solved the problem for now.

Can this be added in the documentation or is there a permanent fix?

**Comment by J4ck4l0pe** [comment]
It is in the documentation, just not really clear. sorry

**Comment by santigimeno** [comment]
It is the expected behavior.
I understand the docs are lacky. PR are always welcomed :)
