### ISSUE TITLE
Handling node-schedule in cluster mode

### ISSUE THREAD

**Issue by DenisLaboureyras** [node-schedule/node-schedule#242]
Hello,

I'm using your great framework for a few months in a classic node application.
But I'm currently working to use node in cluster mode and I tried to include my node-schedule code in it with no success.

If I insert my schedule in the code, the task is fired when the app is launched, and never after that...
I think I will create a second node process with my scheduled tasks, but I was wondering if I could manage to deal with the scheduler in 1 script.

You can find an example code below:

`
var cluster        = require('cluster')
  , schedule       = require('node-schedule');

if (cluster.isMaster) {

  schedule.scheduleJob('10 1 * * *', function(){
    console.log("task scheduled")
  })

}`

**Comment by DenisLaboureyras** [comment]
Hello again,

I finally managed to make it work using RecurrenceRule instead of cron style.
Don't know really why, but the good news is that I can use my node app in cluster mode.

Regards

**Comment by BrijJhala** [comment]
Hi @DenisLaboureyras , could you please share me how did you manage to run in cluster mode ?
Thanks. 
Best Regards,
Brij

**Comment by DenisLaboureyras** [comment]
I don't use it anymore but it works the same way as the classic version, you just have to filter your execution on only one worker (cluster.worker.id)
