### ISSUE TITLE
node-schedule does not run with pm2

### ISSUE THREAD

**Issue by wpsmithtwc** [node-schedule/node-schedule#244]
For whatever reason, node-schedule does not appear to run with pm2. I would rather re-open #138 as I have the same issue.

**Comment by santigimeno** [comment]
Hi! Can you post a reduced test case we can work on? It should also explain how pm2 is used so we can reproduce it. Thanks

**Comment by wpsmithtwc** [comment]
Actually, in a very simplified example, scheduler works. So, there has to be another issue at hand. Sorry.

**Comment by santigimeno** [comment]
Nevermind. Feel free to open if you think there's something wrong with the module. Thanks
