### ISSUE TITLE
Scheduling don't work in February 2016

### ISSUE THREAD

**Issue by vimmerru** [node-schedule/node-schedule#245]
**Steps to reproduce:**

Execute the following script in February 2016

const schedule = require('node-schedule');

schedule.scheduleJob("*/2 * * * *", function(){
        console.log('The world is going to end today.');
})

**Expected result:**

Job is executed every 2 minutes

**Actual result**

Job executes immediately and only once

**Some analysis**

CronExpression.next() rises 'Invalid explicit day of month definition''. Looks like it is just related to 29 days in February 2016

**Comment by santigimeno** [comment]
Are you using version `1.0.0`?

**Comment by vimmerru** [comment]
I used 0.6. Can't reproduce it on 1.0.0. Thanks for support.

**Comment by noodlesticks** [comment]
1.0.0 fixed the issue for me.  Thanks!
