### ISSUE TITLE
Scheduler run instantly before scheduled time

### ISSUE THREAD

**Issue by mohamedmohsin** [node-schedule/node-schedule#246]
@tejasmanohar and @santigimeno 
var schedule = require('node-schedule');
 
schedule.scheduleJob('10 30 * * * *', function () {
	console.log('Node Scheduler Calls For every 30 min 10 second...................!');
});

**Comment by santigimeno** [comment]
Are you using version `1.0.0`?

**Comment by touletan** [comment]
Hi, I had the same issue and this has been fixed when I installed version 1. Could you please explain the reason why? Could this happen again when you'll upgrade to the next version?

**Comment by tejasmanohar** [comment]
There was a patch in v1.0.0 that affected anyone using node-schedule in the month of February due to leap years. @santigimeno Maybe we should add a notice to the readme?
