### ISSUE TITLE
Scheduling Assistance

### ISSUE THREAD

**Issue by rfossella** [node-schedule/node-schedule#247]
Hoping someone can assist.  Need to schedule job every 15 minutes between the hours of 7pm - 1am for weekdays (M-F).  Is this the optimal way of doing so?
```
var rule = new schedule.RecurrenceRule();
rule.dayOfWeek = [1,2,3,4,5];
rule.hour = [0, 1, 19, 20, 21, 22, 23];          // 12am, 1am, 7pm...
rule.minute = new schedule.Range(0, 59, 15);      // update EVERY 15 minutes

job = schedule.scheduleJob(rule, function(){console.log('hit schedule')})
```

Also, is there a way to modify an (the) existing schedule?  For example, between 7pm-10pm execute every 15 mins; 10:00pm-1am every 30 minutes?

Assistance or direction greatly appreciated.
Thanks.
Rob

**Comment by tejasmanohar** [comment]
Is 15 minutes a hard or soft rule? If soft, you could kick off a `setInterval` job at those times. This would obviously be reset every time your server reboots and whatnot so beware of that.

Anyhow, as per your question, I don't recommend you modify an existing schedule. Instead, create another schedule.

**Comment by rfossella** [comment]
Thanks for your response.  The rule is hard (also read/set from external config file) so I'd like to stay with scheduler.  So your recommendation would be to have multiple jobs/schedules for the periods I need?
e.g.
```
// rule1 , rule2  with dayOfWeek = [1,2,3,4,5];
rule1.hour = [0, 1, 22, 23];          // 12am, 1am, 10pm, 11pm...
rule1.minute = new schedule.Range(0, 59, 30);  30 mins
rule2.hour = [19,20,21 ];          // 7pm - 10pm
rule2.minute = new schedule.Range(0, 59, 15);  // 15 mins
```

Rob

**Comment by tejasmanohar** [comment]
Sounds fair. You could have dynamic code to generate these, but I think it's clearer that way :)
