### ISSUE TITLE
Question: how much memory does a job consume?

### ISSUE THREAD

**Issue by Dindaleon** [node-schedule/node-schedule#249]
Hello,

I would like to know how many jobs I can spawn in a period of time. So, If I want to have 10 scheduled jobs at once, how much memory would that consume?

**Comment by tejasmanohar** [comment]
Not sure off the top of my head. I doubt it's very expensive unless we have some mad memory leak that I don't know about ;), but this should be rather simple to profile! Definitely post results if you find any, and let us know if you have any trouble.

**Comment by komocode** [comment]
Is it common to have hundreds, perhaps, even thousands of jobs scheduled? I need to send out push notifications at certain date.

**Comment by tejasmanohar** [comment]
@Dindaleon Not sure off the top of my head. The basis for this would lie in Node's timers/events implementation. Sounds not so hard to get a minimal benchmark up (even if it's not 100% accurate in that there are other things in memory)- node-heapdump or node-inspector may help.

**Comment by tejasmanohar** [comment]
@komocode Could work, but dependent on what you're doing, a more robust queue-based task scheduler implementation that's backed by something like Redis may be ideal.

**Comment by santigimeno** [comment]
No follow up, closing. Feel free to reopen though
