### ISSUE TITLE
Job with already past schedule date still triggers

### ISSUE THREAD

**Issue by andela-omesanni** [node-schedule/node-schedule#250]
I noticed that a job whose schedule date is in the past e.g.Monday, February 8, 2016 still triggers. I would think that a job whose date is the past shouldn't trigger.

**Comment by santigimeno** [comment]
I would think so too. What version are you using? Can you post a reduced test case? Thanks

**Comment by tejasmanohar** [comment]
@santigimeno I think @andela-omesanni is talking about scheduling jobs with a date in the past.

@andela-omesanni The behavior of this was changed in v1, but yes, if you entered a date in the past in older versions,it would trigger immediately. See https://github.com/node-schedule/node-schedule/issues/157. Let me know if this is not the case, and I will re-open the issue :)
