### ISSUE TITLE
Schedule at Midnight evrey day

### ISSUE THREAD

**Issue by tomerb15** [node-schedule/node-schedule#251]
Hey, I was wondering if the following pattern will trigger a job at Midnight every day with no exceptions.
```
'0 0 0 * * *'
```
Thanks and sorry for the newbe question.

**Comment by MySidesTheyAreGone** [comment]
That pattern means "At the 0th second of the 0th minute of the 0th hour" so yes, it will trigger at Midnight; however you don't need to specify the second if you want the 0th. This is sufficient and equivalent to yours:
```
'0 0 * * *'
```

Keep the legend in the README.md handy:
```
*    *    *    *    *    *
┬    ┬    ┬    ┬    ┬    ┬
│    │    │    │    │    |
│    │    │    │    │    └ day of week (0 - 7) (0 or 7 is Sun)
│    │    │    │    └───── month (1 - 12)
│    │    │    └────────── day of month (1 - 31)
│    │    └─────────────── hour (0 - 23)
│    └──────────────────── minute (0 - 59)
└───────────────────────── second (0 - 59, OPTIONAL)
```

So `0 2 * * *` means "at 2 AM every day".

**Comment by tomerb15** [comment]
Thanks :)

**Comment by Ether0x** [comment]
The schedule '0 0 * * *' doesn't fire. Any known issues on this?

**Comment by xhkocatepe** [comment]
is there any solution for node-schedule, for every day at 12am once run ?

**Comment by nikjeni** [comment]
onComplete callback function does not work when a job is done, Could anyone help me out

**Comment by handhikadj** [comment]
I can confirm that @ghost solution is not working on Heroku dyno
