### ISSUE TITLE
Should there be an issue with mixing cron like schedules and date schedules?

### ISSUE THREAD

**Issue by geocontrol** [node-schedule/node-schedule#253]
I have an app that allows you to create one off schedules or repeat schedules (send me the message every wed & fri at 1426).

It was working, but now has stopped.

There should not be an issue using schedule.scheduleJob for a date and then again for a cron style should there?

(at the moment if i set one off dates its all working, as soon as i use the cron like jobs it all stops scheduling)

Thanks

Mark

**Comment by santigimeno** [comment]
What version of `node-schedule` are you using? Can you post a sample code that reproduces the issue? Thanks

**Comment by geocontrol** [comment]
latest version

var schedule = require('node-schedule');

The one off date:
		var job = schedule.scheduleJob(schedUName, scheduletime , function() {
			// Trigger the SMS messge
			triggerSMS(messageSchedule.messageId, messageSchedule.userId, model.id);
		});

The repeat:

// Set the schedule
		var job = schedule.scheduleJob('repeatSched' + model.id,'0 ' + schedMin + ' ' + schedHour + ' * * ' + daysofweek, function() {
			console.log("All the Scheduled Jobs: " + JSON.stringify(schedule.scheduledJobs));
			// Trigger the SMS messge
			triggerSMS(messageSchedule.messageId, messageSchedule.userId, model.id);
		});

**Comment by santigimeno** [comment]
@geocontrol if you don't set the one off date, does the cron job works? What's exactly the cron expression that is not working for you?

**Comment by geocontrol** [comment]
no any attempt at a cron style just does nothing

I tried a cron expression like this: '0 15 15 * * 5'

**Comment by santigimeno** [comment]
Are you sure you're using version `1.0.0`? Your example is working for me just fine:
```
var schedule = require('./');
var sinon = require('sinon');

var now = Date.now();

var clock = sinon.useFakeTimers();

// Set the current date to now
clock.tick(now);

schedule.scheduleJob('0 15 15 * * 5', function () {
  console.log('RUNNING JOB - ' + new Date());
});

// After 100 days...
clock.tick(100 * 24 * 60 * 60 * 1000);
```
The output is: 
```
RUNNING JOB - Fri Feb 19 2016 15:15:00 GMT+0100 (CET)
RUNNING JOB - Fri Feb 26 2016 15:15:00 GMT+0100 (CET)
RUNNING JOB - Fri Mar 04 2016 15:15:00 GMT+0100 (CET)
RUNNING JOB - Fri Mar 11 2016 15:15:00 GMT+0100 (CET)
RUNNING JOB - Fri Mar 18 2016 15:15:00 GMT+0100 (CET)
RUNNING JOB - Fri Mar 25 2016 15:15:00 GMT+0100 (CET)
RUNNING JOB - Fri Apr 01 2016 15:15:00 GMT+0200 (CEST)
RUNNING JOB - Fri Apr 08 2016 15:15:00 GMT+0200 (CEST)
RUNNING JOB - Fri Apr 15 2016 15:15:00 GMT+0200 (CEST)
RUNNING JOB - Fri Apr 22 2016 15:15:00 GMT+0200 (CEST)
RUNNING JOB - Fri Apr 29 2016 15:15:00 GMT+0200 (CEST)
RUNNING JOB - Fri May 06 2016 15:15:00 GMT+0200 (CEST)
RUNNING JOB - Fri May 13 2016 15:15:00 GMT+0200 (CEST)
RUNNING JOB - Fri May 20 2016 15:15:00 GMT+0200 (CEST)
```

**Comment by geocontrol** [comment]
no, you are right, i had latest  1.0.0 installed on a branch but it was not deploying to the test server properly. Taking myself out to shot myself for not picking this up.

Thanks for your help

**Comment by tejasmanohar** [comment]
:)
