### ISSUE TITLE
Unique scheduled Job launched several times.

### ISSUE THREAD

**Issue by ronyrun** [node-schedule/node-schedule#256]
Hello, 

There is a strange behavior on this execution : 

```javascript
   var j = schedule.scheduleJob('* * 13 * * 7', function () {  // 13h every sunday
                logger.info('Execution');
```

My logs showed the 'Execution' console log several times : 
My system did go down...
```
app-3 2016-02-14 13:00:56 - info: Execution
app-3 2016-02-14 13:00:56 - info: Execution
app-3 2016-02-14 13:00:56 - info: Execution
app-3 2016-02-14 13:00:56 - info: Execution
app-3 2016-02-14 13:00:56 - info: Execution
...
...
```

Can you please tell me what I did wrong ?
Best Regards,

**Comment by tejasmanohar** [comment]
Do you have multiple servers, processes, dynos (Heroku), or similar?

**Comment by ronyrun** [comment]
Hello, 

No, Only one.

**Comment by santigimeno** [comment]
@ronyrun What version of `node-schedule`? Can you reproduce it consistently or only happens sometimes?

**Comment by ronyrun** [comment]
Hello, 
it's the last version.
Let me reproduce it. And I'll tell you ASAP

**Comment by ronyrun** [comment]
I have the last version.

Is it because I added a * (seconds) ?

**Comment by tejasmanohar** [comment]
>Is it because I added a * (seconds) ?
I don't see that in your code? Please provide a testable snippet :)

**Comment by ronyrun** [comment]
schedule.scheduleJob('* * 13 * * 7', function () {
                                      ^here

**Comment by santigimeno** [comment]
@ronyrun is it your intention to trigger the job every second? If not remove the first star: `* 13 * * 7`

**Comment by santigimeno** [comment]
If you want it to execute the job at 13:00:00 every sunday: `0 13 * * 7` should do it

**Comment by ronyrun** [comment]
Thank you it works now :)
