### ISSUE TITLE
*/5 doesn't works

### ISSUE THREAD

**Issue by mwkaicz** [node-schedule/node-schedule#257]
Hi, it's few months ago when I used shedules last time. I wrote some app and then stoped using shedules for a while, so I just commented code and let be. Now I have a need to use it again. But it looks that this format ```*/15 * * * * *``` doesn't works now - I have no call of function inside shedule with this. 

It' looks that there are some other problems with cron format, f.e. in my case ```* * * * * *``` makes tick only once, and nothing more, but rules like ```{second: [0,15,30,45]}``` works good.

Was there some change for cron format?
Please, can somebody confirm to me, that it's still works?

**Comment by santigimeno** [comment]
@mwkaicz What version of `node-schedule` are you using?

**Comment by joshuatam** [comment]
Same here, ```*/30 * * * * *``` only tick once, but rules like ```{second: 30}``` working fine
Using version 0.2.9

**Comment by santigimeno** [comment]
Please, upgrade to `1.0.0`. Thanks
