### ISSUE TITLE
It might be an issue

### ISSUE THREAD

**Issue by diegosanchez** [node-schedule/node-schedule#259]
**node version**: v0.10.33
**release**: node-schedule@1.0.0

**issue**: 
I'm afraid of making a mistake but I have to ask you guys.

Having the code below:
```
var config = "03 17,18 * * *"
// it prompts program to run forever
setInterval(function() {
	log("silly", "Time debugging:" + Date());
}, 5000);

log("silly", "Cron configuration: " + config);
cron.scheduleJob(config, function() {
	log("silly", "Cron event time triggered at " + Date());
});
```

I got the out listed below: 

silly: Cron configuration: 03 17,18 * * * (index.js)
silly: Time debugging:Thu Feb 18 2016 17:02:55 GMT+0000 (UTC) (index.js)
silly: Time debugging:Thu Feb 18 2016 17:03:00 GMT+0000 (UTC) (index.js)
silly: Time debugging:Thu Feb 18 2016 17:03:05 GMT+0000 (UTC) (index.js)
silly: Time debugging:Thu Feb 18 2016 17:03:10 GMT+0000 (UTC) (index.js)
silly: Time debugging:Thu Feb 18 2016 17:03:15 GMT+0000 (UTC) (index.js)
silly: Time debugging:Thu Feb 18 2016 17:03:20 GMT+0000 (UTC) (index.js)
silly: Time debugging:Thu Feb 18 2016 17:03:25 GMT+0000 (UTC) (index.js)
silly: Time debugging:Thu Feb 18 2016 17:03:30 GMT+0000 (UTC) (index.js)
silly: Time debugging:Thu Feb 18 2016 17:03:35 GMT+0000 (UTC) (index.js)
silly: Time debugging:Thu Feb 18 2016 17:03:40 GMT+0000 (UTC) (index.js)
silly: Time debugging:Thu Feb 18 2016 17:03:45 GMT+0000 (UTC) (index.js)
silly: Time debugging:Thu Feb 18 2016 17:03:50 GMT+0000 (UTC) (index.js)
silly: Time debugging:Thu Feb 18 2016 17:03:55 GMT+0000 (UTC) (index.js)

I expect that at least one event is triggered at 17:03, but it doesn't happen.

I have parse the expression (03 17,18 * * *) manually and it's right.

What I'm doing wrong?

**Comment by santigimeno** [comment]
It works for me. Are you using version `1.0.0`?

**Comment by diegosanchez** [comment]
Events was triggered!

I think there was something wrong in the node_modules directory.

I think you can close this issue.
