### ISSUE TITLE
Not execute jobs first time immediately

### ISSUE THREAD

**Issue by thebergamo** [node-schedule/node-schedule#261]
Hi!
Every time I start my server the jobs are executed, but its not a good approach for me right now, have a way to cancel the first execution?

Cheers!
Marcos

**Comment by santigimeno** [comment]
They should not. Are you using the latest version: `1.0.0`?

**Comment by thebergamo** [comment]
Hum... not my version is `"node-schedule": "^0.2.9"`.

In the latest version this feature not exist?

**Comment by santigimeno** [comment]
It's not a feature, it was a bug. Try with the `1.0.0` version and let us know if it works for you. Thanks!

**Comment by thebergamo** [comment]
In the latest version seems not execute the jobs at the first time :) @santigimeno thanks :)
