### ISSUE TITLE
Cron run at initial time.

### ISSUE THREAD

**Issue by pongib** [node-schedule/node-schedule#264]
Hi guy, thank you for your amazing work. But I found some bug maybe when I start my node.js app, it fire my job immediately. This just use your example code but change cron time to run job every 5 seconds. 
```javascript
var schedule = require('node-schedule');

var j = schedule.scheduleJob('*/5 * * * * *', function(){
  console.log('The answer to life, the universe, and everything!');
});
``` 
Sometime it doesn't happen but when I stop and start my node app via `nodemon app.js` again it execute my job immediately. I use node version 4.2.6 and node-schedule version 1.0.0. Thank you for your help.

**Comment by santigimeno** [comment]
@pongib That rule means the job will be executed at second 0, 5, 10, ..., 55. It may happen that when you start your application the time at your machine matches with one of those values, so the job is executed at that very moment.

**Comment by pongib** [comment]
Oh Thank you, for your clarify.
