### ISSUE TITLE
Rule triggers every minute

### ISSUE THREAD

**Issue by bipin-nag** [node-schedule/node-schedule#266]
I used the following rule

```
var rule = new schedule.RecurrenceRule();
rule.hour = 12;
rule.min = 59;
```

But it triggered the function every minute from 12:00pm to 1:00pm.

**Comment by albertdatui** [comment]
@bipin-nag, can you give the test case that might reproduce the scenario?

thx

**Comment by bipin-nag** [comment]
@albertdatui  Here is what I used
```
var schedule = require('node-schedule');

var rule = new schedule.RecurrenceRule();
rule.hour = 9;
rule.min = 59;
 
var j = schedule.scheduleJob(rule, function(){
    console.log("Debug")
});
```

**Comment by santigimeno** [comment]
@bipin-nag it's `rule.minute`, not `rule.min`.

**Comment by santigimeno** [comment]
It works for me with that change. Feel free to reopen if it's still an issue. Thanks
