### ISSUE TITLE
Infinite loop due to clock changes (daylight savings time)

### ISSUE THREAD

**Issue by SystemParadox** [node-schedule/node-schedule#267]
There have been repeated issues about crashes and infinite loops caused by changing the date, especially due to daylight savings time changes. See #11, #131, #132, #214, #208. This issue is aimed to be a consolidation of those issues and a final solution. It would be good if we could avoid closing this until we absolutely sure that this is fixed for good.

This issue has caused downtime for us two years running now (when the clocks go forward at the end of March in the UK), with `0.1.13` and `0.1.16`, and I've only just worked out that node-schedule is the cause.

Most of the issues above point to the `while (true)` loop in `nextInvocationDate()`, which can get stuck when `Date` either doesn't increment or jumps back unexpectedly. For example, it will increment one minute at a time... `00:58:00`, `00:59:00`... but then jumps back to `00:00:00` because `01:00:00` does not exist on the night of daylight savings time.

This has been reported for `0.1.8`, `0.1.13`, `0.1.16`. Apparently it's fixed every time, only to find a new report against the next version that it's still similarly broken. One comment said there was a complete overhaul of this to fix it once and for all in `1.0.0`, but I've just upgraded to `1.1.0` and it's **_STILL**_ broken! Daylight savings time... the endless source of bugs :(

To reproduce:

```
var sinon = require('sinon');
var clock = sinon.useFakeTimers(+new Date(2016, 2, 26, 23, 59, 55), 'Date', 'setTimeout');
console.log('NEW DATE', new Date());
var schedule = require('node-schedule');
setInterval(function () {
    clock.tick(1000);
    console.log('NEW DATE', new Date());
}, 1000);

schedule.scheduleJob({ minute: 0 }, function () {
    console.log('MARK ' + new Date());
});
```

Run the above with version `0.1.16` or `1.1.0` and it will go into an infinite loop when reaching `01:00:00`. Depending on the version it will may be running the job repeatedly or just constantly trying to work out the next job time.

It seems there are two variations of this bug:
1. `nextInvocationDate` going into an infinite loop trying to work out the date of the next instance
2. Running an event at `00:00:00`, working out the next event is at `00:00:00` (because `01:00:00` got changed back to `00:00:00`), running the event again, working out the next event is at `00:00:00` again, etc.
3. Any others?

What can be done to finally fix this for good? How might it be rewritten if we start with the assumption that `Date` is malicious and will **actively try** to cause an infinite loop if it can?

Thanks.

**Comment by santigimeno** [comment]
@SystemParadox I feel your pain. The good news is that we're working on it and will have it solved soon.
The first step is already done: `cron-parser` now supports timezone and DST. The next step will be to integrate it into `node-schedule`. It should be quite straightforward. I expect having something for you to try this weekend, hopefully. I will post updates @ https://github.com/node-schedule/node-schedule/issues/217. Thanks

**Comment by carrollgt91** [comment]
Is this an issue on servers where their timezone does not use DST?

**Comment by santigimeno** [comment]
I dont think it should be a problem

**Comment by breel007** [comment]
Confirmed this is still an issue:  Following code results in an infinite loop in nextInvocationDate, starting one week before DST starts.  I believe it would start to work fine again after DST switch-over passes.

var ruleReboot = new schedule.RecurrenceRule();
	ruleReboot.dayOfWeek=0;
	ruleReboot.hour = 3;
	ruleReboot.minute= 30;
schedule.scheduleJob(ruleReboot, function(){	
	piReboot();
});

**Comment by SystemParadox** [comment]
Updated test code:

```
var lolex = require('lolex');
var clock = lolex.install(+new Date(2016, 2, 26, 23, 59, 55));
var schedule = require('node-schedule');

schedule.scheduleJob({ minute: 0 }, function () {
    console.log('MARK ' + new Date());
});

console.log(new Date());
for (var i=0; i < 70; i++) {
    for (var j=0; j < 60; j++) {
        clock.tick(1000);
    }
    console.log(new Date());
}
```

Results:

| node | node-schedule | result |
|--------|---------------------|---------|
| 0.10.25 | 0.1.16 | broken |
| 0.10.25 | 1.1.0 | broken |
| 0.10.25 | 1.2.0 | broken |
| 6.10.0 | 0.1.16 | works |
| 6.10.0 | 1.1.0 | works |
| 6.10.0 | 1.2.0 | works |

This does not really make sense. What's changed in node that would fix this?

**Comment by santigimeno** [comment]
@SystemParadox thanks for the detailed report. Before looking into this, have you chosen the initial date for a specific reason or should it happen with any date?

**Comment by SystemParadox** [comment]
The problem seems to come down to this:

```
# Node 0.10.25
> var d = new Date(2016, 2, 27, 0, 59, 59);
> d.toString()
'Sun Mar 27 2016 00:59:59 GMT+0000 (GMT)'
> d.setSeconds(60);
1459036800000
> d.toString()
'Sun Mar 27 2016 00:00:00 GMT+0000 (GMT)'

# Node 6.10.0
> var d = new Date(2016, 2, 27, 0, 59, 59);
> d.toString()
'Sun Mar 27 2016 00:59:59 GMT+0000 (GMT)'
> d.setSeconds(60);
1459040400000
> d.toString()
'Sun Mar 27 2016 02:00:00 GMT+0100 (BST)'
```

**Comment by santigimeno** [comment]
okay, have you tried with the latest from the `0.10.x` branch?

**Comment by SystemParadox** [comment]
Broken: `0.10.48`, `0.11.16`, `0.12.0`, `0.12.2`
Working: `0.12.3`, `0.12.4`, `0.12.9`, `0.12.18`

The only reason 0.10.x is of any interest is because it's the default installation in Ubuntu 14.04 (and yes I realise how old this is). There are so many packages that have already dropped support for it that this probably isn't worth making a workaround for. I'm planning to upgrade to node 6 soon anyway.

What do you think?

**Comment by santigimeno** [comment]
@SystemParadox sorry for the delayed response.

> There are so many packages that have already dropped support for it that this probably isn't worth making a workaround for
> What do you think?

I think I agree with you. I don't think making a workaround is worth it.

Thanks!
