### ISSUE TITLE
Persist scheduled jobs after node restart

### ISSUE THREAD

**Issue by Manish2005** [node-schedule/node-schedule#268]
Is there any way in the module to persist scheduled jobs after server restart?
I f not, can someone please suggest a good way to implement it using mongoDB?

**Comment by paperrr1** [comment]
Create a table in MongoDB that is filled with the data you'd like.  One boot scrape through that table and fill the scheduler.  Clear the table after that.

**Comment by Manish2005** [comment]
Thanks @paperrr1 . Got it to work after some initial troubles

**Comment by askdesigners** [comment]
Could also be done with redis, static files or whatever :)

**Comment by nodesocket** [comment]
Would be awesome to officially support Redis or MongoDB.

**Comment by tamaker** [comment]
I'm curious to get this working with (at first) just a static flat file that is loaded at boot.   do I just need to use FS to save out the schedule.scheduledJobs object to do this and when I load it (at boot) do I just iterate over the jobs and re-schedule them or is there a built in 'loader' of some kind?  Thx!
