### ISSUE TITLE
execute a job at every 3 hours of every day -help

### ISSUE THREAD

**Issue by madibalive** [node-schedule/node-schedule#269]
Hi, noob to this cron world 
I want o execute a job at every 3 hours of every day 
```
var rule = new schedule.RecurrenceRule();
rule.dayOfWeek = [0,6];
rule.hour = 17; // can i add multiple times [06,9,12,15,...]
rule.minute = 0;

var j = schedule.scheduleJob(rule, function(){
  console.log('Today is recognized by Rebecca Black!');
});
```

or  which seem too long
```
var rule1 = new schedule.RecurrenceRule();
rule1.dayOfWeek = [0,6];
rule1.hour = 06; // set at 6 am
rule1.minute = 0;

var rule2 = new schedule.RecurrenceRule();
rule2.dayOfWeek = [0,6];
rule2.hour = 09; // set at 9 am
rule2.minute = 0;
...

var j = schedule.scheduleJob(rule1, function(){
  console.log('Today is recognized by Rebecca Black!');
});
var j = schedule.scheduleJob(rule2, function(){
  console.log('Today is recognized by Rebecca Black!');
});
..
```
any help would be appreciated

**Comment by rguedes** [comment]
Hi,
Try this:

var j = schedule.scheduleJob('0 0 */3 * *', function(){
  console.log('The answer to life, the universe, and everything!');
});

**Comment by madibalive** [comment]
thanks , would test in and close issue in after 3 hours

**Comment by joshualong2012** [comment]
not sure if required or not but I added an additional * so my code was:

var j = schedule.scheduleJob('0 */1 * * * *', function(){
    
    console.log('Process Started!!');
});

Working perfectly finally!!
Had such a hard time finding this.

Now I will be updating to the correct time interval as needed.

**Comment by santigimeno** [comment]
It looks like the issue is solved. Please, reopen if you still have problems.

**Comment by vcasadei** [comment]
Hi, if I want to run at 19, 20, 21 and 22h, how can I do this?

Will I have to create one job for each? Or does hour accepts a list of items?

var rule = new schedule.RecurrenceRule();
rule.dayOfWeek = [0, new schedule.Range(5, 6)];
rule.hour = 19;
rule.minute = 0;

var rule1 = new schedule.RecurrenceRule();
rule1.dayOfWeek = [0, new schedule.Range(5, 6)];
rule1.hour = 20;
rule1.minute = 0;

var rule2 = new schedule.RecurrenceRule();
rule2.dayOfWeek = [0, new schedule.Range(5, 6)];
rule2.hour = 21;
rule2.minute = 0;

var rule3 = new schedule.RecurrenceRule();
rule3.dayOfWeek = [0, new schedule.Range(5, 6)];
rule3.hour = 22;
rule3.minute = 0;

schedule.scheduleJob(rule, fn)
schedule.scheduleJob(rule1, fn)
schedule.scheduleJob(rule2, fn)
schedule.scheduleJob(rule3, fn)

**Comment by santigimeno** [comment]
@vcasadei use a `Range`:

```js
rule.hour = new schedule.Range(19, 22);
```
