### ISSUE TITLE
check ongoing job before cancelling?

### ISSUE THREAD

**Issue by nasr18** [node-schedule/node-schedule#271]
How to check whether a job is running or not before cancelling that job? Because i tried cancelling a job after 30 seconds and it did as i wanted. but after another 30 seconds it throws error that `Cannot call method 'cancel' of undefined`. How to check for on going job?

**Comment by santigimeno** [comment]
@nasr18 do you have a test that demonstrates the issue?

**Comment by nasr18** [comment]
`var cron = require('node-schedule');`

```
var j = cron.scheduleJob('nasr', '*/5 * * * * *', function() {
    console.log('will get this console on every 5 sec.');
});
```

```
var k = cron.scheduleJob('30 * * * * *', function() {
    cron.scheduledJobs['nasr'].cancel();
    console.log('at first 30 sec of a minute the above job will get cancelled.');
});
```

again after another 30th sec of a minute i'm getting error as `Cannot call method 'cancel' of undefined.` and all of a sudden my nodejs server stop running.

How to fix this? I mean how to check whether that "nasr" job is on-going or not before it gets called.

**Comment by santigimeno** [comment]
@nasr18 can't you just check if `cron.scheduledJobs['nasr']` exists before calling cancel on it?

**Comment by nasr18** [comment]
Success. Got it.. Thank you dude.
