### ISSUE TITLE
Cron Job Finished status?

### ISSUE THREAD

**Issue by nasr18** [node-schedule/node-schedule#272]
I would like to know whether cron job finished or not after starting the job without using `if(cron.ScheduledJobs()`.

**Comment by albertdatui** [comment]
Hi!

You could attach an event listener and listen to 'run' event. This event is emitted once the job is invoked.

Hope it helps!

**Comment by nasr18** [comment]
thanks for replying. Can you pls post some code??? @albertdatui

**Comment by albertdatui** [comment]
```
var cron = require('./');
var sinon = require('sinon');

var now = Date.now();

var clock = sinon.useFakeTimers();

clock.tick(now);
var job = cron.scheduleJob('* * * * *', function() {});

job.on('run', function() {
  console.log("Invoked!");
})

clock.tick(120 * 1000);
```

The output
```
Invoked!
Invoked!
```

**Comment by albertdatui** [comment]
feel free to re-open the issue!
Thanks
