### ISSUE TITLE
every second does not work with object literal syntax

### ISSUE THREAD

**Issue by darkdragon-001** [node-schedule/node-schedule#275]
`schedule.scheduleJob({},callback)`

or when seconds should be optional, 

`schedule.scheduleJob({seconds: '*'},callback)`

should be equivalent to 

`schedule.scheduleJob('* * * * * *', callback)`

**Comment by albertdatui** [comment]
Hi! @darkdragon-001 

If you want to trigger the job every seconds by using object literal syntax. It can be done by using
```
schedule.scheduleJob({second: null},callback)
```
In addition, the property of the object should be _second_ not _seconds_

Hope it helps!

**Comment by albertdatui** [comment]
feel free to open the issue if you still encounter the bug!
