### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by kadosh1000** [node-schedule/node-schedule#281]
Hi, is there any way to log all schedueld jobs? maybe a callback function that run at the end of every job and gets the results of the job?

**Comment by albertdatui** [comment]
Hi @kadosh1000, can you be more specific?
what do you mean by the result of the job?

In addition, the library does provide scheduledJobs if you want to see the jobs in the queue.

Thanks

**Comment by TimMeade** [comment]
@kadosh1000  not sure if this helps,  i just did something like this:

    var j = scheduleObj.scheduleJob(when, what);
    j.callback = function() {
        console.log('CALLBACK?');
    };

But I'm just logging date/time and what was run....

**Comment by santigimeno** [comment]
No follow up, closing. Feel free to reopen though.
