### ISSUE TITLE
rule.second is not working

### ISSUE THREAD

**Issue by arshtepe** [node-schedule/node-schedule#282]
I have this bug
https://github.com/node-schedule/node-schedule/issues/277
system: 
Linux root 4.2.0-36-generic #42-Ubuntu SMP Thu May 12 22:05:35 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
my code
```js
   var rule = new schedule.RecurrenceRule();
   rule.second = 1;
  var d = new Date();
  var j = schedule.scheduleJob(rule, () =>  console.log((new Date - d)/1000));
```
console(seconds from start):
22
82
142
202

p.s same problem i have on node cron and same time interval node cron

**Comment by bambalaus** [comment]
If I understand correctly what is your issue, the comments in the bug you referenced explain what's happening here: your function is called every minute, at the 1 second of each minute. So, from you output it looks like you start the job at, for example, at 5:00:39 and after 22 second it trigger the job for the first time (5:01:01) and again after further 60 second (5:02:01), 82 seconds from the moment you started your application, etc...

**Comment by arshtepe** [comment]
@bambalaus  yes,  as in #277 . is It  bug?)

**Comment by bambalaus** [comment]
No, that's how is supposed to work, as the schedule work by setting point in time in the calendar, not intervals. If you want to run it every second you need to pass an array with all the seconds you want it to trigger, so [0,1,2,3,....,59].

**Comment by santigimeno** [comment]
@arshtepe, @bambalaus is right. If you set `second = 1`, the job will trigger on the second #1 of every minute. If you want to trigger a job every second you have 2 options:

```javascript
const schedule = require('node-schedule');

const job1 = schedule.scheduleJob({ second : null }, () => {
   console.log(new Date(), 'job1');
});

const job2 = schedule.scheduleJob('* * * * * *', () => {
   console.log(new Date(), 'job2');
});
```

**Comment by santigimeno** [comment]
Closing the bug for the moment. Feel free to re-open though :)
