### ISSUE TITLE
can a job be re-scheduled ? 

### ISSUE THREAD

**Issue by BOUAZIZamrou** [node-schedule/node-schedule#283]
I'm working on an app where I need to schedule some jobs in the future. and it turns out that I may need to re-schedule some of them? Can I do that using the node-schedule module? #

**Comment by santigimeno** [comment]
Does this work for you?  https://github.com/node-schedule/node-schedule/blob/master/lib/schedule.js#L545

**Comment by santigimeno** [comment]
These tests: https://github.com/node-schedule/node-schedule/blob/master/test/convenience-method-test.js#L202-L556 can show you how to use it.

**Comment by BOUAZIZamrou** [comment]
Thank you ! That works perfectly !!
