### ISSUE TITLE
Unable to test schedule via sinon.useFakeTimers()

### ISSUE THREAD

**Issue by elnewfie** [node-schedule/node-schedule#287]
Greetings,

I'm trying to incorporate node-schedule into my app, but having trouble getting it to execute via my test cases.  I'm using the [SinonJS](http://sinonjs.org/) library to simulate the flow of time.

I'm using a very simple test case to see if the schedule is executing:

``` javascript
const scheduler = require("node-schedule"),
   sinon = require("sinon");

describe("test case", () => {
    it("runs schedule", done => {
        const clock = sinon.useFakeTimers();

        //Execute one second from now
        scheduler.scheduleJob("1 0 0 * * *", () => {
            console.log("GOT HERE!");
            clock.restore();
            done();
        });

        clock.tick(1000000);
    });
});
```

However, when I run the above, the scheduled task does not run at all.  Any ideas if I'm missing something, or if this is a bug?

**Comment by santigimeno** [comment]
@elnewfie I think there's nothing wrong with your test as it works as expected. The cron expression you're using should trigger the job only once a day: @ `00:00:01`. The clock is ticking less than 1-day milliseconds. Change the tick value to: `1 * 24 * 60 * 60 * 1000` and it should work.

**Comment by santigimeno** [comment]
No follow up, closing. Feel free to re-open though
