### ISSUE TITLE
Scheduled job skips execution every second time

### ISSUE THREAD

**Issue by n2sandhu** [node-schedule/node-schedule#289]
Hey. i have just started using node-schedule to schedule a cron job on my server which is supposed to run at 1520 hours everyday. For the first week it ran as expected but afterwards it started skipping one day before next execution. i noticed this as i send out an email to myself every time the cron job is executed. I also have set up logs to log when the cron job executes. Both emails and logs suggest that it skips a day before next execution. For example, the last 3 executions of scheduled job were on 8th,10th and 12th  of  July, skipping 9th and 11th of July. This is the code i am using to set up the cron job

```
var rule = new schedule.RecurrenceRule();
    rule.hour = 15;
    rule.minute = 20;

    schedule.scheduleJob(rule, function(){
       //Some logic goes here
    });
```

Am i missing something ??

**Comment by santigimeno** [comment]
@n2sandhu Thanks for the report. It sounds strange indeed. A couple of things I can think of to try to track down the issue:
- Using `sinon` fake timers, reproduces the issue for you?:
```js
var schedule = require('schedule');
var sinon = require('sinon');

// Use sinon fake timers starting from current date.
var now = Date.now();
var clock = sinon.useFakeTimers();
clock.tick(now);

var rule = new schedule.RecurrenceRule();
rule.hour = 15;
rule.minute = 20;

schedule.scheduleJob(rule, function(){
   //Some logic goes here
   console.log(new Date());
});

// Simulate 14 days have passed
clock.tick(14 * 24 * 60 * 60 * 1000);
```
- Add this log to the code in the server and wait for the issue to happen:
```
diff --git a/lib/schedule.js b/lib/schedule.js
index 69e4273..5d582e5 100644
--- a/lib/schedule.js
+++ b/lib/schedule.js
@@ -487,6 +487,8 @@ function scheduleNextRecurrence(rule, job, prevDate) {
   prevDate = (prevDate instanceof Date) ? prevDate : (new Date());
 
   var date = (rule instanceof RecurrenceRule) ? rule.nextInvocationDate(prevDate) : rule.next();
+  console.log('CurrentDate: ', new Date());
+  console.log('NextInvocationDate: ', date.toString());
   if (date === null) {
     return null;
   }
```

**Comment by santigimeno** [comment]
@n2sandhu ping

**Comment by santigimeno** [comment]
No follow-up. Closing. Feel free to re-open if this is still an issue. Thanks
