### ISSUE TITLE
Update scheduled job time.

### ISSUE THREAD

**Issue by svadodariya** [node-schedule/node-schedule#291]
Can you please help me out to update the time of scheduled job? Is there any method for update time for job which already scheduled?

Thanks Ahead The Time,
Sudhir

**Comment by santigimeno** [comment]
@svadodariya I think `rescheduleJob` should help you: https://github.com/node-schedule/node-schedule/blob/master/lib/schedule.js#L522-L535

**Comment by santigimeno** [comment]
Closing. Feel free to reopen if the issue hasn't been resolved for you
