### ISSUE TITLE
Test if schedule is valid.

### ISSUE THREAD

**Issue by ericrini** [node-schedule/node-schedule#296]
Is there any way to test if a scheduling string is valid, without actually creating the job?

**Comment by santigimeno** [comment]
No. The best option would probably be creating the job, check if it's successfully created and cancel it.

**Comment by jugaltheshah** [comment]
You can also use an online checker tool: http://cron.schlitt.info/. As long as you're aware of the [unsupported features](https://github.com/node-schedule/node-schedule#unsupported-cron-features) of node-schedule, it should get the job done.

**Comment by rtodea** [comment]
As `node-scheduler` uses `cron-parser` to handle cron-like syntax you could do something along these lines:
```
const cronParser = require('cron-parser');

// `when` is the cron-like string
try {
  cronParser.parseExpression(when);
} catch (error) {
  // handle the parse error
}
// on success, schedule the job

```

**Comment by santigimeno** [comment]
Closing as it seems to be correctly answered. Feel free to re-open if you have further questions.
