### ISSUE TITLE
Safely stop job

### ISSUE THREAD

**Issue by wayofthefuture** [node-schedule/node-schedule#298]
Will job.cancel() wait for the job to stop before cancelling? What are the chances that on application fail or exit, a task will be stopped in the middle of executing code. For example, what if it is writing to MongoDB and the application exists in the middle of the task. Is there a way to wait for all jobs to finish then exit?

**Comment by santigimeno** [comment]
In short, no. Cancelling a job just avoids future invocations of the scheduled job. Improvements in this area are certainly possible.

**Comment by kylecordes** [comment]
If anyone wonders by with a tip on how (using this library or any other) to implement safe job stopping, it would be great to leave a link here for the next one of us that wanders by looking.

(To clarify: safely stopping a job means that, first use the scheduler API to stop the job; then you get a promise which won't resolve until the job has actually stopped. This implies that the function being scheduled must itself be a promise-returning function - in other words the scheduler cannot assume job code is synchronous. Most real Node code is asynchronous.)
