### ISSUE TITLE
Skipping task after (more or less) one hour

### ISSUE THREAD

**Issue by esuarezz** [node-schedule/node-schedule#300]
So I am running this task:  **var j = schedule.scheduleJob('5 * * * * *', function(){**.........[]
And everything is fine after 1 hour... it is like this is not called anymore, should I set perhaps something more???

*

**Comment by esuarezz** [comment]
another question:

is it possible to execute the first time inmediately? I have not found that possibility in the tests and readme file

**Comment by sunkuo** [comment]
Can you post the log? I don't think it is the problem of node-schedule

**Comment by esuarezz** [comment]
The problem was with the Heroku plan.... it was getting out of memory! you can close it! 

Thanks!

**Comment by mitchellporter** [comment]
> The problem was with the Heroku plan.... it was getting out of memory! you can close it!

@esuarezz Can you elaborate on this? Was your free dyno going to sleep or was there an actual memory problem?

**Comment by esuarezz** [comment]
Hi! it was not a memory problem, I checked that, it was the dyno, so dont
worry, it is something not related with node-schedule, if not I would tell
you! thank and good job!

**Comment by santigimeno** [comment]
Great you found out what the problem was.
