### ISSUE TITLE
Each Nth day and month are not working correctly (*/N)

### ISSUE THREAD

**Issue by catherinetsokur** [node-schedule/node-schedule#301]
Patterns like `*/2 * * * * *`, `* */3 * * * *`, `* * */4 * * *` - each Nth second, minute, hour - work perfectly fine.
Patterns for day and month - `* * * */3 * *` and `* * * * */3 *` - are not working properly. As today is 27th of September (month 9) `*/3` should be a valid pattern for both, as they are both dividable by 3. 
Whereas pattern like this `* * * 25,26,27,28,29,30/3 * *` (where 27th is the third in the list) works well. I can make an assumption, that it has something to do with the starting point of counting - it is 0 for seconds, minutes and hours (where it works), and 1 for days and months (where it doesn't).

**Comment by catherinetsokur** [comment]
Goes wrong in [```cron-parser```](https://github.com/harrisiirak/cron-parser) already. It generates next execution `Sat Oct 01 2016 10:00:00 GMT+0000` for expression `0 0 10 */3 */3 *`, when it should be `Tue Sep 27 2016 10:00:00`.

**Comment by santigimeno** [comment]
Thinking about it, it looks correct. The manual here: https://linux.die.net/man/5/crontab says:
`Following a range with "<number>" specifies skips of the number's value through the range`. 
I interpret it that using this pattern for month; `* * * * */3 * `, should match for: `1, 4, 7 and 10`. The same can be applied for day. What do you think?

**Comment by catherinetsokur** [comment]
There's an example right after your quotation `For example, "0-23/2" can be used in the hours field to specify command execution every other hour (the alternative in the V7 standard is "0,2,4,6,8,10,12,14,16,18,20,22"). Steps are also permitted after an asterisk, so if you want to say "every two hours", just use "*/2".`

I will try to contribute a fix to cron-parser. Just got it working locally.

**Comment by catherinetsokur** [comment]
Here's a thing btw - http://crontab-generator.org/ - don't know what it's built on, but I totally agree with it's results.

**Comment by santigimeno** [comment]
Yes, I read that. What's not completely clear to me with that text is when it starts counting the steps. 

Hours seems clear, its range is: `0-23` so `0-23/2` and `*/2` seem like they should do the same: starting on `0` --> `0, 2, 4, ...`.

Month range goes: `1-12` so if `1-12/2` has to be equivalent to `*/2` it should go: `1, 3, 5, 7, 9, 11`. The same should apply to `*/3`.

Anyway, open the PR @ cron-parser and let's see how it goes.

**Comment by catherinetsokur** [comment]
That's weird indeed. `*/2` and `1-12/2` should produce the same result. You are right here. Can be something to do with `*/2` meaning modulo and ranges meaning order numbers starting from the first element...  Then more fixes will be needed. But I'm pretty sure, that `*/2` should be even.

**Comment by catherinetsokur** [comment]
Was just executing cron jobs and figured out I was wrong about `*/2` being even. Taking into account today is 2016-09-27:

`* * */2 * *    echo '* * */2 * *' >> /tmp/crontest.txt                             # Executed: Odd days 1,3,5... 27
* * * */2 *    echo '* * * */2 *' >> /tmp/crontest.txt                             # Executed: Odd month 1,3,5...9
* * */3 * *    echo '* * */3 * *' >> /tmp/crontest.txt                             # Not executed: 1,4,7....
* * * */3 *    echo '* * * */3 *' >> /tmp/crontest.txt                             # Not executed: 1,4,7....
* * 26,27,28,29/2 * *    echo '* * 26,27,28,29/2 * *' >> /tmp/crontest.txt         # Executed
* * 25,26,27,28,29/3 * *   echo '* * 25,26,27,28,29/3 * *' >> /tmp/crontest.txt    # Executed
* * 1-31/2 * *   echo '* * 1-31/2 * *' >> /tmp/crontest.txt                        # Executed: Odd days 1,3,..... 27
* * 2-30/2 * *   echo '* * 2-31/2 * *' >> /tmp/crontest.txt                        # Not executed: Even days 2,4,6....
* * * 1-12/2 *   echo '* * * 1-12/2 *' >> /tmp/crontest.txt                        # Executed: Odd month 1, 3, 5, 7, 9, 11
* * * 2-12/2 *   echo '* * * 2-12/2 *' >> /tmp/crontest.txt                        # Not executed: Even month 2,4, ... 12
`
So for `*/N` (where X is a min value) and intervals `X-Y/N`: X will be the first, X+N.
For A,B,C/N seems it still counts order number. But cannot explain why examples work.
So everything is okay. Sorry for creating a confusion.

**Comment by santigimeno** [comment]
No problem. Something new I learnt too.
