### ISSUE TITLE
Is it possible to access the rule being executed?

### ISSUE THREAD

**Issue by jamesone** [node-schedule/node-schedule#303]
I've got a loop like so:

```
// Create new cron for each iteration (creating 1-10 mins)
for (var x = 1; x<10; x++){
      var rule = new schedule.RecurrenceRule();
      rule.minute = new schedule.Range(0, 59, x);
      schedule.scheduleJob(rule, (RULE_SHOULD_ BE_HERE) => {
     // Can I access the RULE which is being executed NOW somehow?!

```

Is the functionality built in so that when a cron runs, the rule for it can be accessed?

I created a SO question here: http://stackoverflow.com/questions/39842781/node-schedule-how-can-i-access-the-current-rule-which-is-being-executed

**Comment by santigimeno** [comment]
@jamesone Not directly. You can always do something like this:
```js
var rule = new schedule.RecurrenceRule();
rule.minute = new schedule.Range(0, 59, x);
var job = schedule.scheduleJob(rule, () => {
  console.log('Rule should be here', this.rule);
});
job.rule = rule;
```

**Comment by jamesone** [comment]
That does it, thanks. Feel free to post it on the SO question! BTW I had to use `function () {` instead of the fat arrow `() => {` as `this` inside a fat arrow is globally scoped.

**Comment by santigimeno** [comment]
Closing this. Feel free to reopen if you think something else needs to be discussed
