### ISSUE TITLE
Problem when define unordered hours list 

### ISSUE THREAD

**Issue by leoslopez** [node-schedule/node-schedule#304]
I have a cron definition to run at minute 0 past hour 1, 9, and 11:
- When I defined in this way: _0 9,11,1 \* \* *_ (the job is not running at 1)
- When I defined in this way: _0 1,9,11 \* \* *_ (it's running correctly)

It seems to be a problem related to node-schedule.

**Comment by santigimeno** [comment]
@leoslopez please, report the issue @ cron-parser: https://github.com/harrisiirak/cron-parser/. It looks like a bug to me, but let's see what they think. Thanks

**Comment by leoslopez** [comment]
Here is [the issue](https://github.com/harrisiirak/cron-parser/issues/75)
Thanks!

**Comment by santigimeno** [comment]
This will be fixed once https://github.com/node-schedule/node-schedule/commit/0883f24dcb2717f04aba9bb8503f260c706ae144 lands.

**Comment by santigimeno** [comment]
Should be fixed by https://github.com/node-schedule/node-schedule/commit/519917bc8138ebc9a8ad19641a02fbaec89ff69d. Feel free to re-open if it's still an issue. Thanks
