### ISSUE TITLE
"Set StartTime and EndTime" functionality not included in release

### ISSUE THREAD

**Issue by gtorodelvalle** [node-schedule/node-schedule#307]
Hi @tejasmanohar , @santigimeno (since I saw you both made releases for this repo in the past), all,

I was trying the "Set StartTime and EndTime" functionality and noticed it didn't work in release `1.1.1`. The reason is that although this functionality is included in `master` (see https://github.com/node-schedule/node-schedule/blob/master/lib/schedule.js#L192), it is not included in the latest release (as for now `1.1.1`, see https://github.com/node-schedule/node-schedule/blob/v1.1.1/lib/schedule.js#L189 and you'll find no processing of the `start` and `end`dates)... 😮 

Any reason for that? 😃 

In fact, I checked that picking the file from `master` (setting the dependency in my `package.json` file such as this: `"node-schedule": "node-schedule/node-schedule"`, it gets the master version and the functionality works as expected... 😉 

It would be great if you could publish a new release including this functionality to have better control on which version a project which leans on yours depends on (leaning on the master version is kind of risky... 😨 ).

Thank you very much!

**Comment by santigimeno** [comment]
> Any reason for that?

@gtorodelvalle not really, just didn't think about it. :). I'll make a release asap (or now)

**Comment by gtorodelvalle** [comment]
Thank you very much once again, this time for your quick reply... 😃

**Comment by santigimeno** [comment]
> leaning on the master version is kind of risky... :fearful:

BTW you could always use the hash of the commit.

**Comment by santigimeno** [comment]
Version `1.2.0` released. Thanks!
