### ISSUE TITLE
not running for hour job.

### ISSUE THREAD

**Issue by jefftham** [node-schedule/node-schedule#308]
it is not running for hour job.

```
    var schedule = require('node-schedule');

     schedule.scheduleJob('* * 11 * * *', function(){
                console.log(new Date().toLocaleString('en-us',{timeZone:'America/New_York'}));
     });

   //no result at all for every 11am
```

**Comment by santigimeno** [comment]
@jefftham if your purpose is that the job runs exactly at 11am, you should use the following rule: `0 11 * * *` or `0 0 11 * * *`. The rule you are using, triggers the job every second in 11 am hour i.e. 11:00:00, 11:00:01, and so on

**Comment by jefftham** [comment]
@santigimeno , i understand that it will be running every second or minute at 11am. However, it is not working.

**Comment by santigimeno** [comment]
@jefftham Ok, I see.

I've tried your code, and it's working correctly in my box. Maybe it's a problem with timezones. Is your  system configured in the same timezone you're expecting the job to run? I mean, I'm in `Europe/Madrid` and the output of your code is (using `0 11 0 0 0`):
```
10/27/2016, 5:00:00 AM
10/28/2016, 5:00:00 AM
10/29/2016, 5:00:00 AM
10/30/2016, 6:00:00 AM
10/31/2016, 6:00:00 AM

```
that's 11 am in my timezone translated to `America/New_York`... I'm just guessing.

**Comment by jefftham** [comment]
@santigimeno , you are right.  it is my timezone problem. i suggest the developer add it to the README.md  and warn others.  

Thanks for your time, and sorry for disturbing.
