### ISSUE TITLE
Fix for Documentation

### ISSUE THREAD

**Issue by ssmith88** [node-schedule/node-schedule#309]
The code snippet below does not work. 

let **startTime** = new Date(Date.now() + 5000);
let endTime = new Date(**now**.getTime() + 5000);
var j = schedule.scheduleJob({ start: startTime, end: endTime, rule: '*/1 * * * * *' }, function(){
  console.log('Time for tea!');
});

I believe you wanted ...**startTime**.getTime()...

Or at least that is how I got it to work.

**Comment by santigimeno** [comment]
I think this was fixed with https://github.com/node-schedule/node-schedule/commit/fa1212b1e8e4f8eda2001c90330f8bc94725619e
