### ISSUE TITLE
Last execution date

### ISSUE THREAD

**Issue by kkarahainko** [node-schedule/node-schedule#310]
I have a job, it should fire every 10 min. App is crashed on 9 min and after restart I have to wait 10 mins again, but it should start immediately because 10 mins is passed after last execution (stored in db). Is it possible to define a last execution date somehow or use start date for this purposes?

**Comment by santigimeno** [comment]
Does this cover your needs https://github.com/node-schedule/node-schedule#set-starttime-and-endtime?

**Comment by kkarahainko** [comment]
Thank you, solved.
