### ISSUE TITLE
poor documentation: RecurrenceRule options 

### ISSUE THREAD

**Issue by magicdawn** [node-schedule/node-schedule#315]
the document on the README.md did not list the options / properties of the RecurrenceRule instance,but I had seen code in a ancient project

```js
var rule = new schedule.RecurrenceRule();
rule.hour = 1;
rule.daysInMonth = 1;
rule.minute = 0;
```

The `daysInMonth` option is not working, and don't know where the code come from,
After read the source code, I can only know the property name is `date`, So we'd better add these to the documentation.

https://github.com/node-schedule/node-schedule/blob/v1.2.0/lib/schedule.js#L330-L340
```js
function RecurrenceRule(year, month, date, dayOfWeek, hour, minute, second) {
  this.recurs = true;

  this.year = (year == null) ? null : year;
  this.month = (month == null) ? null : month;
  this.date = (date == null) ? null : date;
  this.dayOfWeek = (dayOfWeek == null) ? null : dayOfWeek;
  this.hour = (hour == null) ? null : hour;
  this.minute = (minute == null) ? null : minute;
  this.second = (second == null) ? 0 : second;
}
```

**Comment by magicdawn** [comment]
# the list

- `second`
- `minute`
- `hour`
- `date`
- `month`
- `year`
- `dayOfWeek`

**Comment by santigimeno** [comment]
@magicdawn you're correct, the documentation is lacking in a lot of aspects. Would you like to create a PR fixing this issue? Thanks!

**Comment by santigimeno** [comment]
Fixed by https://github.com/node-schedule/node-schedule/commit/852b3c9505474b7985b22081d8e08fd60583aedb

**Comment by alexgleason** [comment]
To clarify, does "date" in this context actually mean "day of the month"?
