### ISSUE TITLE
Is it possible to validate cron pattern?

### ISSUE THREAD

**Issue by whitecolor** [node-schedule/node-schedule#318]
Is it possible currently to validate cron string other other options format?

**Comment by rtodea** [comment]
If you would like to validate the cron-like pattern before actually creating a job, see [my comment](https://github.com/node-schedule/node-schedule/issues/296#issuecomment-269971152) on [issue#296](https://github.com/node-schedule/node-schedule/issues/296).

**Comment by whitecolor** [comment]
Ok thanks.
