### ISSUE TITLE
NWJS context issue

### ISSUE THREAD

**Issue by jssuttles** [node-schedule/node-schedule#321]
This is probably a weird use case for you, but I tried using this package in nwjs.
I maintain two apps. 
I first used this with an nwjs app with --mixed-content enabled. This worked perfectly.
Then, I used it in my other nwjs app that doesn't have --mixed-content enabled, and it didn't work. It returned a recurring rule that recurs every minute. I was trying to schedule a job to occur on a single date.
I've tested this with the solution here: http://stackoverflow.com/questions/1353684/detecting-an-invalid-date-date-instance-in-javascript
spec instanceof Date 
is false
Object.prototype.toString.call(spec) === "[object Date]" 
is true
So, I guess I'm having a cross-frame issue.

**Comment by tejasmanohar** [comment]
Closing this out since I think it's related to NWJS and don't see a relevant fix in this module but feel free to comment if that's not the case.
