### ISSUE TITLE
Could I pause/resume a job?

### ISSUE THREAD

**Issue by knight42** [node-schedule/node-schedule#324]

**Comment by santigimeno** [comment]
@knight42 I'm not sure I understand. Can you describe your use case? Thanks!

**Comment by knight42** [comment]
@santigimeno In some cases I want to pause a job until certain condition is met. I know that I can remove the job and re-add it, but if I could invoke some APIs, say `scheduledJobs[name].pause()` or `scheduledJobs[name].resume()`, that would be significantly more convenient.

**Comment by santigimeno** [comment]
I'm not sure if this should belong to the module. As you say, removing / adding the job should do it. All that said, I'm not totally opposed to it, so if you come with a proposal (pull request) we can discuss it. Thanks!
