### ISSUE TITLE
TypeError: Cannot read property 'execute' of undefined

### ISSUE THREAD

**Issue by PsyTae** [node-schedule/node-schedule#328]
Here is my code, simple test to try and get it to console out every minute to make sure the schedule will work.  also tried with rule.minute = (next minute of the hour); and rule.minute = 0;

```
console.log('Inside Delete Processor');
var schedule = require('node-schedule');
var rule = new schedule.RecurrenceRule();
//rule.hour = 0;
rule.minute = null;
		
var deleteSchedule = schedule.scheduleJob(rule, deleteExpiredFiles());

function deleteExpiredFiles(){
	console.log(moment().format('MMM DD, Y hh:mm:ss A'), ': Scheduled Tick');
}
```

Received same error every time.

```
C:\NodeCode\Processor\node_modules\node-schedule\lib\schedule.js:177
    this.job.execute();
            ^
TypeError: Cannot read property 'execute' of undefined
    at Job.invoke (C:\NodeCode\Processor\node_modules\node-schedule\lib\schedule.js:177:13)
    at Timeout._onTimeout (C:\NodeCode\Processor\node_modules\node-schedule\lib\schedule.js:479:11)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

**Comment by PsyTae** [comment]
It seems to work only if I use an anonymous function in stead of a named function... that doesn't seem to be right.... but I got it working using:

```
var deleteSchedule = schedule.scheduleJob(rule, function (){
	deleteExpiredFiles();
});
```

**Comment by rtodea** [comment]
Hi @PsyTae,

You should not invoke the function, but pass the `Function` object:
```
var deleteSchedule = schedule.scheduleJob(rule, deleteExpiredFiles); // note the missing `()`
```

In:
```
var deleteSchedule = schedule.scheduleJob(rule, deleteExpiredFiles());
```
you are invoking the function `deleteExpiredFiles` by `deleteExpiredFiles()`.
`deleteExpiredFiles` does not have any return statement (i.e. the return value is `undefined`).

Thus your line is equivalent to:
```
var deleteSchedule = schedule.scheduleJob(rule, undefined);
```

which is further equivalent to:
```
var deleteSchedule = schedule.scheduleJob(rule);
```

`scheduleJob` expects at least 2 proper arguments to actually create a `Job`.
Otherwise it returns `null`.

When writing anonymous functions you are less likely to invoke it by mistake.
```
var deleteSchedule = schedule.scheduleJob(rule, function (){
	deleteExpiredFiles();
});
```
vs
```
var deleteSchedule = schedule.scheduleJob(rule, (function (){
	deleteExpiredFiles();
})());
```

Please close the issue if this solves your problem.

**Comment by PsyTae** [comment]
This solves my Problem.

**Comment by rmorrise** [comment]
Can you please add in error checking code, so that the scheduleJob() method throws an error immediately if schedule.scheduleJob(rule, undefined) is called? This would make it much easier to troubleshoot.

**Comment by fplaten** [comment]
Sorry to reply to this closed issue, but how would I pass an argument to the named function? 

I'm currently doing `schedule.scheduleJob(new Date(), function() { myNamedFunction(myArgument) });

**Comment by FlandersBurger** [comment]
> Sorry to reply to this closed issue, but how would I pass an argument to the named function?
> 
> I'm currently doing `schedule.scheduleJob(new Date(), function() { myNamedFunction(myArgument) });`

Have you found an answer to this?

**Comment by fplaten** [comment]
yes, I needed to bind the object:

```
function initSchedule(argument, callback)
 const jobSchedule = nodeSchedule.scheduleJob(schedule, (argumentToPass => {
    callback(argumentToPass);
  }).bind(null, argument));
```

```
function myNamedFunction(myArgument) {
  // do something with job
}

initSchedule(myArgument, myNamedFunction);
```
