### ISSUE TITLE
bitdefender Virus Report

### ISSUE THREAD

**Issue by MarkPareja** [node-schedule/node-schedule#329]
Bitdefender is flagging ' node_modules/node-schedule/test/job-test.js ' as "Infected"  

node-schedule@1.1.0 

Detected as " Generic.JS.NemucodC.B9AB1355 "

**Comment by tejasmanohar** [comment]
Weird. Not familiar with this. The error sounds like it'd just flag all Node code. Feel free to PR if there's something I'm missing.
