### ISSUE TITLE
Issue setting up multiple scheduled emails

### ISSUE THREAD

**Issue by itsmoops** [node-schedule/node-schedule#332]
Hey there! I'm trying to set up an email scheduler on a Heroku worker process that will send an email 4 times a day. One at 9am, 12:30pm, 4pm and 7pm. What I end up seeing is that the last email job runs at 7'oclock, but then it continues firing every minute afterwards. Clearly I am setting something up incorrectly here, is the scheduler meant to be able to used like this - setting up multiple RecurrenceRules?

Any help would be very much appreciated.

```
const schedule = require('node-schedule');

let rule1 = new schedule.RecurrenceRule();
rule1.hour = 9;
schedule.scheduleJob(`9am`, rule1, () => {
  console.log('9 oclock');
});

let rule2 = new schedule.RecurrenceRule();
rule2.hour = 12;
rule2.minute = 30;
schedule.scheduleJob(`12:30pm`, rule2, () => {
  console.log('12:30 oclock');
});

let rule3 = new schedule.RecurrenceRule();
rule3.hour = 16;
schedule.scheduleJob(`4pm`, rule3, () => {
  console.log('4 oclock');
});

let rule4 = new schedule.RecurrenceRule();
rule4.hour = 19;
schedule.scheduleJob(`7pm`, rule4, () => {
  console.log('7 oclock');
});
```

**Comment by fgkramer** [comment]
Hi @itsmoops, the syntax seems correct and indeed, multiple schedules is the currently available way to run jobs at different periods of time when this periods don't defer by the same amount of time.

You could try setting the minutes on rule4 like `rule4.minute = 0;`.

Cheers.

**Comment by rtodea** [comment]
Hi @itsmoops,

The correct way to use `RecurrenceRule` is as suggested by @fgkramer (i.e. setting explicitly the `minute` property to 0).

Please read the `README.md` recurrence rule [section](https://github.com/node-schedule/node-schedule#recurrencerule-properties), and please mind the following:
> **Note**: It's worth noting that the default value of a component of a recurrence rule is
`null` (except for seconds, which is 0 for familiarity with cron). *If we did not
explicitly set `minute` to 0 above, the message would have instead been logged at
5:00pm, 5:01pm, 5:02pm, ..., 5:59pm.* Probably not what you want.

The rules created by you that do not have `minute` will run every minute, i.e:

1. `rule1` 9 am (9:00, 9:01, ..., 9:59)
2. `rule3` 4 pm (16:00, 16:01, ..., 16:59)
3. `rule4` 7 pm (19:00, 19:01, ..., 19:59)

I suspect you did not notice the first two as heroku instances are usually put to sleep when not used.

If you consider this solves the issue, please close it.

Have a nice day!

**Comment by itsmoops** [comment]
Thank you both @fgkramer and @rtodea, that resolved the issue! I had erroneously assumed that leaving minute undefined would default the value to 0.
