### ISSUE TITLE
job runs multiple times every minute with reschedule

### ISSUE THREAD

**Issue by goto100** [node-schedule/node-schedule#336]
```
const schedule = require('node-schedule');

const cron = '*/1 * * * *';
const job = new schedule.Job('test', function () {
	console.info('job ' + job.name + ' running at ' + new Date().toLocaleString());
	job.reschedule(cron);
});

job.schedule(cron);
```

job runs hundred times with this code. `job.reschedule()` function fires the job runs wrongly.

but if changed the code `const cron = '*/15 * * * * *';`, it's just runs once, `jos.rescheduled()` functoin works fine.

**Comment by santigimeno** [comment]
@goto100, yeah, I can reproduce the error. For a fix we'll need to bump the `cron-parser` dependency, but for the moment that won't be possible until https://github.com/node-schedule/node-schedule/pull/316 lands

**Comment by santigimeno** [comment]
I'm pretty sure this is fixed by https://github.com/node-schedule/node-schedule/commit/519917bc8138ebc9a8ad19641a02fbaec89ff69d and released in `1.2.2`. Feel free to re-open if it's still an issue. Thanks!

**Comment by mariohmol** [comment]
I'm having a similar issue with '* */1 * * * *' , it runs a lot at same time! version 1.3.0

**Comment by ivanm376** [comment]
@mariohmol its runs every second, change  **'* */1 * * * *'** to **'0 */1 * * * *'** instead

**Comment by mariohmol** [comment]
I found out my issue: https://github.com/node-schedule/node-schedule/issues/263#issuecomment-406616377

thanks
