### ISSUE TITLE
async/await support

### ISSUE THREAD

**Issue by damianobarbati** [node-schedule/node-schedule#337]
What about async/await support? It's 2017 guys! :)

```
//every second jobs
scheduler.scheduleJob('* * * * * *', async () => {
   await whatever(); //2017 is here, yay!
});
```

**Comment by santigimeno** [comment]
I'm not using `async/await` myself but of course PR's are welcome :)

**Comment by damianobarbati** [comment]
Then you'll be using generators or promises: what about them? :)

**Comment by santigimeno** [comment]
Not really, I love good old callbacks :)
Jokes aside, I'd **love** adding support for async/await or whatever other async mechanism that's used, but not being a user myself makes unlikely that I add that support myself. Of course I'll happily merge any PR that adds it.

**Comment by santigimeno** [comment]
And when I say I, I mean me or anyone of the module maintainers.

**Comment by damianobarbati** [comment]
> Not really, I love good old callbacks 

God may have mercy on you 😂
Got it, I'll try to PR this. Thanks!

**Comment by victor0801x** [comment]
@damianobarbati  async function  support on node > =7.6
I have already use this method like this

```
let testJob = schedule.scheduleJob(testRule1, myAsyncCB);
async function myAsyncCB ()  {
  try {
    await myAsyncWork();
  } catch (e) {
    console.error(e);
  }
}
function myAsyncWork() {
  return new Promise((resolve, reject)=>{
    // do your async work...
    if (err)
      reject(err);
    resolve(xxx);
  });
}
```
is that same as ?
```
schedule.scheduleJob(testRule1, async()=>{
  try {
    await asyncWork();
  } catch(e) {
  }
});
```
for now it work well for me

**Comment by damianobarbati** [comment]
wow @victor0801x is correct: I didn't even try but the scheduleJob is already resolving promises if they are returned.
Closing this, thanks!

**Comment by victor0801x** [comment]
scheduleJob is use old style callback function, but you can pass async function as cb.
I think schedulejob register event, so it doesn't need return new Promise

**Comment by rustanacexd** [comment]
works perfectly fine.  here is my code 

````/**
 * start of the script
 * @function run
 */
const run = async() => {
  try {
    await setupTDAccessToken();
    schedule.scheduleJob('*/2 * * * *', getWorklogs);
    
  } catch (error) {
    if (error.response) {
      // The request was made, but the server responded with a status code that falls
      // out of the range of 2xx
      // log(error.response.data);
      console.log('Data: ',error.response.data);
      console.log('Status: ', error.response.status);
      console.log('Headers:', error.response.headers);
    } else {
      // Something happened in setting up the request that triggered an Error
      log('Error', error.message);
    }
  }
};


run();```

**Comment by xianxingg** [comment]
When i wrote a test on `await sleep`
```javascript
var job = new schedule.Job(async function () {
  console.log(Date.now());
  await (ms => new Promise(resolve, setTimeout(resolve, ms)))(1000);
  console.log(Date.now());
});
job.schedule(new Date(Date.now() + 3000));
clock.tick(4150);
```
i got this:
```
3000
1515561822159
```
but i was expecting the result of
```
3000
4000
```
it seems that the await process blocked the fakeTimer.
Any idea, or should this be a sinon issue?

**Comment by zoneccc** [comment]
> When i wrote a test on `await sleep`
> 
> ```js
> var job = new schedule.Job(async function () {
>   console.log(Date.now());
>   await (ms => new Promise(resolve, setTimeout(resolve, ms)))(1000);
>   console.log(Date.now());
> });
> job.schedule(new Date(Date.now() + 3000));
> clock.tick(4150);
> ```
> 
> i got this:
> 
> ```
> 3000
> 1515561822159
> ```
> 
> but i was expecting the result of
> 
> ```
> 3000
> 4000
> ```
> 
> it seems that the await process blocked the fakeTimer.
> Any idea, or should this be a sinon issue?



> When i wrote a test on `await sleep`
> 
> ```js
> var job = new schedule.Job(async function () {
>   console.log(Date.now());
>   await (ms => new Promise(resolve, setTimeout(resolve, ms)))(1000);
>   console.log(Date.now());
> });
> job.schedule(new Date(Date.now() + 3000));
> clock.tick(4150);
> ```
> 
> i got this:
> 
> ```
> 3000
> 1515561822159
> ```
> 
> but i was expecting the result of
> 
> ```
> 3000
> 4000
> ```
> 
> it seems that the await process blocked the fakeTimer.
> Any idea, or should this be a sinon issue?

I have the same questions as you.
