### ISSUE TITLE
Running a job every X seconds does not work

### ISSUE THREAD

**Issue by ashwanikumar04** [node-schedule/node-schedule#339]
Hello:
I am trying to run a job every 20 seconds, but the job runs every minute. I am not sure what am I doing wrong.
I tried following schedules.
 ``` "/20 * * * * *"; ```
 and 
```
 {
           second: 20
  };
```
What is wrong here?

Thanks,
Ashwani

**Comment by ashwanikumar04** [comment]
Got it working 
```
  return {
            second: [19, 39, 59]
        };
```

**Comment by victor0801x** [comment]
You can new a recursiveRule,  and set the rule's sec to [0, 20, 40]
