### ISSUE TITLE
Set timezone config

### ISSUE THREAD

**Issue by hustcer** [node-schedule/node-schedule#34]
Can this module has a way to set the timezone for job schedules?
It seemed that this repo hasn't been update for a long time.

**Comment by bminer** [comment]
There should be an option to rely on UTC time instead.  Just a thought...

**Comment by tejasmanohar** [comment]
Thoughts, @santigimeno ?

**Comment by bminer** [comment]
FYI.. a valid workaround might be to use [node-time](https://github.com/TooTallNate/node-time) and overwriting the `Date` constructor before using node-schedule.

```
var time = require("time");
time.tzset("Australia/Sydney");
Date = time.Date;
```

If the timezone ever needs to be changed on-the-fly, all jobs scheduled with node-schedule can be cancelled and restarted.

**Comment by santigimeno** [comment]
It looks to me like an nice enhancement.
I've seen this has functionality has been asked for a few times already: bug #70 and bug #62. A couple of questions for you:

- What would the API look like?
- Would anyone would be willing to submit a PR?

**Comment by santigimeno** [comment]
WIP here: https://github.com/node-schedule/node-schedule/pull/137
I think we have a bug when DST ends, will look into it

**Comment by Messilimeng** [comment]
如果 有两个任务同时进行 ，那我如何知道 它对应处理的是哪个时间的事件？

**Comment by tejasmanohar** [comment]
>If there are two tasks at the same time, when the event execution, how do I know it is an event which corresponds to the processing time? Can I return the following event in the callback within it?
- @Messilimeng 

https://translate.google.com/#auto/en/如果%20有两个任务同时进行%20，当事件执行的时候%20，我如何知道%20它对应处理的是哪个时间的事件？能够在回调里面返回%20对应%20事件%20吗？

**Comment by Messilimeng** [comment]
Yes, Do you konw how to do this?  @tejasmanohar

**Comment by tejasmanohar** [comment]
@Messilimeng Provide some more details. You can always reference jobs by the variable you assign them to (which you should do, for this reason) assuming it's two distinct variable names.

**Comment by Messilimeng** [comment]
When running the program, the program will generate batch for many tasks, JS for (VaR key in obj) {}, in the callback procedure when I don't know which task is completed.
![Uploading F5{@CF89HF4}%25ZRF%OD81.png…]()

**Comment by Messilimeng** [comment]
如果 我用for 循环 生成了 很多的 任务 。但是 我想取消其中的某个任务 ，那我该怎么写呢。

**Comment by tejasmanohar** [comment]
If they're generated on a schedule, you can grab the jobs from that. Else, it's a bit open-ended.

cc @santigimeno

**Comment by tejasmanohar** [comment]
@Messilimeng If possible, please write your responses in English. You can always use Google Translate or a similar service :)

**Comment by Messilimeng** [comment]
can u tell me how to grab the jobs from the schedule?

or give me some examples！thx!

**Comment by santigimeno** [comment]
@Messilimeng 
```
var schedule = require('schedule');

var first = schedule.scheduleJob('First', new Date(Date.now() + 1000000), function() {
});

var second = schedule.scheduleJob('Second', new Date(Date.now() + 1000000), function() {
});

var third = schedule.scheduleJob('Third', new Date(Date.now() + 1000000), function() {
});


console.log('You can cancel the job by using the Job returned by scheduleJob');
first.cancel();

console.log('Or cancelling the Job using cancelJob and the job name');
schedule.cancelJob('Second');

console.log('Or accessing the job using scheduledJobs');
schedule.scheduledJobs['Third'].cancel();

console.log(schedule.scheduledJobs);
console.log('There are no scheduled jobs left');
```
And please, the next time don't use an existing issue to ask non related questions, open a new issue for that. Thanks!

**Comment by tejasmanohar** [comment]
#217

**Comment by damianobarbati** [comment]
+1

**Comment by senorcodecat** [comment]
+1
