### ISSUE TITLE
Is there any way to obtain the first date value when scheduleJob() is used?

### ISSUE THREAD

**Issue by komplexb** [node-schedule/node-schedule#342]
> Note that jobs are scheduled the first time immediately, so if you create a job using the scheduleJob() convenience method, you'll miss the first scheduled event. Also note that canceled is the single-L American spelling. - [Jobs and Scheduling](https://github.com/node-schedule/node-schedule#jobs-and-scheduling)

I need to get the first date, is there a work around?

**Comment by santigimeno** [comment]
@komplexb does calling `job.nextInvocation()` work for you?

**Comment by komplexb** [comment]
@santigimeno wow, that worked. Was that in docs somewhere and I missed it?

**Comment by santigimeno** [comment]
@komplexb glad it worked for you. Unfortunately it's not in the docs. Docs are not in good shape and contributions are always welcome.
