### ISSUE TITLE
5 digit rule cron is broken

### ISSUE THREAD

**Issue by git0rhero** [node-schedule/node-schedule#344]
5 digit rule is broken (used to work):

```
var schedule = require('node-schedule');

var j0 = schedule.scheduleJob('* * * * * *', function(){
  console.log("6 "+Date.now());
});

var j1 = schedule.scheduleJob('* * * * *', function(){
  console.log("5 "+Date.now());
});
```
Spams 6's, rarely logs a 5.

**Comment by santigimeno** [comment]
@git0rhero 6 digit rule should execute every second, 5 digit every minute. It's that what you're seeing?

**Comment by git0rhero** [comment]
@santigimeno Yes that makes sense! No idea where I lost that last * when I used 6 digits before. Guess you can delete this issue, sorry. Now I see the readme indicates seconds as optional. Wasn't too obvious to me.

**Comment by santigimeno** [comment]
@git0rhero no problem :)
