### ISSUE TITLE
.. all events fire at every schedule, all schedules repeat ?

### ISSUE THREAD

**Issue by ericblade** [node-schedule/node-schedule#349]
Maybe I'm not entirely understanding exactly what is supposed to be going on with this library, so asking here.

When I schedule an event using 
    scheduleJob(new Date(dateStamp), () => { console.log('*** running job'); });

If the given dateStamp is in 1 minute from now, it runs the log in 1 minute. It then runs the log every 1 minute.

If I schedule two events, using the same syntax, but 1 minute and 5 minutes from now, I get the log twice when it fires in 1 minute, and twice when it fires in 2 minutes, twice when it fires in 3 minutes, twice when it fires in 4 minutes, and 4 times when it fires in 5 minutes.

How can I prevent it from a- repeatedly firing the same job over and over (i want these to schedule one time), and b- firing every job at every scheduled interval?  Is this how it's *intended* to work?

If that's not possible, anyone know of a library that does do that?  I basically want to schedule a bunch of 1-off things to occur at given date stamps.

**Comment by santigimeno** [comment]
@ericblade what you describe looks like a bug to me. If you schedule on a specific date, it should only fire once. I'll look into it. Thanks!

**Comment by santigimeno** [comment]
@ericblade I've tested with this code and works correctly (it fires only once)

```js
'use strict';

const schedule = require('node-schedule');

console.log(new Date());
const now = Date.now();
const one_min = new Date(now + 60000);
schedule.scheduleJob(one_min, () => {
  console.log(new Date());
});
```

Can you provide a test case that fails for you? Thanks!

**Comment by ericblade** [comment]
ok .. if/when i get a few minutes, i will see if I can build something completely outside of my other code, that demonstrates .. it seemed really odd to me :)  but the above line was literally what I tried, just to see if it was working correctly.  The source of "dateStamp" is an input from another piece of the program, which I replaced with literally the following:

````
const now = Date.now();
const targetTime = parseInt(dateStamp, 10);
setTimeout(() => { console.log('**** Firing event'); }, targetTime - now);
````

oh, i just received yours, i'll give that a quick spin and see what happens.  (i do notice one difference here, is that I threw in a parseInt(), just in case it's a string when it comes in.. i wonder if that might cause a freak out)

**Comment by ericblade** [comment]
Thanks for the attention, Santiago.  It's looking pretty clearly like I did something really really wrong somewhere, and I don't understand what.  If I was sending new Date() a string, then i'd get back "Invalid Date", which i have no idea what the effect of passing the string "Invalid Date" to scheduleJob() would be.  

Anyway, I'll close this until / unless I find something that's triggering it. Thanks!
