### ISSUE TITLE
The schedule expression */8 * * * * does not work as expected.

### ISSUE THREAD

**Issue by pushpender** [node-schedule/node-schedule#350]
*/8 * * * * It executes every 8 mins starting from 0th min, 8th, 16th and so on till 56th min. At the end of the hour, it again starts from 0th minute and not from 64th (or 4th) min.
Is it the intended behavior? If yes, then how do I execute a job every 8th min.?

**Comment by santigimeno** [comment]
Yes, it's the intended behavior. For what you need I think using `setInterval()` could do it.

**Comment by pushpender** [comment]
Using `setInterval()` is not a solution. I have a list of schedule expression that I read from a JSON and based on schedule expression (for eg. */8 * * * *), it is not efficient to detect whether to use node-schedule or `setInterval()`.

**Comment by guymcswain** [comment]
I've used node-schedule for some time now but just ran into this.  It's not a problem to have such a limitation but it should be documented.  For example I've been using `'15 5 2-30/2 * *'` and it work fine for every even day of the month.  Where does the limitation begin?   Day intervals, ok.  Hour intervals, ?  Minute interval, not ok.

**Comment by kibertoad** [comment]
As per official documentation, "While you can easily bend it to your will, if you only want to do something like
"run this function every 5 minutes", [toad-scheduler](https://github.com/kibertoad/toad-scheduler) would be a better choice."
