### ISSUE TITLE
定时不起作用

### ISSUE THREAD

**Issue by jihadwk** [node-schedule/node-schedule#354]
schedule.scheduleJob('0 0 11 1/2 * ?',function(){
//每隔2天11点执行
})

**Comment by victor0801x** [comment]
please ask in English, thanks
盡量使用英文提問, 通常才會有人回答

'0 11 */2 * *'

**Comment by liufengsoft** [comment]
please try "0 0 11 */2 * *"

**Comment by santigimeno** [comment]
No follow up. Closing it.
