### ISSUE TITLE
how to set time range

### ISSUE THREAD

**Issue by RifeWang** [node-schedule/node-schedule#355]
If i want to do the same thing  every 3 min at 09:00--11:30 , 13:30--15:30 every day , how to set time range?

**Comment by victor0801x** [comment]
startJob: */3 9 * * *
cancleJob: 30 11 * * *

**Comment by RifeWang** [comment]
@victor0801x
```
let startTime = '* 9 * * *';
let endTime = '30 11 * * *';
var j = schedule.scheduleJob({ start: startTime, end: endTime, rule: ' */3 * * * *' }, function(){
  console.log('Time for tea!');
});
```
 Is it correct ?

**Comment by victor0801x** [comment]
maybe you can do like
`
const dateFns = require('date-fns');
let routinJob = {};
let regiterJob = schedule.scheduleJob('30 8 * * *', () => {
    let year = parseInt(dateFns.format(new Date(), 'YYYY'));
    let month = parseInt(dateFns.format(new Date(), 'MM'));
    let day = parseInt(dateFns.format(new Date(), 'DD'));
    let timeConfig = {
        start: new Date(year, month, day, 9, 0, 0),
        end: new Date(year, month, day, 13, 30, 0),
        rule: '*/3 * * * *',
    };
    routinJob = schedule.scheduleJob(timeConfig, yourRoutinFuncion);
});`

**Comment by victor0801x** [comment]
@RifeWang sorry, my bad. you can use webAPI to set time like this: 
`let _sTime = new Date();`
`_sTime.setHours(9);`
`_sTime.setMinutes(0);`
`let startTime = new Date(_sTime.getTime());`
