### ISSUE TITLE
Is there a method to list all the existing schedule jobs?

### ISSUE THREAD

**Issue by anroopak** [node-schedule/node-schedule#360]
Is there a method to list all the existing schedule jobs?

**Comment by santigimeno** [comment]
@anroopak does [`scheduledJobs`](https://github.com/node-schedule/node-schedule/blob/master/lib/schedule.js#L648) works for you?

**Comment by santigimeno** [comment]
No follow up. Closing it.

**Comment by SheaBelsky** [comment]
@santigimeno Can `scheduledJobs` be added to the README? I think it's an important piece of documentation for people who may need to manipulate or examine jobs scheduled for the future.
