### ISSUE TITLE
The schedule expression 0/5 * * * * * does not work as expected.

### ISSUE THREAD

**Issue by David2685** [node-schedule/node-schedule#361]
I want it to work every five second.

the code is here:

var test = schedule.scheduleJob('/5 * * * * *', function(){
    console.log(''+new Date());
});

the result is here:

Sat Jun 10 2017 10:05:00 GMT+0800 (CST)
Sat Jun 10 2017 10:06:00 GMT+0800 (CST)
Sat Jun 10 2017 10:07:00 GMT+0800 (CST)
Sat Jun 10 2017 10:08:00 GMT+0800 (CST)
Sat Jun 10 2017 10:09:00 GMT+0800 (CST)
Sat Jun 10 2017 10:10:00 GMT+0800 (CST)

it worked every minute

**Comment by eaconner** [comment]
You are missing a `*` before `/5`.
```
var test = schedule.scheduleJob('*/5 * * * * *', function(){
  console.log(''+new Date());
});
```

**Comment by luchillo17** [comment]
It's as @eaconner says, it's a matter of syntax, `* * * * * *` will run every second, so if you split the second part with `*/5` it will run every 5 seconds.

This issue was about lack of understanding of the recurrence rule, and can be closed now.

**Comment by santigimeno** [comment]
Closing then. Feel free to re-open if it's still an issue.
