### ISSUE TITLE
Not able to run Mocha tests with node-schedule.

### ISSUE THREAD

**Issue by manikumar446** [node-schedule/node-schedule#364]
I've setup a suite of tests in mocha using Sinon and Chai.
What I'm aiming for is that the tests will run daily and then email the results to my team. 
So I installed below npm modules,
1. node-schedule: To run tests daily
2. mocha-runner-reporter: To send the test report as email.
The tests are all running and sending email as expected only first time. From second time on wards it's not running the tests and sending email. I have attached the sample project as well.
i'd appreciate any suggestions.
[Sample code.zip](https://github.com/node-schedule/node-schedule/files/1077573/Sample.code.zip)

**Comment by rynobax** [comment]
I checked the code and node-schedule is correctly firing the runReportAndSendEmail function.  Seems like it is a bug with mocha-runner-reporter or your test code.

**Comment by manikumar446** [comment]
I found work around for this issue. [Check it here](https://github.com/mochajs/mocha/issues/2887)

**Comment by santigimeno** [comment]
@manikumar446  thanks for following up. Closing this then. Feel free to re-open if it's still an issue
