### ISSUE TITLE
ReferenceError: setImmediate is not defined

### ISSUE THREAD

**Issue by phongdangthanh** [node-schedule/node-schedule#365]
Hi, 

I have used a node-schedule in my project. When I set 30 seconds to get the data from server site. Sometimes I got the error message as below:

**core.es5.js:1085 ERROR ReferenceError: setImmediate is not defined
    at runOnDate (schedule.js:497)
    at prepareNextInvocation (schedule.js:526)
    at currentInvocationFinished (schedule.js:551)
    at schedule.js:527
    at ZoneDelegate.webpackJsonp.1743.ZoneDelegate.invokeTask (zone.js:424)
    at Object.onInvokeTask (core.es5.js:4136)
    at ZoneDelegate.webpackJsonp.1743.ZoneDelegate.invokeTask (zone.js:423)
    at Zone.webpackJsonp.1743.Zone.runTask (zone.js:191)
    at ZoneTask.invoke (zone.js:486)
    at timer (zone.js:1512)**

Here are my code:

```
let schedule: any = require('node-schedule');
...
ngAfterViewInit() {
      this.scheduleMedia = schedule.scheduleJob("*/30 * * * * *", () => {
      let id = +self.activeRoute.snapshot.paramMap.get("id");
      if (id > 0) {
        self.service.getCollects(id, { sort: "created desc", top: 1, filter: `incomingMediaId ne null` }).subscribe(res => {
          let dataResult = res as GridDataResult;
          if (!self.isNullOrEmpty(dataResult) && !self.isNullOrEmpty(dataResult.data) && dataResult.data.length > 0) {
            const item = dataResult.data[0];
            self.key = `se-collects-lastest-${id}`;
            if (self.isNullOrEmpty(localStorage.getItem(self.key))) {
              localStorage.setItem(self.key, item.incomingMediaId);
            }
            else {
              let incomingMediaId: number = parseFloat(localStorage.getItem(self.key) || "0");
              if (incomingMediaId < item.incomingMediaId) {
                incomingMediaId = item.incomingMediaId;
                localStorage.removeItem(self.key);
                localStorage.setItem(self.key, incomingMediaId.toString());
                self.snackBar.open('New Media Received.', 'Click to display media received.', {
                  duration: 10000,
                }).onAction().subscribe(() => {
                  self.router.navigate([`/devices/device/${id}/collects/${incomingMediaId}`]);
                });
              }
            }
          }
        });
      }
    });
}
```
Thanks for help.

**Comment by rynobax** [comment]
Is this code running in a browser?  This library is intended to be run in the context of Node.  I would guess the error is caused because the browser does not support [setImmediate](https://developer.mozilla.org/en-US/docs/Web/API/Window/setImmediate).   If you just want to call a function every 30 seconds, you can use [setInterval](https://www.w3schools.com/jsref/met_win_setinterval.asp).

**Comment by santigimeno** [comment]
No follow up. Closing it. Feel free to reopen if you need something else to discuss
