### ISSUE TITLE
Firing job one time

### ISSUE THREAD

**Issue by kenanchristian** [node-schedule/node-schedule#368]
Hi, what I want to achieve is delaying the task 30 min after it's called. Is this code snippet a good way of doing it?

```js
var schedule = require("node-schedule");

let startTime = new Date(Date.now + 1800000);

let j = schedule.scheduleJob({start: startTime, rule: '*/1 * * * * *'},function(){
    console.log("hello");
    j.cancel();
});
```

or there's another way to do it better?

**Comment by santigimeno** [comment]
Maybe I'm missing something but what about using `setTimeout()` directly?

**Comment by kenanchristian** [comment]
@santigimeno I'm afraid I will get `ENOMEM` error when I call `setTimeout()` many times. Or it won't cause that error?

**Comment by santigimeno** [comment]
Does that error exist? TBH it's the first time I've heard about it. How many timers/jobs do you plan to run at the same time?

With this code I've been able to have more than 800K timers setup at the same time
```js
'use strict';

let i = 0;

function launch_timer() {
  setTimeout(() => {}, 1000000000);
  console.log('timeout', ++i);
  setImmediate(() => launch_timer());
}

launch_timer();

```

**Comment by santigimeno** [comment]
Anyway, if you want to use `node-schedule` you can use a `Date` directly. See [this test](https://github.com/node-schedule/node-schedule/blob/master/test/job-test.js#L42-L57) as an example.

**Comment by kenanchristian** [comment]
@santigimeno Yes that error exists, but maybe I'm a bit paranoid. After I've done some research, I think it only happens in child_process.

OK, I've successfully created a schedule with a date like the one from your test, my question is. How can I create multiple jobs, and I want to cancel on of them?

From what I see, the example always assigns the job to a variable then cancel it using a method from that variable, or did I miss something?

**Comment by santigimeno** [comment]
> From what I see, the example always assigns the job to a variable then cancel it using a method from that variable, or did I miss something?

Yes that's correct.

**Comment by santigimeno** [comment]
Closing it. Please reopen if there's anything else that needs to be addressed
