### ISSUE TITLE
Job still fired after .cancel()

### ISSUE THREAD

**Issue by Clbt** [node-schedule/node-schedule#369]
Hello there,

We're having a weird issue with node-schedule.  When having a lot of jobs firing at the same time (a lot = more than 20) and deleting another job one day after it was created, this job is still fired on its due time, every day. 

Here's our process: 
We have three kinds of jobs, and we're saving each of them in an array.  
```javascript
this.scheduler = {
    true: [],
    false: [],
    later: []
};
```
After initializing this array, we process our recurrence rule which is a bit too complicated to show here.
If we don't do anything after that, the reccurrence rule works fine and jobs are fired whenever they're supposed to. 

The issue happens after we've deleted the job (if we delete it one day or more after its creation).

Here's the way we're deleting our jobs:
```javascript
deleteScheduledJobs = function() {
	for (let laterJob of this.scheduler.later) {
		if (laterJob != null) {
			laterJob.cancel();
		}
	}
	for (let trueJob of this.scheduler.true) {
		if (trueJob != null) {
			trueJob.cancel();
		}
	}
	for (let falseJob of this.scheduler.false) {
		if (falseJob != null) {
			falseJob.cancel();
		}
	}

this.scheduler = {
		true: [],
		false: [],
		later: []
	};
```
When looping on `schedule.scheduleJobs` and listing pending invokations before canceling, we have this:
```json
JOB=<Anonymous Job 97> - PENDING INVOCATIONS=[{"fireDate":"2017-05-31T08:00:00.446Z","recurrenceRule":{"recurs":true,"year":null,"month":null,"date":null,"dayOfWeek":null,"hour":10,"minute":0,"second":0}}]
JOB=<Anonymous Job 98> - PENDING INVOCATIONS=[{"fireDate":"2017-05-31T08:10:00.447Z","recurrenceRule":{"recurs":true,"year":null,"month":null,"date":null,"dayOfWeek":null,"hour":10,"minute":10,"second":0}}]
```
After canceling those jobs, they don't appear in `schedule.scheduledJobs` and when doing something like `myJob.pendingInvocations()` the result is empty. As it should be. **However, the job is still fired at the correct time even though it's been cancelled**. And we know it's been fired because the callback is fired.

We have absolutely no idea of where the issue is coming from or what we may have done wrong. It seems wer'e canceling jobs properly. 

Is there any kind of stress issue on node-schedule that we're not aware of? 
Is there any way to see what could be firing our callback if not the jobs?

Thank you, we'll appreciate any kind of help!

**Comment by santigimeno** [comment]
Thanks for the detailed report. I can't seen anything obviously wrong with what you're doing. A reduced test case could be of great help, though I understand it's not going to be easy.

> Is there any kind of stress issue on node-schedule that we're not aware of?

No, that I can remember.

> Is there any way to see what could be firing our callback if not the jobs?

You could always add logs to the library code. It's not that complicated and could shed some light. Also you could add a `console.trace()` to the callback to see who's calling that.

**Comment by Clbt** [comment]
Hi, thanks for the answer!

> A reduced test case could be of great help, though I understand it's not going to be easy.

We've tried putting in place a test case using `lolex` in order to fake time passing, with the `clock.tick() ` function, however we aren't able to reproduce. 

We'll try putting in place a reduced test case in the following week so that you can get a deeper understanding on this issue. As you said, it's not going to be easy and we're not sure to succeed. As time faking doesn't work for our issue, this test case would probably require to wait one day as in original description of the issue. 

> You could always add logs to the library code. It's not that complicated and could shed some light. Also you could add a console.trace() to the callback to see who's calling that. 

 
With `console.trace()` in our code, we saw that the callback was called by `Job.invoke() `function. By adding `this.name logs` in this function, we saw that it was our jobs previously canceled (id 428 & 427, no longer listed when calling `schedule.scheduledJobs`) that were firing the callback. 

```javascript
Job.prototype.invoke() - name=<Anonymous Job 428>
Job.prototype.invoke() - name=<Anonymous Job 427>
```
Before canceling, when calling `schedule.scheduledJobs` we had : 
```javascript
'<Anonymous Job 427>':
   Job {
     job: [Function: bound ],
     callback: false,
     name: '<Anonymous Job 427>',
     trackInvocation: [Function],
     stopTrackingInvocation: [Function],
     triggeredJobs: [Function],
     setTriggeredJobs: [Function],
     cancel: [Function],
     cancelNext: [Function],
     reschedule: [Function],
     nextInvocation: [Function],
     pendingInvocations: [Function] },
  '<Anonymous Job 428>':
   Job {
     job: [Function: bound ],
     callback: false,
     name: '<Anonymous Job 428>',
     trackInvocation: [Function],
     stopTrackingInvocation: [Function],
     triggeredJobs: [Function],
     setTriggeredJobs: [Function],
     cancel: [Function],
     cancelNext: [Function],
     reschedule: [Function],
     nextInvocation: [Function],
     pendingInvocations: [Function] }
```



Is it possible that something is wrong with the `cancel()` function and the job still exists outside of the `schedule.scheduledJobs`?

**Comment by goto100** [comment]
I have this issue too, but I don't have any clue about why this happens either.

after job canceled, the job has deleted in `scheduledJobs`, but still fires.

**Comment by nnoto** [comment]
I am also experiencing this issue with cancelJobs() but cannot seem to determine the exact criteria for reproduction. The call seems to be successful, and the job no longer appears in scheduledJobs, but the job still runs. Has anyone determined a solution for this issue?

**Comment by santigimeno** [comment]
I'm sorry you're experiencing this issue but we would need a reproducible test case to advance on its resolution.

**Comment by nnoto** [comment]
I was finally able to reproduce this issue fairly consistently with this test. 
1. 10000 jobs were scheduled to run every 10 seconds
2. All jobs are cancelled after 20 seconds
3. More often than not, at least one job will continue running, despite witnessing a successful cancellation in the logs. I've ran it a few times where none of the jobs continued running, but on the majority of runs, at least one job continues to get scheduled. 
4. nscheduler.scheduledJobs begins printing after all jobs have been cancelled. It returns an empty object in the scenario where a cancelled job is still getting scheduled

```
const nscheduler = require('node-schedule');

let name = 'testSched';
let flag = false;

for (let i = 0; i < 10000; i++) {
  let schedName = name + i;
  nscheduler.scheduleJob(schedName, '*/10 * * * * *', function () {
      console.log(schedName + ' ran successfully');
      if (flag) {
        console.log(JSON.stringify(nscheduler.scheduledJobs));

      }

  });
}

setTimeout(function() {
  for (let i = 0; i < 10000; i++) {
    let schedName = name + i;
    if (nscheduler.cancelJob(schedName) === false) {
      console.log('Schedule ' + schedName + ' not currently active.');
    } else {
      console.log('Schedule ' + schedName + ' removed from scheduler.');
    }
  }
  flag = true;
}, 20000)
```

**Comment by santigimeno** [comment]
@wux5 sounds about right. PR is welcome. Thanks!!

**Comment by wux5** [comment]
The issue happened with canceling jobs that are delayed and scheduled with setImmediate(), which didn't set timerID to the pending invocation.

In our case we want to cancel any pending invocations no matter if it's scheduled to happen in future or should happen in the past but delayed due to other jobs. So our fix is simply replacing the setImmediate() with setTimeout(..., 0) and return a timerID anyways. (we could use "return setImmediate(...)" and call clearImmediate() in cancel() function, please let me know if you want me to change it to this way).

A PR was created at: https://github.com/node-schedule/node-schedule/pull/379
