### ISSUE TITLE
Job runs 2 or 3 times instead of 1

### ISSUE THREAD

**Issue by Benny739** [node-schedule/node-schedule#370]
I have a job, setup, to run every night, but in the end, the job runs 2 or 3 times every night.
I call this function once in my index.ts.
`
    runEveryNight(fct: () => void): void {
        cron.scheduleJob({ hour: 4, minute: 19, second: 5 }, () => {
            console.log('Running Once a Night');
            fct();
        });
    }
`
This night the job ran at 1500862745797, 1500862745825 and 1500862745832.
Have I setup anything wrong, or is there a bug causing this?

**Comment by havenbarnes** [comment]
@Benny739 Not sure if this applies to your situation, but this bug appeared for me in situations where you create jobs with the same 'unique' name, perhaps while trying to edit the rules of a job. In this case, once the job actually fires, it will run the same amount of times that you tried to edit this same job.

**Comment by steven-supersolid** [comment]
We are also experiencing duplicate jobs since upgrading from 1.2.0 to 1.2.3

Will try and investigate further but it's hard to pin down for us as seems to happen randomly.

```
const schedule = require('node-schedule');

let rule = new schedule.RecurrenceRule();
rule.minute = new schedule.Range(0, 60, 6);

schedule.scheduleJob(rule, function() {
	...
});
```

**Comment by mostman1043** [comment]
This is absolutely a regression post `1.2.0` - We use node-scheduler in many places and had never seen this prior to moving beyond `1.2.0`; rolling back to that version resolves the issue. There are very few changes between now and then, so finding the root cause shouldn't be too difficult. Until then, if you happen across this on a Google search, just lock your version number.

**Comment by santigimeno** [comment]
Okay. It there's a regression, a reduced test case would really help. Running `git bisect` would also help!!

**Comment by santigimeno** [comment]
@Benny739 @steven-supersolid @mostman1043 can you check if https://github.com/node-schedule/node-schedule/pull/396 fixes the issue for you? Thanks!

**Comment by steven-supersolid** [comment]
I wonder if #379 might actually fix it?
