### ISSUE TITLE
Option to return "nextFireDate" for a Job

### ISSUE THREAD

**Issue by Apollon77** [node-schedule/node-schedule#371]
Hi,

I use cron schedules in some places. Many of them are dynamically defined based on a weekly time matrix when thinks should happen. (e.g. Mo at 9:30, Tue at 12:30 and such). So after one action is completed it searches the next and set a schedule for this. For display purposes it would be great to have an option to get the Daten of the next fire planned on the schedule for this job.

so a method like

getNextTriggerDate() 

which returns a Date object would be great.

**Comment by santigimeno** [comment]
@Apollon77, I think that's already implemented. Does `job.nextInvocation()` work for you?

**Comment by Apollon77** [comment]
Cool, you should document that :-)
I test it currently ... had problems in the past weth scheduled jobs for the next day ... so will give another feedback later today :-)

**Comment by santigimeno** [comment]
> Cool, you should document that :-)

You're right. PR are always welcome! :)

**Comment by Apollon77** [comment]
will come later

**Comment by Apollon77** [comment]
Yes, works well.

This issue should close automatically when you merge the PR :-)

**Comment by santigimeno** [comment]
Fixed by https://github.com/node-schedule/node-schedule/pull/372
