### ISSUE TITLE
Dynamic scheduling for GET Requests

### ISSUE THREAD

**Issue by gragra100** [node-schedule/node-schedule#373]
I need some GET requests to run on a specific scheduling which is dynamic and may change later, eg every 2 minutes by default. Now, in the response data I get the scheduling for next time, eg 3 minutes. So I'm trying to find a way to change the scheduling of a running cron.
Is it possible with this module?

Thanks.

**Comment by rynobax** [comment]
It should be possible.  However, if all you want is to run some code every X minutes, [setTimeout()](https://www.w3schools.com/jsref/met_win_settimeout.asp) should be sufficient for your needs.

**Comment by santigimeno** [comment]
No follow up. Closing it. Feel free to reopen though
