### ISSUE TITLE
npm version of the module does not match the github

### ISSUE THREAD

**Issue by articobandurini** [node-schedule/node-schedule#374]
Version number is the same here and on npm: 1.2.3
However, using module installed from npm, I stumbled upon an issue with unsupported timezone parameter.
After investigation is turned out that there's a bug on line 193 of file schedule.js:
tz = spec.tz; has to go before spec = spec.rule; - otherwise id obviously doesn't make sense.
After forking the module and working on pull request proposal to fix the issue, I found out that the issue is not present in the actual github codebase.
It means that npm version of the module in not in sync with github.

**Comment by santigimeno** [comment]
Published as `1.2.4`. Thanks for reporting the issue.
