### ISSUE TITLE
Recurrence rule's property "month" is 0 based

### ISSUE THREAD

**Issue by KingRial** [node-schedule/node-schedule#375]
By reading the documentation it seems that the rules should follow crontab's standards:

> *    *    *    *    *    *
> ┬    ┬    ┬    ┬    ┬    ┬
> │    │    │    │    │    |
> │    │    │    │    │    └ day of week (0 - 7) (0 or 7 is Sun)
> │    │    │    │    └───── month (1 - 12)
> │    │    │    └────────── day of month (1 - 31)
> │    │    └─────────────── hour (0 - 23)
> │    └──────────────────── minute (0 - 59)
> └───────────────────────── second (0 - 59, OPTIONAL)

However the "month" property, to correctly work, should be used as 0 based instead of 1 based.

On August, the current recurrence rule doesn't work:
```
{
        "month": 8,
        "second": 0,
        "minute": 8,
        "hour": 11
}
```

Instead the following works correctly:
```
{
        "month": 7,
        "second": 0,
        "minute": 8,
        "hour": 11
}
```

**Comment by santigimeno** [comment]
Yes, it seems more like a documentation issue to me. `RecurrenceRule`s syntax is different from the `cron` notation. In this case, `month` follows the `Date.prototype.setMonth` range. i.e: (0-11)
