### ISSUE TITLE
Question: I wanted to schedule for every x hours and n minutes

### ISSUE THREAD

**Issue by arunkumarpalaniappan** [node-schedule/node-schedule#383]
How do I implement schedule for every x hours and n minutes.

Eg: Schedule for every 2 hr and 13 mins.

**Comment by santigimeno** [comment]
What about using `setInterval()` ?

**Comment by santigimeno** [comment]
Closing as there's no follow up. Please feel free to reopen if you think this is still an issue.

**Comment by arunkumarpalaniappan** [comment]
@santigimeno using `setInterval()` asynchronously can solve this, but It would be better if we have a custom schedule method.

For Example:

Let's say I'm scheduling for every 2 mins, starting from 10:00 am, Once it runs at 10:02,it should reschedule itself to 10:04 like 

`return Schedule.scheduledJobs[id].reschedule({`
`start: newfireDate,`
`end: endDate,`
`rule: rule}, function ({`
`//logic here`
`})`
