### ISSUE TITLE
Quartz format support

### ISSUE THREAD

**Issue by dbrezoev** [node-schedule/node-schedule#384]
Is it possible node-schedule to work with quartz format ? I put this 1 0/1 * 1/1 * ? * cron which is valid quartz cron and it is not working. No error also. 
Thanks in advance

**Comment by dbrezoev** [comment]
Anyone ?

**Comment by santigimeno** [comment]
Only formats supported in [cron-parser](https://github.com/harrisiirak/cron-parser) are supported. By looking at [this issue](https://github.com/harrisiirak/cron-parser/issues/104) it seems that's not the case.

**Comment by santigimeno** [comment]
Of course, feel free to re-open once `cron-parser` adds that support. Thanks
