### ISSUE TITLE
Cron x/y pattern not working as espected

### ISSUE THREAD

**Issue by fabiomor** [node-schedule/node-schedule#385]
Hi,

I noticed that pattern x/y, as every y starting from x is not wotking

According to crontab.guru [this](https://crontab.guru/#0/2_*_*_*_*) pattern should produce:

> “At every 2nd minute from 0 through 59.”

But in the attached code i've noticed a different behavior (applied to seconds for brevity). It triggers just at the very start of every minute insted of every 2 seconds starting from second 0

`var event = schedule.scheduleJob("0/2 * * * * *", function() {
    var dt = dateTime.create();
	console.log("Inserting new data: " + dt.format('Y-m-d H:M:S'));
});
`

Output:

> Inserting new data: 2017-09-13 16:35:00
Inserting new data: 2017-09-13 16:36:00
Inserting new data: 2017-09-13 16:37:00
Inserting new data: 2017-09-13 16:38:00

**Comment by santigimeno** [comment]
This module uses [cron-parser](https://github.com/harrisiirak/cron-parser) for the cron syntax support. Can you check with their latest version if that's an issue and open an issue at their repo. Thanks!

**Comment by fabiomor** [comment]
Thanks man, i'll check it out

**Comment by santigimeno** [comment]
@fabiomor I've been looking into this and TBH after reading the [crontab manual](http://www.manpagez.com/man/5/crontab/) I'm not sure that format is correct:

> **Step values can be used in conjunction with ranges**. Following a range with "/<number>" specifies skips of the number's value through the range. For example, "0-23/2" can be used in the 'hours' field to specify command execution for every other hour (the alternative in the V7 standard is "0,:2,:4,:6,:8,:10,:12,:14,:16,:18,:20,:22"). **Step values are also permitted after an asterisk**, so if specifying a job to be run every two hours, you can use "*/2".

I'm not completely sure that using a value with step values is a valid crontab expression. It seems that only ranges and * are valid. /cc @harrisiirak 

Anyway, for your use case you could always use `0-59/2 * * * * *` and it should work.

**Comment by fabiomor** [comment]
ty man, in fact there was a warning stating that the non standard format. I modified the code according to your suggestion.

Great work btw ;)

**Comment by santigimeno** [comment]
Closing then. Thanks!
