### ISSUE TITLE
Async function inside a job. Error handling.

### ISSUE THREAD

**Issue by adambuczek** [node-schedule/node-schedule#389]
Hi! I find this package very useful. It lets me schedule an action in a docker container which dissolves after the job runs.

I have a problem with error handling inside a job. I pass a curried async `a.bid(o)`. When the promise is rejected the error doesn't get caught. What should I do to make it work?

```js
(async function() {
  let client = new Client(CONF);
  try {
    // client connection, time offset calculation
    let job = new schedule.Job(order.id.toString(), ((o,a) => () => a.bid(o))(order, client));
    // setting up logging
    job.schedule(bidTime);
  } catch (e) {
    eventEmmiter.emit('error', e);
  }
})();
```

**Comment by adambuczek** [comment]
I figured it out.
```js
    let job = new schedule.Job(order.id.toString(), ((o,a) => () => {
      a.bid(o).catch((err) => {eventEmmiter.emit('error', err);})
    })(order, client));
```
I needed to catch it in its context. Is there anything like an `job.on('error')` that would facilitate handling errors inside an actual job?

**Comment by maxym-plotnikov** [comment]
Did You try to use Promise with catch inside job?

**Comment by adambuczek** [comment]
`Client` is a SOAP connection manager. all it's methods are async. That is exactly what I ended up doing.
I hoped for a solution without an additional `catch` but I guess a job has to be treated as self contained.
