### ISSUE TITLE
Rule dayOfMonth

### ISSUE THREAD

**Issue by Tuzizon** [node-schedule/node-schedule#390]
Is there a rule to run a specific day of the month?
For example, every 5th day of every month.
It could function exactly like the dayOfWeek parameter.
would work like a charm!
Thanks

**Comment by ariadnalls** [comment]
54 16 5 * *
“At 16:54 on day-of-month 5.”

**Comment by Tuzizon** [comment]
ty u so much @ariadnalls

**Comment by santigimeno** [comment]
I guess this can be closed. Reopen if the issue is not solved

**Comment by Hamza-Khurshid** [comment]
I want to run and repeat a job on specific days like 08, 11, 27 of every month.
