### ISSUE TITLE
Module not found: Error: Can't resolve './locale'

### ISSUE THREAD

**Issue by Karthikmuthupandi** [node-schedule/node-schedule#391]
Hi All,

Suddenly we are facing the below issue,

Module not found: Error: Can't resolve './locale'

Could you please advise to resolve this issue. 

Thanks,
karthi

**Comment by santigimeno** [comment]
@Karthikmuthupandi can you describe how can I reproduce the issue?

**Comment by Karthikmuthupandi** [comment]
Now its working. please close
