### ISSUE TITLE
How to run a job once a day?

### ISSUE THREAD

**Issue by jonathan68** [node-schedule/node-schedule#400]
Thanks for your library! I am using this library to run a job once a day.
I used this pattern. 
`* * 23 * * *`
But this calls every 23:00:00~23:59:59.
I want to run once a day.
How can I set the pattern?

**Comment by wux5** [comment]
Your cron means every second between 23:00 and 23:59. To run it once a day you'll need to set the cron to 0 0 23 * * *

**Comment by jonathan68** [comment]
Ah, gotcha. Thank you very much!

**Comment by munkhorgil** [comment]
@wux5 It doesn't work when I change my computer date manually to next day of 23:00.
