### ISSUE TITLE
How to run a schedule every 2 hours?

### ISSUE THREAD

**Issue by wagng** [node-schedule/node-schedule#405]
I want to run a schedule every 2 hours.
I tried these 2 patterns. But none of them is working.

```
*0 0 /2 * * *
* * /2 * * *
```

I'd appreciate any help.
Thank you!

**Comment by victor0801x** [comment]
`0 0 */2 * * *` will run every 2 hours after  nearest_hour:00:00
need to specify min and sec

**Comment by Zhou-Bill** [comment]
how about 25 hours ?
