### ISSUE TITLE
Date-based Scheduling runs multiple times

### ISSUE THREAD

**Issue by Shamonshamonsha** [node-schedule/node-schedule#412]
I am trying to set cron-job on fixed date using 

 ```
cronJob = schedule.scheduleJob(new Date(date), function(){
            console.log('The world is going to end today.');
        });
```

Date generated using the following method
```
let date = moment(dateInUTC).format('YYYY-M-DD-H-mm-s').split('-');
        date[1]  = date[1]-1;
        return date.toString();
```

everything works but the crone executes multiple times

Here is the things i can see in console

```
The world is going to end today.
The world is going to end today.
-------
```

**Comment by santigimeno** [comment]
@Shamonshamonsha thanks for the report. Can you print what `new Date(date)` is?

**Comment by Shamonshamonsha** [comment]
Issue resolved its the problem with date string

**Comment by Kmess** [comment]
Hi!

I'm still running into this bug in the latest version (1.3.0) - previously every instance was running at least 5 times per reoccurring rule (only supposed to be running once), I updated it and now it's still at 2.

`   //Setup Cron jobs - 6AM CENTRAL
    var rule = new schedule.RecurrenceRule();
    rule.hour = 12;
    rule.minute = 0;
    var j = schedule.scheduleJob(rule, function() {
        //This is called twice
    });

    var rule = new schedule.RecurrenceRule();
    rule.hour = 12;
    rule.minute = 5;
    var j = schedule.scheduleJob(rule, function() {
        //This is called twice
    });`
