### ISSUE TITLE
Hourly rule running at each minute instead

### ISSUE THREAD

**Issue by fullofcaffeine** [node-schedule/node-schedule#413]
Hi there!

I have the following piece of code:

```js
  scheduler.scheduleJob('0 * * * 1-7', () => console.log('test'))
```

As far as I'm concerned, that should trigger at every hour at minute `0` (see: `https://crontab.guru/#0_*_*_*_*`)

However, on the production server, which is a basic heroku nodejs (`node v9.4.0`) instance, it's triggering the `log` at _every minute_, I just deployed the app and confirmed this. It does work fine locally (`node v8.9.1`) running it at every hour. Does anyone have any clues on why it would it do that? 

Both instances are using node-schedule `v^1.2.0`.

Any insights appreciated.

**Comment by victor0801x** [comment]
'0 * * * * *' it will run every minute at  *:*:00
'0 0 * * * *' it will run every hour at  *:00:00
if you want to run every hour after the program started (*:mm:ss), try 'ss mm * * * *' ?

**Comment by santigimeno** [comment]
@fullofcaffeine can we close the issue now?

**Comment by fullofcaffeine** [comment]
Yes, it was false positive, I checked the code again and the syntax was wrong, indeed. Thanks.
