### ISSUE TITLE
restart, valid?

### ISSUE THREAD

**Issue by LitileXueZha** [node-schedule/node-schedule#414]
I have a problem.If the node process is restarted, scheduleJob will keeping run or be aborted.
Somebody give me a bug about scheduleJob, maybe i restart the node server?

**Comment by santigimeno** [comment]
If the process node is restarted you'll lose all the running jobs.

**Comment by LitileXueZha** [comment]
But how can i save the jobs, writing it to file?

**Comment by LitileXueZha** [comment]
thanks,.I have no idea to query database now when i restart node

**Comment by santigimeno** [comment]
Yes. Storing the jobs in a database seems like a good idea.
