### ISSUE TITLE
Question about existing functionality

### ISSUE THREAD

**Issue by katp4** [node-schedule/node-schedule#415]
Hello,

My jobs need to run on an interval between a start time and an end time so I've chosen to use 

`var j = schedule.scheduleJob({ start: startTime, end: endTime, rule: '*/1 * * * * *' }, function(){
  console.log('Time for tea!');
}); `

However, i don't want my jobs to run again the next day. I want them to only do this scheduler today and then just cancel themselves.  

Is there anyway to achieve the below functionality? if not, could you point me in the right direction? Happy to extend the code myself.

**Comment by santigimeno** [comment]
Hi,
I'm not sure I understand: if you don't want to run the job the next day isn't that exactly what `endTime` is for?

**Comment by katp4** [comment]
I was under the impression that if i set the above, it would run on every minute, between say 9am and 8pm every day due to the fact that there's not date restriction anywhere.  Start and end are just times not dates and rule is a cron expression that just specifies the interval.

**Comment by santigimeno** [comment]
> Start and end are just times not dates and rule is a cron expression that just specifies the interval.

Are you sure about that, I've never used them myself but IIRC `start` and `end` should be dates. See: https://github.com/node-schedule/node-schedule/blob/master/test/start-end-test.js

**Comment by katp4** [comment]
I always assumed that the Date part was discarded and it only Time took into consideration due to the the example and the fact that it focuses only time but fair enough, if that's how it works by default then i'll take it :) 

Will leave my jobs running tonight and verify it tomorrow. 

Thanks for the clarification!

**Comment by santigimeno** [comment]
If you look to the example in the README `start` and `end` are indeed Date's.

I hope it works for you.

Closing this now. Feel free to reopen if there is still an issue.
