### ISSUE TITLE
How can i use in a cluster mode or distribute system?

### ISSUE THREAD

**Issue by lsytj0413** [node-schedule/node-schedule#417]
As the title, if i use node in cluster mode or distribute system, and i use the code blow:
`
schedule.scheduleJob('* * * * * *', function () {
    console.log('run');
});
`
when the time is up, the job will run at all node instance at the same schedule times. my question is how to make just one node run the job?

**Comment by akumar86** [comment]
I am facing the same issue. if I have 4 core cpu then it runs for 4 times.

**Comment by williamknn** [comment]
Same issue here.

**Comment by johnathanmiller** [comment]
I setup a separate node server to handle scheduling/running jobs via api.

**Comment by akumar86** [comment]
Even from APIs, it is running multiple times

**Comment by zhangge3992513** [comment]
if use pm2, you can
pm2.list((err, list)=>{
   if(list[0].pid === process_id){
    }
})

**Comment by williamknn** [comment]
When I tried to setup this solution using `pm2` it was when I've found the solution I was looking for:

```js
var cluster = require('cluster');
if (process.env.NODE_ENV === 'production' && cluster.worker.id === 1)  {
    // exec cron stuff
}
```

So there's no need for using `pm2` only for this purpose.

**Comment by jeffreyjackson** [comment]
@williamknn I tried your solution but without success.  Im running a multiple dyno environment on heroku.

**Comment by awwong1** [comment]
I don't think the scope of node-schedule should handle clustering.
The scheduled tasks need to be persisted in database anyways for when the app restarts and auto scales. Therefore, something like PM doesn't seem like the best fit here (sure, only one worker will run at a time but memory is still scoped to each process).

Using postgresql, I think the best solution is to store the necessary jobs in a table containing an auto increment ID, a timestamp (or cron string), plus some metadata about your task. When the application loads, all scheduled tasks are loaded into the scheduler. Then, when you need to execute a scheduled task, you can use the `pg_advisory_lock*` functions to wrap your task and ensure only one instance of your clustered app executes the scheduled job.

https://www.postgresql.org/docs/9.6/static/explicit-locking.html#ADVISORY-LOCKS

Not sure about other databases or for a pure Node solution.

**Comment by bosscheng** [comment]
Same issue here.
