### ISSUE TITLE
RecurrenceRules get called twice

### ISSUE THREAD

**Issue by Kmess** [node-schedule/node-schedule#419]
Previously there was a bug where RecurrenceRules were getting called multiple times - I was seeing that each function was getting called 5 times. 

Now we have updated to 1.3.0 and are still seeing the functions getting called more than once (instead of 5 times, its only 2 times... but still more than once).

Here's a snippet of the code: 
```
//Setup Cron jobs - 6AM CENTRAL
    var rule = new schedule.RecurrenceRule();
    rule.hour = 12;
    rule.minute = 0;
    var j = schedule.scheduleJob(rule, function() {
        //This is called twice, when it should be called once
    });

   rule = new schedule.RecurrenceRule();
    rule.hour = 12;
    rule.minute = 5;
    var j = schedule.scheduleJob(rule, function() {
         //This is called twice, when it should be called once
    });
```

**Comment by Kmess** [comment]
This was user error on my part. The discord bot would get disconnected and then reconnect every so often. Which then calls these functions again.

**Comment by santigimeno** [comment]
Great you found the issue. I had been trying to reproduce it for a while without any luck
