### ISSUE TITLE
Store jobs in a database / JSON file

### ISSUE THREAD

**Issue by nodesocket** [node-schedule/node-schedule#421]
Is it possible to create jobs at run-time using a JSON file format or even better read from Redis or MongoDB?

**Comment by brooksbecton** [comment]
I know you can't store functions in JSON, but you can store the time the job needs to run in JSON/Redis/Mongo

```js
const schedule = require('node-schedule');

const jobTimes = {
    'oneSeconds': {
        jobTime: { second: 0 },
        run: function () {
            console.log("At 1 Seconds " + Date())
        }
    },
    'fiveSeconds': {
        jobTime: { second: 5 },
        run: function () {
            console.log("At 5 Seconds " + Date())
        }
    }
}

Object.keys(jobTimes).forEach(jobType => {
    const job = jobTimes[jobType];

    const jobRef = schedule.scheduleJob(job.jobTime, function () {
        job.run()
    });
})

```

**Comment by nodesocket** [comment]
@brooksbecton yes, it is ok to define the function logic statically, but I am looking for a way to dynamically create lots of schedules at run-time without having to restart the node process.

```
const a = schedule.scheduleJob({hour: 12, minute: 10, dayOfWeek: 0}, functionLogic);
const b = schedule.scheduleJob({hour: 13, minute: 20, dayOfWeek: 1}, functionLogic);
const c = schedule.scheduleJob({hour: 14, minute: 30, dayOfWeek: 2}, functionLogic);
```

**Comment by alihesari** [comment]
@nodesocket Do you tried this? https://docs.mongodb.com/manual/tutorial/store-javascript-function-on-server/

**Comment by kibertoad** [comment]
As per official documentation: "In case you need durable jobs that persist across restarts and lock system compatible with multi-node deployments, try [agenda](https://github.com/agenda/agenda) or [bree](https://github.com/breejs/bree)."
