### ISSUE TITLE
"*/45 * * * * *"

### ISSUE THREAD

**Issue by tigranmartirosyan** [node-schedule/node-schedule#423]
schedule.scheduleJob("*/45 * * * * *", function() {
        console.log(new Date());
});
it runs at 00 and 45 seconds for every minute.
shouldn't it have been run every 45 seconds?

**Comment by ashishpatel1992** [comment]
Yes you are right, looks like a bug
Here are my results:
```
2018-02-21T09:35:45.001Z
2018-02-21T09:36:00.001Z
2018-02-21T09:36:45.001Z
2018-02-21T09:37:00.003Z
```

**Comment by santigimeno** [comment]
If you think this could be a bug, please open an issue @ https://github.com/harrisiirak/cron-parser. Thanks!

**Comment by santigimeno** [comment]
BTW this doesn't look like a bug to me, but this is how `cron` works. See: https://stackoverflow.com/questions/27412483/how-do-cron-steps-work

**Comment by ashishpatel1992** [comment]
@santigimeno But why it executes two times at 00 and at 45?

**Comment by santigimeno** [comment]
Have you read https://stackoverflow.com/a/27412884/1562178 ?

**Comment by santigimeno** [comment]
Basically it says the step calculation is calculated **inside** the range. In this specific case: * means from 00-59. So it will be executed at 00 and 45 minutes on every hour.

**Comment by ashishpatel1992** [comment]
Aah! Finally, i understood!
So is there any way to avoid that?

**Comment by santigimeno** [comment]
Using `setInterval()` ?

**Comment by santigimeno** [comment]
Anyway, this kind of issues show up from time to time, so if anyone proposes a sane API to implement this kind of functionality I think it could be a nice addition to the library.

**Comment by santigimeno** [comment]
Closing this for the moment. If this is still an issue, please re-open.
