### ISSUE TITLE
cancelNext not working 

### ISSUE THREAD

**Issue by GaneshaThirumurthi** [node-schedule/node-schedule#425]
Attempting to use the cancelNext feature on a reoccurring job, however, it doesn't appear to be cancelling the next invocation. Whether I call j.cancelNext() or j.cancelNext(true) nothing happens. By calling j.cancelNext(false) the entire job stops indefinitely.

```/** Cancel next iteration test */
var rule = new schedule.RecurrenceRule();
rule.second = [new schedule.Range(0, 59)];

var j = schedule.scheduleJob(rule, function(){
  console.log(`Job j ran at: ${new Date()}`);

});

setTimeout(function(){
  console.log('Next invocation without cancellation should be at', j.nextInvocation());
  j.cancelNext(true);
 }, 3000);
```

Output:

```
Job j ran at: Sat Feb 24 2018 14:25:38 GMT-0800 (PST)
Job j ran at: Sat Feb 24 2018 14:25:39 GMT-0800 (PST)
Job j ran at: Sat Feb 24 2018 14:25:40 GMT-0800 (PST)
Next invocation without cancellation should be at 2018-02-24T22:25:41.000Z
Job j ran at: Sat Feb 24 2018 14:25:41 GMT-0800 (PST)
Job j ran at: Sat Feb 24 2018 14:25:42 GMT-0800 (PST)
Job j ran at: Sat Feb 24 2018 14:25:43 GMT-0800 (PST)
Job j ran at: Sat Feb 24 2018 14:25:44 GMT-0800 (PST)

```

**Comment by santigimeno** [comment]
@GaneshaThirumurthi Can you check if https://github.com/node-schedule/node-schedule/pull/432 fixes the issue for you?

**Comment by Freakspot** [comment]
@santigimeno It did for me. However, now I'm not able to easily format it (using moment.js) anymore. Also see #436. A standard Date would make it easier imo.

**Comment by santigimeno** [comment]
Thanks for the feedback. I'll merge it as soon as I can

**Comment by Freakspot** [comment]
Perfect, thanks for the fix!

**Comment by rijnhard** [comment]
Hi 

Not to sound needy but if everything is ok can we get this merged? I'm going to be using this lib and need this functionality

**Comment by jpdurot** [comment]
Hi
I also need this fix. Can it be merged ?
