### ISSUE TITLE
Is there a way to lock a job?

### ISSUE THREAD

**Issue by erickles** [node-schedule/node-schedule#427]
Hello guys,

is there a way to set a job to run just when the previous one is done? In my case, i have a job that runs every 5 seconds and sometimes, some jobs take more than that to finish...

**Comment by GaneshaThirumurthi** [comment]
Erickles, one way to do it might be to have an event fire when the job completes. Catch the event and then call the reschedule method on the job with the current date (plus a small offset so that the date is not historical).

**Comment by santigimeno** [comment]
The solution proposed by @GaneshaThirumurthi  seems like a good idea to me. I'll close the issue for now. Feel free to reopen if you want to discuss it further. Thanks
