### ISSUE TITLE
task is executed over and over again

### ISSUE THREAD

**Issue by salamander-mh** [node-schedule/node-schedule#429]
This my schedule task:
```
function addLinkValidSchedule() {
    schedule.scheduleJob('* 7,20 * * *', async function() {
        detectLinksValid();
    });
}
```
from my log:
![image](https://user-images.githubusercontent.com/16663435/37465133-567cbf16-2895-11e8-8c0f-bd59f6edabdc.png)
When the task finished, it was executed again. it is strange!

**Comment by ycankasal** [comment]
I've this problem too. It's working over and over.

It's too strange.

**Comment by salamander-mh** [comment]
@ycankasal  the format is not correct `* 7,20 * * *` will be executed every minute.
so the format should be `0 7,20 * * *`

**Comment by santigimeno** [comment]
Just to be sure. Is this still an issue?
