### ISSUE TITLE
How to run a job where start time and end time is on different days

### ISSUE THREAD

**Issue by rajkaran** [node-schedule/node-schedule#430]
I have a job which I want to run between 19:00 and 7:00 every night. 

I have tried  `*/2 19-23,0-6 * * *` so far, but job runs between 19:00 to 23:58.

Any help?

**Comment by santigimeno** [comment]
You can set the [StartTime and EndTime](https://github.com/node-schedule/node-schedule#set-starttime-and-endtime) options
