### ISSUE TITLE
Concerning monthly function call

### ISSUE THREAD

**Issue by Tevinthuku** [node-schedule/node-schedule#447]
I just wanted to confirm if this function will be called once a month at 12

```
const schedule = require("node-schedule");

var rule = new schedule.RecurrenceRule();
rule.month = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11];
rule.hour = 12;
rule.minute = 0;

const handleMonthyFunction = () => console.log("Monthly");

var j = schedule.scheduleJob(rule, handleMonthyFunction);
```

**Comment by ftechhelp** [comment]
You can simply handle that with the CRON like method, for example, this will run every 1st day of every month at midnight:

`schedule.scheduleJob('0 0 1 * *', () => {`

` console.log("Monthly")                  `

` });                                                          `

Is a bit cleaner in my  opinion and it will do just what you want.

**Comment by Tevinthuku** [comment]
It does look cleaner . Thank you.
