### ISSUE TITLE
Time Recurrence Rule is not working properly

### ISSUE THREAD

**Issue by Satya2401** [node-schedule/node-schedule#45]
var schedule = require('node-schedule');
var rule = new schedule.RecurrenceRule();
rule.minute = 1;//Here minute is taking as an hour and If you give second, Its taking as //a minute

var j = schedule.scheduleJob(rule, function(){
    console.log('The answer is not working!');

});

**Comment by mrugesh-onehop** [comment]
@mattpat what about every second ?

**Comment by diegofreemind** [comment]
+1
