### ISSUE TITLE
Date scheduler is not working at all

### ISSUE THREAD

**Issue by Satya2401** [node-schedule/node-schedule#46]
var schedule = require('node-schedule');
var date = new Date(2014 11, 21, 5, 30, 0); 

var j = schedule.scheduleJob(date, function(){
    console.log('Today is holy Day.');
});

**Comment by adadgio** [comment]
Should be re-opened, not working at all. Maybe issues with time zones, but the docs do not state anything about time zones.. (?)

**Comment by santigimeno** [comment]
@adadgio can you open a new issue with code that reproduces the issue please? :)

> Maybe issues with time zones, but the docs do not state anything about time zones

There's no timezone support at the moment, but there's a pending [PR](https://github.com/node-schedule/node-schedule/pull/316) that should add that support.
