### ISSUE TITLE
How to launch it

### ISSUE THREAD

**Issue by luminous8** [node-schedule/node-schedule#462]
Hey, 

It may sound like a silly question (it's probably silly but couldn't find any answer in the docs).
How the do I launch it? If I do `node index.js` on a server, do I need to keep the window open? If I quit the script does the cron will be executed as well?

Thanks !

**Comment by jpdurot** [comment]
Hi,

From  the Overview part in the readme file:

`
Note that Node Schedule is designed for in-process scheduling, i.e. scheduled jobs will only fire as long as your script is running, and the schedule will disappear when execution completes. If you need to schedule jobs that will persist even when your script isn't running, consider using actual cron.
`

**Comment by luminous8** [comment]
Pretty clear indeed, I missed this section. Thanks
