### ISSUE TITLE
How to free memory after running schedule function ?

### ISSUE THREAD

**Issue by valterh4ck3r** [node-schedule/node-schedule#476]
How to free memory after running schedule function ?

All times that schedule execute function, the memory was not clearing...

**Comment by rfossella** [comment]
FYI: I added something in my callback to check if the job was done - i.e. no next invocation.  If done, then I cancel the job, thus removing it from memory.
```
var checkJob = (aJob) =>
{
	if (aJob.nextInvocation() == null)
	{
		aJob.cancel();
	}
} 
```
