### ISSUE TITLE
where is the cron config stored on mac?

### ISSUE THREAD

**Issue by StevenWung** [node-schedule/node-schedule#486]
Hi
I used the node-schedule to debug a schedule, but after I shutdown the process, the tasks are still scheduled to run.
I checked the `crontab -l `, nothing found there.
I'm wondering where the scheduling file stored?

I am using Mac.

Thanks

**Comment by andrewsosa** [comment]
See here:

https://github.com/node-schedule/node-schedule/blob/cb5a08d4329f5f328cd094ca072ad7711811ece1/README.md#L35-L38
