### ISSUE TITLE
Firebase Cloud Functions - Long Cron Time

### ISSUE THREAD

**Issue by yuricamara** [node-schedule/node-schedule#487]
Hi,

Does this library work well in CF even with long time, such as days?
I read somewhere that CF can have problems with long cron time.

Thanks!

**Comment by aqualaguna** [comment]
of course the CF is a bad platform to running cronjob. 
**CF has a lifetime of 10 minutes**.
because of its design its not used for long running application.

**Comment by yuricamara** [comment]
Thanks!
