### ISSUE TITLE
Update docs to reflect cron-parser's new support for the # day-of-week character

### ISSUE THREAD

**Issue by DiskImage** [node-schedule/node-schedule#490]
The latest release of the `cron-parser` dependency has added support for the `#` special character.

**Comment by santigimeno** [comment]
@DiskImage do you really need the update? Just saying because it's now defined like this: `"cron-parser": "^2.7.3"` and that should have you covered.

**Comment by DiskImage** [comment]
@santigimeno Thanks, that's an excellent point. What I should have requested, and will edit the issue to reflect, is that the docs need to be updated to reflect the new `#` support.

**Comment by santigimeno** [comment]
:+1: Are you up for a PR? ;)

**Comment by DiskImage** [comment]
Yeah, I don't mind resolving my own issue. 😛
It's only fair since I added the `#` support to `cron-parser`, too

**Comment by DiskImage** [comment]
I might add W later if I'm feeling wild.
