### ISSUE TITLE
Correct way to schedule to run every minute (*/1 * * * * vs * */1 * * * *)

### ISSUE THREAD

**Issue by simonstewart-bridgement** [node-schedule/node-schedule#497]
I understand that the first * is optional for seconds, but why does the following execute every second and not every 1 minute:
* */1 * * * *

Here is a quick reproducible.
```
var schedule = require('node-schedule');

var runEveryMinute = "*/1 * * * *"; // works
//var runEveryMinute = "* */1 * * * *"; // doesn't work. runs every second instead
var j = schedule.scheduleJob(runEveryMinute, function(){
  console.log('tick');
});
```

Quick solution for me is to remove the leading * as we don't require seconds anyway, but I'm curious why it doesn't work with it in place.

**Comment by lacivert** [comment]
I am not sure about this but for "every minute", I would use 

5 stars => "* * * * *" 
or 
0 + 5 stars  => "0 * * * * *" (= whenever "second" shows 0 on the clock)

**Comment by juhana** [comment]
The default value for seconds is `0`, not `*`. So `*/1 * * * *` is equivalent to `0 */1 * * * *`. And like lacivert said, `*/1` is equivalent to `*`.

**Comment by rohitpatil7892** [comment]
can '' * * * * * " stop working after month ?

**Comment by kibertoad** [comment]
As per official documentation: "While you can easily bend it to your will, if you only want to do something like
"run this function every 5 minutes", [toad-scheduler](https://github.com/kibertoad/toad-scheduler) would be a better choice."
