### ISSUE TITLE
 What parameter should I pass to run every day at 5:30 pm?

### ISSUE THREAD

**Issue by cristian-programmer** [node-schedule/node-schedule#502]
Hi good day
What should I set as a parameter if I want my JOB to run every day at 5:30 pm? using RecurrenceRule ?

**Comment by Corbineau** [comment]
try this: 

var rule = new schedule.RecurrenceRule();
rule.hour = 17;
rule.minute = 30;

var j = schedule.scheduleJob(rule, function(){
  console.log('Run job, run!');
});

or

var j = schedule.scheduleJob({hour: 17, minute: 30});

hope that

**Comment by cristian-programmer** [comment]
thank you very much.
