### ISSUE TITLE
Cron should support 7 cells

### ISSUE THREAD

**Issue by shlomo666** [node-schedule/node-schedule#506]
I'm trying to execute every 10 seconds, and I implemented some auto cron generator to do this.
But it seems like my cron string is not supported by this module. 
Here's what is not working:
`*/10 * * * * * *`
Here's what is working (one less *):
`*/10 * * * * *`

From what I understand from cron documentation 7 * should be supported as well.

```
* * * * * * *
| | | | | | |
| | | | | | +-- Year              (range: 1900-3000)
| | | | | +---- Day of the Week   (range: 1-7, 1 standing for Monday)
| | | | +------ Month of the Year (range: 1-12)
| | | +-------- Day of the Month  (range: 1-31)
| | +---------- Hour              (range: 0-23)
| +------------ Minute            (range: 0-59)
+-------------- Second            (range: 0-59)
```

**Comment by santigimeno** [comment]
@shlomo666 we use https://github.com/harrisiirak/cron-parser as the cron library. If you want to ask for new functionality you should ask there first. Thanks!
