### ISSUE TITLE
scheduleJob return null

### ISSUE THREAD

**Issue by campanagerald** [node-schedule/node-schedule#511]
OS: macOS Mojave, Version 10.14
Node: v10.15.0

I tried the example on Date-Based Scheduling.

var schedule = require('node-schedule');
var date = new Date(2012, 11, 21, 5, 30, 0);
 
var j = schedule.scheduleJob(date, function(){
  console.log('The world is going to end today.');
});

console.log(j) // null

when logged "j" is null.

**Comment by Yetix33** [comment]
I am having the exact same problem on windows using the object literal based scheduling

**Comment by benjivm** [comment]
I am also seeing this behavior.

**Comment by terwinsamsung** [comment]
@campanagerald maybe because you scheduled something in the past?

**Comment by campanagerald** [comment]
@terwinsamsung Yah, you are correct. What I did is I scheduled ahead from the current time. I am closing this issue. Thanks!

**Comment by yorickdevries** [comment]
Sorry for opening this issue again a year after, but shouldn't this behaviour be added in the documentation to prevent future confusion?

**Comment by SemperFortis** [comment]
Just had the same issue, and I honestly think it should. It seems like due to poor documentation of these edge cases are causing a lot of bugs when trying to even debug the issue.
