### ISSUE TITLE
How to access specific job instance in a large queue?

### ISSUE THREAD

**Issue by tcampbPPU** [node-schedule/node-schedule#513]
Is there some property or method to be able to access a specific job will its waiting to be fired?

For example in my app users can set times for emails to be sent off. If I allow the user to edit that submission time after it already has been added to the scheduler how could I get that job instance and change the date to be the new submission date? 

Thanks for the help in advance!
-tcampbPPU

**Comment by alekseytsvetkov** [comment]
I have a similar problem and also don't know how to solve it

**Comment by terwinsamsung** [comment]
@tcampbPPU if I understand you correctly you should just be able to do that right on the job instance itself...

```
var j = schedule.scheduleJob('0 17 ? * 0,4-6', function(){
  console.log('Today is recognized by Rebecca Black!');
});

// j is the job instance...

j.reschedule(...);
```

**Comment by tcampbPPU** [comment]
@terwinsamsung Correct but that only to appears to work when you 1 single job. In my instance, I load many jobs to the scheduler. Given the example below there doesn't seem to be a solution to this:
```
// Will submit a series of jobs to the scheduler

// array of imaginary times
let jobs = [new Date(), new Date(), new Date()];
for (let i = 0; i < jobs.length; i++) {
     var j = schedule.scheduleJob(jobs[i], () => {
          // Do something when job timer goes off
     });
}
```
In the example above how could I edit the 2 job time before it will fire.

My issue is I have many jobs that weight to get fired and if my users edit that before it gets sent I need to be able to update that instance.

**Comment by tcampbPPU** [comment]
@alekseytsvetkov Are you still facing a similar issue to myself?

**Comment by terwinsamsung** [comment]
@tcampbPPU you have to store a hash to track the jobs....

```
const jobmap = {};

let jobs = [{ id: 1, date: new Date() }, { id: 2, date: new Date() }, {id: 3, date: new Date() }];

for (let i = 0; i < jobs.length; i++) {
     const job = jobs[i];

     jobmap[job.id] = schedule.scheduleJob(jobs.date, () => {
          // Do something when job timer goes off
     });
}

later....

jobs[2].reschedule(...);
```

**Comment by tcampbPPU** [comment]
@terwinsamsung Ahh I see, no worries. That solution will work!

Thanks!!

**Comment by priya0607jain** [comment]
Hello. Even I faced a similar problem. I followed the given approach for my single job. But the addition to it, what I need is to persist the job created in the last based on it's 'id' to the database so that these can be accessible later from the mongo dB too. But when I `console.log(jobmap)`, it returns {'5ed4a1cf023e8f12f85fa83d': null }. Please help on this issue asap.
