### ISSUE TITLE
Is there any rule dayOfMonth exactly like dayOfWeek?

### ISSUE THREAD

**Issue by Hamza-Khurshid** [node-schedule/node-schedule#514]
Actually I want to repeat a job on specific days of every month like on 10th, 17th, 24th of every moth.

**Comment by shanike** [comment]
me too

**Comment by shanike** [comment]
there is an option for that. as shown in the documentation

**Comment by Hamza-Khurshid** [comment]
> there is an option for that. as shown in the documentation

can you please share link

**Comment by santigimeno** [comment]
@Hamza-Khurshid only if you use the `cron` syntax (see README)

**Comment by shanike** [comment]
var schedule = require('node-schedule');
let rule = new schedule.RecurrenceRule();
rule.dayOfMonth = 25;
rule.hour = 7;
rule.minute = 30;
let job = schedule.scheduleJob(rule, () => {
  console.log('25th is today, rule is happenning, the time is: ' + Date());
});

**Comment by shanike** [comment]
https://www.npmjs.com/package/node-schedule
