### ISSUE TITLE
Scheduler is stopped after 25-30 days

### ISSUE THREAD

**Issue by rohitpatil7892** [node-schedule/node-schedule#516]
In the server, the VM environment scheduler gets stop after 25-30(Not sure about exact) days.
 Our scheduler executes the below rule.

`const k = schedule.scheduleJob('* * * * *', async() => { console.log('This job runs every 1 minute.'); });
`
Does anybody have an idea about why my node scheduler process stops? I checked the logs and there were no errors in logs.

**Comment by j1151300783** [comment]
based on [#473](https://github.com/node-schedule/node-schedule/issues/473)
Please check your node version.

**Comment by rohitpatil7892** [comment]
Node version 10.17.0 is an updated one but still facing these issues.

**Comment by xinyi1989** [comment]
@j1151300783  I have the same issue, And my node version is v10.13.0.

**Comment by j1151300783** [comment]
@rohitpatil7892 @xinyi1989 
That's bad news to me.
[#494 ](https://github.com/node-schedule/node-schedule/issues/494)
i have updated my node version to 10.13.0 and wait the result.
i will keep looking for the solution.

**Comment by rohitpatil7892** [comment]
@j1151300783 
We apologize about we provided some wrong information mistakenly to you.
Actually our development environment uses a node with version v11.13.0 and our production environment uses the node of version v10.7.0 (base on docker image node:10.7-alpine).
We found that the Scheduler from 'node-schedule' npm package stops execution after 25 days on the production environment which uses a node with version v10.7.0.

So if we upgraded the production environment with node v10.9.0, will this issue be reproduced or not?

**Comment by j1151300783** [comment]
@rohitpatil7892 
It's good to know that.
according to  [#473](https://github.com/node-schedule/node-schedule/issues/473)
>  It seems this is a bug that was fixed in Node 10.9.0
> [nodejs/node#22149](https://github.com/nodejs/node/issues/22149)

I am testing now. 
No matter success or fail, i will let you know.

**Comment by nxycdl** [comment]
I have the same problem

**Comment by j1151300783** [comment]
Solve by updating my node version.

**Comment by JVaghela-Fintech** [comment]
Facing the same issue in node 14.7.0, the node-schedule stops working after 26 days.

**Comment by centigrade-thomas-becker** [comment]
I have the same issue using node 14.17.6 (node:14-alpine to be precise) and node-schedule 1.2.1.

A docker container using node-schedule was created on 2021-09-02 and it executed a daily cronjob using the pattern "0 6 * * *".

The cronjob in the container was executed daily without error for 35 days until at 2021-10-07 when the cronjob ran for the last time. Since 2021-10-08 the cronjob did not start anymore. There is no error anywhere in the logs.
