### ISSUE TITLE
node-schedule no longer supported?

### ISSUE THREAD

**Issue by Bobo-amg** [node-schedule/node-schedule#519]
Just wondering what the deal is, as there the number of issues is growing and there doesn't seem to be any response from devs.

Anyone know?

**Comment by jawaaad** [comment]
HI, it just seems like that, I stumbled upon this package, I have a query and I'm afraid I'm not gonna get any response either. Can you tell me  how many jobs can i schedule at once with node-schedule? what would be the memory limitations etc? lets say  my users grow in number and they can schedule the jobs for the dates they specify, and lets if there're like 100K users who want to schedule the jobs what limitations could be incurred while doing it?

**Comment by Bobo-amg** [comment]
I would be looking for something else. There are a few bugs lurking within, and with no response from any of the devs I don't think this is worth the trouble.

**Comment by renato** [comment]
@Bobo-amg any recommendation? other similar projects are abandoned.

**Comment by Bobo-amg** [comment]
I have successfully integrated this into my node-red project: https://github.com/kelektiv/node-cron
All the issues I was having with node-schedule have now gone away.

**Comment by renato** [comment]
@Bobo-amg thanks. I'm using this too, the only concern is the [bundle size](https://bundlephobia.com/result?p=cron@1.8.2) (https://github.com/kelektiv/node-cron/issues/402), but it's a lesser concern.

**Comment by msageryd** [comment]
If you want the cron syntax Bree is the best (according to Bree =) 
https://github.com/breejs/bree

If you want RRule scheduling you might be interested in my take on this. I forked node-schedule at first. But now it's detached, due to too big code differences. I will be using this in production myself soon. If I see interest from others, I'll make the final touches sooner.
https://github.com/msageryd/node-schedule-rrule

**Comment by P4sca1** [comment]
Hello! I created a similar library for working with cron expressions. Since this is my first open source project, I would really appreciate any feedback.
You can find it here: https://github.com/P4sca1/cron-schedule

**Comment by jgonera** [comment]
Found https://github.com/jaclarke/cronosjs which looks like a promising replacement.

**Comment by kibertoad** [comment]
@tejasmanohar I can step in to maintain this library if you feel like you could use some help.

**Comment by tejasmanohar** [comment]
Hi all! I no longer actively maintain on this package. I'm happy to let someone else take over.

@kibertoad I just invited you as a member of this organization, which would allow you to start maintaining the package. I'm going to trust your GitHub profile since you're also a maintainer on knexjs.

**Comment by kibertoad** [comment]
@tejasmanohar Much appreciated! Will start the basic housekeeping this week :).
Does that include npm permissions or you would like to handle publishing yourself for a while ?

**Comment by kibertoad** [comment]
@tejasmanohar Could you please publish 1.3.3?
Planning to switch into 2.0.0 mode after that.

**Comment by tejasmanohar** [comment]
@kibertoad Added you as a maintainer on npmjs

**Comment by kibertoad** [comment]
Aaaaand we are back on track :)

**Comment by xinthose** [comment]
Are we though?

**Comment by kibertoad** [comment]
@xinthose Any particular issues that you believe demand immediate attention?
