### ISSUE TITLE
Is this library maintained?

### ISSUE THREAD

**Issue by PabloHernanVila** [node-schedule/node-schedule#525]
I'd like to know if this library is currently maintained and will continue to be. I see that the last commit is from more than a year ago and a lot of issues open. It's safe to use this library?

Thanks very much

**Comment by JuanCasian** [comment]
I would like to know this too

**Comment by PabloHernanVila** [comment]
This lib is not maintained anymore, I think users should see [node_cron](https://github.com/kelektiv/node-cron) for similar functionallity.
