### ISSUE TITLE
Start / Stop the scheduler

### ISSUE THREAD

**Issue by tbhaxor** [node-schedule/node-schedule#528]
Hey, nice package.

I got some doubt, how do i stop / start the scheduler programatically?

**Comment by amisys** [comment]
Hello @tbhaxor , check this out, see if helps you:

`var jobStart = () => { let job = scheduler.scheduleJob(rule,actions) }`
`// do whatever`
`jobStart()`

You can i.e. make "actions" be a Promise that calls `job.cancel()` upon rejection.
