### ISSUE TITLE
Launch task at startup

### ISSUE THREAD

**Issue by qvdp** [node-schedule/node-schedule#530]
Hello :)

First of all sorry if the answer in my question could be found in the documentation or in github issues, but I have been searching without success.

I would like to know if their is a way to run my sheduled tasks at server-startup. 

```
...
schedule.scheduleJob(resetPasswordRecoveryToken.scheduledTime, resetPasswordRecoveryToken.task)
...
```

```
scheduledTime: '0 */6 * * *'
```

Here is why, I have several tasks cheduled to run each 6 hours on my server (for example `resetPasswordRecoveryToken`) and I would like to be able to trigger the first round of runned tasks at server startup, meaning trigger `resetPasswordRecoveryToken.task()` and then repeat the task each 6 hours as it does currently.

Is there any option in node-schedule to do that (i.e. `@boot`) or should I trigger the task manually ?

Thank you for you answer.

**Comment by faulander** [comment]
you can use the date function to get a date/time a few seconds after startup and then fire it at that given date.
