### ISSUE TITLE
Do you have a plan to support graceful shutdown?

### ISSUE THREAD

**Issue by changmyeong** [node-schedule/node-schedule#549]
I need gracefully shutdown of node-schedule.
I will edit your code by cloning it. 

Can I contribute it?

**Comment by kibertoad** [comment]
Yes. This is very high on my to-do list.

**Comment by changmyeong** [comment]
@kibertoad OK. I will PR soon :)

**Comment by kibertoad** [comment]
Released in 2.1.0
