### ISSUE TITLE
every 15 minutes problem

### ISSUE THREAD

**Issue by igordeoliveirasa** [node-schedule/node-schedule#552]
How to execute every 15 minute? I tried '* */15 * * * *' but it did not work...

**Comment by akshayajeevan** [comment]
Try `0 */15 * * * *`

**Comment by kibertoad** [comment]
@igordeoliveirasa See official documentation: Node Schedule is for time-based scheduling, not interval-based scheduling..
For interval-based scheduling ("fire each 7 seconds"), toad-scheduler (https://github.com/kibertoad/toad-scheduler) is a much better fit.
