### ISSUE TITLE
run scheduler on live server

### ISSUE THREAD

**Issue by tehceen** [node-schedule/node-schedule#572]
how to run the scheduler permanently mean when i close the terminal the scheduler also stop working. i want it to work like pm2 when  i close the termnial it should run also.

**Comment by kibertoad** [comment]
@tehceen See the official documentation:

```
Note that Node Schedule is designed for in-process scheduling, i.e. scheduled jobs will only fire as long as your script is running, and the schedule will disappear when execution completes. If you need to schedule jobs that will persist even when your script isn't running, consider using actual cron.
```

You would need to wrap in some kind of a simplistic app to achieve your purpose and run it with something like `nodemon`.
