### ISSUE TITLE
Memory Leak on linux systems

### ISSUE THREAD

**Issue by brys0** [node-schedule/node-schedule#611]
Currently these 'cron' type libs cause severe memory issues on Linux systems, we have tried to fix it, with no success. They only appear to work on Windows. It not only causes a memory leak but spikes the CPU to the point of the process, below is an attached picture of the error that is occurring.

![ERROR](https://user-images.githubusercontent.com/35676267/120930407-b9495000-c6b2-11eb-8a3c-a08ecab3c6ce.png)

**Comment by kibertoad** [comment]
Which node-schedule and Node versions are you using?

**Comment by kibertoad** [comment]
Also how are you using it? Are you scheduling anything dynamically in the runtime, or everything is registered at a startup?
Also what is your scheduling use-case?

**Comment by brys0** [comment]
Hi! Yes sorry about that this issue is fixed now it was due to a database controller issue specifically mongoose, and yes thats precisely where the issue occured when we tried to dynamicly assign a new element to the array of the data, thanks for responding we have it resolved now.. curious how the issue only occurred on linux though
