### ISSUE TITLE
Unreleased Patches: bump cron-parser from 3.5.0 to 4.4.0 #642

### ISSUE THREAD

**Issue by carboneater** [node-schedule/node-schedule#723]
Over the weekend, there was a new github advisory on Luxon 1, which is used in cron-parser 3.5.  
https://github.com/advisories/GHSA-3xq5-wjfh-ppjc

The 4.x branch of cron-parser is patched.

As the code is already committed, would you mind releasing `2.1.1` to address this vulnerability?  
Is there any thing I can do to help?

Thanks

**Comment by kibertoad** [comment]
Sure, I'll release

**Comment by kibertoad** [comment]
Released in 2.1.1
