### ISSUE TITLE
There are times on high loads when specific cron jobs are not triggered at all until the next day.

### ISSUE THREAD

**Issue by greg-md** [node-schedule/node-schedule#732]
I don't have a specific test case, but during high loads and long running jobs, there are jobs that are not running at all and they are starting to trigger only after few hours/next day. So there is a problem on the schedule side which is not triggering them in time.

I saw that there are a few tickets related to the same issue but on different behaviors (like https://github.com/node-schedule/node-schedule/issues/707). Can you please investigate?

**Comment by lalitwinjit** [comment]
@greg-md  I am facing the same issue? can you please assist me here? how you solve this issue?
