### ISSUE TITLE
integrate travis ci for tests

### ISSUE THREAD

**Issue by tejasmanohar** [node-schedule/node-schedule#92]
https://travis-ci.org - we can get this nice banner in the readme then (below)

![banner](http://i.imgur.com/yQd90xk.png)

thoughts on this?

**Comment by jonhester** [comment]
:+1:

**Comment by santigimeno** [comment]
:+1:

**Comment by jonhester** [comment]
https://github.com/node-schedule/node-schedule/pull/98

**Comment by jonhester** [comment]
Still needs to be setup on the travis side. A maintainer will need to do the following:

## Step one: Sign in

To get started with Travis CI, sign in with your GitHub account. Go to Travis CI and follow the Sign In link at the top.

Note that on https://travis-ci.org, you'll currently only see your public repositories, whereas on https://travis-ci.com, you can find your private projects.

While signing in, GitHub will ask you for a set of access permissions on our behalf. We've outlined them and their use in more detail.

## Step two: Activate GitHub Webhook

Once you're signed in, and we've initially synchronized your repositories from GitHub, go to your profile page for open source or for your private projects.

You'll see all the organizations you're a member of and all the repositories you have access to. The ones you have administrative access to are the ones you can enable the service hook for.

Flip switch to on for all repositories you'd like to enable.

**Comment by tejasmanohar** [comment]
@jonhester Looks like travis ci is erroring. The flip switches but the request made by flipping the switch fails, as seen by console error (chrome JS console when flipping switch on travis for this repo):

`XMLHttpRequest cannot load https://api.travis-ci.org/hooks/3635277. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://travis-ci.org' is therefore not allowed access. The response had HTTP status code 500.`

Going to make an issue on Travis CI for this

**Comment by tejasmanohar** [comment]
https://github.com/travis-ci/travis-ci/issues/3335

**Comment by jonhester** [comment]
@tejasmanohar Well that's a bummer, it was working when I set it up on mine earlier.

**Comment by tejasmanohar** [comment]
@jonhester Still works on my other repo, something is acting up. Made an issue + asked in IRC. Hope it's fixed soon :tada:
