### ISSUE TITLE
Intermittently not firing on the start of each minute

### ISSUE THREAD

**Issue by andrewwakeling** [node-schedule/node-schedule#96]
Using the simple example below:

````javascript
var schedule = require('node-schedule');

var j = schedule.scheduleJob("* * * * *", function(){
    console.log((new Date()));
});
````
I am seeing cases where my job [isn't firing at the start of every minute.](https://gist.github.com/andrewwakeling/972049948b05cfd3d78d)

(Edit: I think my laptop may have suspended a few times during my log. I'm still seeing cases where it repeatedly runs "off" the start of the minute). 

I there something I can do to make this fire more accurately?

**Comment by santigimeno** [comment]
@andrewwakeling I'm trying to reproduce the issue you're seeing but no luck for the moment. (Only 1 hour test ATM). 
Do you see any pattern? After how long it starts failing, etc.?
In which timezone are you on?
What version of node are you using?

Thanks

**Comment by santigimeno** [comment]
Being testing this for a day and only twice I had a variation of 2 seconds

**Comment by jonhester** [comment]
@santigimeno Since the tests use fake timers couldn't we extend time for the test cases or add some new ones that cover longer durations?

**Comment by santigimeno** [comment]
We could do that but I'm not sure that would uncover the issue. It looks to me more of a problem of the environment (cpu load, etc). Anyway, I'll try to come up with some tests and see how it goes

**Comment by tejasmanohar** [comment]
Thought I'd add in -> I also cannot replicate this issue.

**Comment by tejasmanohar** [comment]
Hey @andrewwakeling any luck on this?

**Comment by andrewwakeling** [comment]
I'm still capable of reproducing it. I believe it's happening when my machine is powering up again, (from being suspended).
I'm using:
- Node version 0.11.14
- "node-schedule" version 0.2.3

I'm on OSX 10.10.1.

**Comment by jonhester** [comment]
So I think what's happening is it's basically catching up for everything that it missed while the computer was asleep. A potential fix would be to store the last time a job ran in each job. If it's been less than a second since it's last run, we don't run it. Thoughts?

**Comment by tejasmanohar** [comment]
(revisiting old issues now that I can be more active on node-schedule again)

@andrewwakeling When I tested this putting my computer to sleep and woke it up again on OS X, it looks like that's what happened to me, too.

Saving the last run time is the only way that makes sense to me, @jonhester. I'm on it.

/cc @santigimeno

**Comment by santigimeno** [comment]
I don't know. I don't think it will always be a good idea running the *missing* jobs immediately after the computer awakes. It will depend on the case I guess. So I would not implement anything special for this case

**Comment by jonhester** [comment]
How about the default behavior not running missed jobs. And add an option to the API to enable running missed jobs on resume?

**Comment by tejasmanohar** [comment]
>I don't know. I don't think it will always be a good idea running the missing jobs immediately after the computer awakes. It will depend on the case I guess. So I would not implement anything special for this case
That's true... I have to think about this some more.

>How about the default behavior not running missed jobs. And add an option to the API to enable running missed jobs on resume?
Maybe, I'd not like to make node-schedule too complex; people are better off with a full fledged persistent job scheduler dependent on the use case.

**Comment by tejasmanohar** [comment]
yeah, let's not cover for sleeping. we can't assume what the program wants.
